"""GRASP git host — repo provisioning, path mapping, hook installation, size/gc bounding (P0/P2).

Bare repos live under `data/git_repos/<owner_pubkey_hex>/<repo-id>.git`. This module owns:
  - the URL npub -> on-disk path mapping (with strict traversal-proof sanitization),
  - lazy creation of a bare repo + install of the GRASP auth hooks,
  - per-repo/global size accounting + a rate-limited gc reaper (bound background CPU).

It runs in the FastAPI app process (provisioning is an admin request); the actual git smart-HTTP
serving + auth hooks run in the SEPARATE git_host_main.py subprocess. Keep git work off this process:
this module only does `git init --bare`/config/`for-each-ref`/`gc` — small, occasional, admin-driven —
never upload-pack/receive-pack/pack streaming (those are the subprocess's job).
"""

import json
import logging
import os
import re
import subprocess
import sys
import time

from app.services.nostr import bech32

logger = logging.getLogger(__name__)

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def git_project_root() -> str:
    """Repo store root. Resolution order:
      1. GRASP_GIT_PROJECT_ROOT env — set by git_host_main into the CGI/hook environment (so the fresh
         pre-receive/post-receive subprocesses resolve the SAME root the server served from) and by a
         container/turnkey that relocates the store.
      2. the operator's Storage Path (`upload_path` setting) + /git_repos — so repos live on the SAME
         volume as uploaded media (e.g. /raid/posterchanai/git_repos), not the small system/code disk.
      3. /var/lib/posterchanai/git_repos as a last-resort default.
    Computed LAZILY (not a module constant) so it reflects the setting once the datastore has hydrated —
    an import-time constant would freeze the default before settings load."""
    env = os.environ.get("GRASP_GIT_PROJECT_ROOT")
    if env:
        return env
    up = ""
    try:
        from app.services import settings_store
        up = (settings_store.get("upload_path", "") or "").strip()
    except Exception:
        up = ""
    return os.path.join(up or "/var/lib/posterchanai", "git_repos")


GIT_HTTP_BACKEND = "/usr/libexec/git-core/git-http-backend"

# A repo id is the 30617 d-tag (a slug). Strict allowlist so it can never escape GIT_PROJECT_ROOT.
_ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,99}$")


def sanitize_repo_id(repo_id: str) -> str | None:
    """Return a safe repo id or None. Rejects traversal (`..`, `/`), absolute paths, uppercase,
    and anything outside [a-z0-9._-]. A leading dot is rejected (no `.`/`..`/dotfiles)."""
    if not isinstance(repo_id, str):
        return None
    s = repo_id.strip().lower()
    if s.endswith(".git"):
        s = s[:-4]
    if not s or s in (".", "..") or "/" in s or "\\" in s or ".." in s:
        return None
    if not _ID_RE.match(s):
        return None
    return s


def owner_hex_from_npub(npub_or_hex: str) -> str | None:
    """URL owner segment (npub1... or 64-hex) -> 64-char lowercase hex, else None."""
    s = (npub_or_hex or "").strip()
    if len(s) == 64:
        try:
            bytes.fromhex(s)
            return s.lower()
        except ValueError:
            return None
    if s.startswith("npub1"):
        raw = bech32.decode("npub", s)
        return raw.hex() if raw and len(raw) == 32 else None
    return None


def repo_dir(owner_hex: str, repo_id: str) -> str | None:
    """Traversal-proof path for a repo. Both components are validated; the result is asserted to be
    strictly under GIT_PROJECT_ROOT (defense in depth against any sanitizer gap)."""
    if not (isinstance(owner_hex, str) and len(owner_hex) == 64):
        return None
    try:
        bytes.fromhex(owner_hex)
    except ValueError:
        return None
    rid = sanitize_repo_id(repo_id)
    if not rid:
        return None
    root = git_project_root()
    path = os.path.join(root, owner_hex.lower(), rid + ".git")
    real_root = os.path.realpath(root)
    real_path = os.path.realpath(path)
    if real_path != path and not real_path.startswith(real_root + os.sep):
        return None
    if not (path == os.path.join(root, owner_hex.lower(), rid + ".git")
            and os.path.commonpath([real_root, os.path.realpath(os.path.dirname(path))]) == real_root):
        return None
    return path


def repo_exists(owner_hex: str, repo_id: str) -> bool:
    d = repo_dir(owner_hex, repo_id)
    return bool(d) and os.path.isdir(d)


def _hook_script(target_py: str) -> str:
    """A tiny shell shim git invokes; it execs the venv python on the shared validator, forwarding
    stdin (the ref lines) + the inherited environment (GRASP_* config). Pinned to the interpreter +
    repo root at creation time so hooks work regardless of git's cwd."""
    py = sys.executable
    return (
        "#!/bin/sh\n"
        "# GRASP hook shim (auto-generated by git_host_service). Do not edit.\n"
        "exec %s %s\n" % (
            _shq(py), _shq(os.path.join(_REPO_ROOT, "git_hooks", target_py)))
    )


def _shq(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


def install_hooks(gitdir: str) -> None:
    """Install pre-receive (push auth) + post-receive (30618 witness) shims. Overwrites so a code
    move/interpreter change is picked up on the next provision/reconcile."""
    hooks = os.path.join(gitdir, "hooks")
    os.makedirs(hooks, exist_ok=True)
    for name, py in (("pre-receive", "pre_receive.py"), ("post-receive", "post_receive.py")):
        p = os.path.join(hooks, name)
        with open(p, "w") as f:
            f.write(_hook_script(py))
        os.chmod(p, 0o755)


def _git(gitdir: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "--git-dir", gitdir, *args],
                          capture_output=True, text=True, check=check, timeout=60)


def _norm_reader_list(readers) -> list:
    """Normalize a readers list (hex/npub) to a deduped list of 64-hex pubkeys."""
    out = []
    for pk in (readers or []):
        h = owner_hex_from_npub(pk)
        if h and h not in out:
            out.append(h)
    return out


def create_repo(owner_hex: str, repo_id: str, *, announcement_addr: str = "",
                private: bool = False, readers=None) -> dict:
    """Idempotently create a bare repo + hooks + config + grasp.json. Returns {ok, path, created}.

    Config choices (security/robustness):
      http.receivepack=true          smart-HTTP push enabled (auth is the hook, not a password).
      receive.fsckObjects=true       reject malformed/objects-smuggling pushes.
      receive.denyNonFastForwards=false   allow signed force-push (gated by git_server_allow_force).
      receive.denyDeletes=false      allow signed deletes.
      gc.auto / receive.autogc=true  bound loose objects automatically after pushes (no per-push gc).

    PRIVATE repos (`private=True`): read (clone/pull) is gated by NIP-98 in the git subprocess; the
    repo is NOT announced (no public 30617/30618) and does NOT use the public Nostr issue/patch flow.
    `readers` are extra pubkeys (beyond the maintainer set) allowed to READ. Persisted BOTH as git
    config (pcai.private / pcai.readers) AND in grasp.json so the subprocess can read the flag off
    disk without a DB hit. Public repos are unchanged (anonymous clone).
    """
    d = repo_dir(owner_hex, repo_id)
    if not d:
        return {"ok": False, "error": "invalid owner/repo id"}
    rid = sanitize_repo_id(repo_id)
    created = not os.path.isdir(d)
    os.makedirs(os.path.dirname(d), exist_ok=True)
    if created:
        r = subprocess.run(["git", "init", "--bare", d], capture_output=True, text=True, timeout=60)
        if r.returncode != 0:
            return {"ok": False, "error": "git init failed: %s" % (r.stderr or r.stdout).strip()}
    # Apply config every time (idempotent) so an existing repo also gets corrected settings.
    reader_hex = _norm_reader_list(readers)
    for k, v in (("http.receivepack", "true"),
                 ("http.uploadpack", "true"),
                 # ngit's remote helper is libgit2-based and asks for a specific OID (`want <sha>`)
                 # taken from the 30618 state rather than negotiating from the advertised refs.
                 # git-upload-pack refuses that unless SHA1-in-want is allowed, so every `git fetch
                 # nostr://…` died with "cannot fetch a specific object from the remote repository".
                 # Reachable-only (not allowAnySHA1InWant) so unreferenced/dangling objects — e.g.
                 # left by a force-push — still can't be fetched by anyone who guesses their sha.
                 ("uploadpack.allowTipSHA1InWant", "true"),
                 ("uploadpack.allowReachableSHA1InWant", "true"),
                 # PARTIAL CLONE. In-browser git clients (gitworkshop.dev and anything else fetching a
                 # repo over fetch()) ask for `filter blob:none` so they can render a tree without
                 # pulling every blob — posterchanai is a 72MB pack, which no browser wants. Without
                 # this, git does not advertise `filter`, and a client that asks anyway gets
                 # upload-pack exiting mid-stream: HTTP 200 with a ZERO-byte body, which surfaces as
                 # "couldn't fetch the objects (upload-pack failed)" and looks like a network fault
                 # rather than a refused capability. Costs nothing for ordinary clones.
                 ("uploadpack.allowFilter", "true"),
                 ("receive.fsckObjects", "true"),
                 ("receive.denyNonFastForwards", "false"),
                 ("receive.denyDeletes", "false"),
                 ("receive.denyCurrentBranch", "ignore"),  # bare repo; no working tree to protect
                 ("receive.autogc", "true"),
                 ("gc.auto", "512"),
                 ("pcai.private", "true" if private else "false"),
                 ("pcai.readers", " ".join(reader_hex))):
        _git(d, "config", k, v, check=False)
    install_hooks(d)
    # `git-daemon-export-ok` marks the repo exportable to git-http-backend (GIT_HTTP_EXPORT_ALL also
    # set by the subprocess). PRIVATE repos still get it — export != public; the NIP-98 read gate in
    # git_host_main.py runs BEFORE git-http-backend, so this only matters once access is granted.
    try:
        open(os.path.join(d, "git-daemon-export-ok"), "w").close()
    except OSError:
        pass
    meta = {"owner": owner_hex, "repo_id": rid,
            "private": bool(private),
            "readers": reader_hex,
            # A private repo is intentionally NOT announced, so it has no public addressable coord.
            "announcement_addr": "" if private else (announcement_addr or ("30617:%s:%s" % (owner_hex, rid))),
            "created_at": int(time.time())}
    try:
        with open(os.path.join(d, "grasp.json"), "w") as f:
            json.dump(meta, f)
    except OSError:
        pass
    logger.info("[git-host] %s %srepo %s/%s", "created" if created else "reconciled",
                "PRIVATE " if private else "", owner_hex[:12], rid)
    return {"ok": True, "path": d, "created": created, "meta": meta}


def repo_private_meta(owner_hex: str, repo_id: str) -> dict:
    """Read {private: bool, readers: [hex]} for a repo from disk (grasp.json, falling back to git
    config). NO DB hit — safe to call on every request in the subprocess. Fail-closed default:
    if the repo/metadata can't be read cleanly we return private=True (deny by default) ONLY when the
    repo dir exists; a missing repo returns private=False (the 404 path handles nonexistence)."""
    d = repo_dir(owner_hex, repo_id)
    if not d or not os.path.isdir(d):
        return {"private": False, "readers": []}
    try:
        with open(os.path.join(d, "grasp.json")) as f:
            meta = json.load(f)
        return {"private": bool(meta.get("private")),
                "readers": _norm_reader_list(meta.get("readers"))}
    except (OSError, ValueError):
        pass
    # grasp.json unreadable but repo exists -> consult git config; if THAT fails, deny (fail-closed).
    try:
        pv = _git(d, "config", "--get", "pcai.private", check=False).stdout.strip().lower()
        rd = _git(d, "config", "--get", "pcai.readers", check=False).stdout.strip()
        return {"private": pv in ("1", "true", "yes", "on"),
                "readers": _norm_reader_list(rd.split())}
    except Exception:
        return {"private": True, "readers": []}   # existing repo, indeterminate -> deny reads


def is_private(owner_hex: str, repo_id: str) -> bool:
    return bool(repo_private_meta(owner_hex, repo_id).get("private"))


def repo_refs(owner_hex: str, repo_id: str) -> dict:
    """Current on-disk refs {refname: sha} via for-each-ref. Used to build a 30618 witness/state."""
    d = repo_dir(owner_hex, repo_id)
    if not d or not os.path.isdir(d):
        return {}
    r = _git(d, "for-each-ref", "--format=%(refname) %(objectname)", check=False)
    refs = {}
    for line in (r.stdout or "").splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[0].startswith("refs/"):
            refs[parts[0]] = parts[1]
    return refs


def repo_head(owner_hex: str, repo_id: str) -> str:
    d = repo_dir(owner_hex, repo_id)
    if not d or not os.path.isdir(d):
        return ""
    r = _git(d, "symbolic-ref", "HEAD", check=False)
    return (r.stdout or "").strip()


def adopt_head_if_unborn(owner_hex: str, repo_id: str) -> str:
    """Point HEAD at a real branch when the repo's default branch was never born. Returns the ref
    HEAD ends up on ("" if unchanged/unknown).

    `git init --bare` stamps HEAD from the SERVER's init.defaultBranch (master here), so a repo whose
    first push is `main` is left with HEAD -> refs/heads/master, a branch that does not exist. Clones
    survive it (git falls back to the only advertised branch), but every reader that asks the repo for
    its DEFAULT branch — the web Git UI's browse ref, the 30618 HEAD tag — gets a dead ref. Nothing
    else sets it, and there is no endpoint to set it by hand, so the push that creates the first
    branch adopts it here.

    Only ever fires when HEAD's target does NOT exist: an established default branch is never
    retargeted, so this cannot hijack a repo that deliberately points HEAD elsewhere."""
    rid = sanitize_repo_id(repo_id)
    d = repo_dir(owner_hex, rid) if rid else None
    if not d or not os.path.isdir(d):
        return ""
    refs = repo_refs(owner_hex, rid)
    head = repo_head(owner_hex, rid)
    if head and head in refs:
        return ""                     # already born — leave it alone
    heads = sorted(r for r in refs if r.startswith("refs/heads/"))
    if not heads:
        return ""                     # empty repo: HEAD stays as-is until something is pushed
    # Prefer the conventional names when the push brought several branches at once, else the first.
    pick = next((r for r in ("refs/heads/main", "refs/heads/master") if r in heads), heads[0])
    r = _git(d, "symbolic-ref", "HEAD", pick, check=False)
    return pick if r.returncode == 0 else ""


def state_tags(owner_hex: str, repo_id: str, refs: dict | None = None, head: str | None = None) -> list:
    """NIP-34 kind-30618 ("repository state") tags for a repo's CURRENT refs: d, HEAD, every
    refs/… -> sha, and an `a` link back to the 30617 announcement.

    ONE builder for every producer of a 30618 — the post-receive witness, the web-editor commit, and
    the announce endpoint — because git_auth.decide_push_ref authorizes a push by SHA-matching these
    tags. Two hand-rolled copies that drift in tag shape would mean pushes that mysteriously fail."""
    rid = sanitize_repo_id(repo_id) or repo_id
    if refs is None:
        refs = repo_refs(owner_hex, rid)
    if head is None:
        head = repo_head(owner_hex, rid)
    tags = [["d", rid]]
    if head:
        tags.append(["HEAD", "ref: " + head])
    for name, sha in sorted((refs or {}).items()):
        tags.append([name, sha])
    tags.append(["a", "30617:%s:%s" % (owner_hex, rid)])
    return tags


def publish_state_witness(owner_hex: str, repo_id: str) -> bool:
    """Publish an OPERATOR-signed kind-30618 mirroring the repo's on-disk refs to the LOCAL relay.

    Best-effort and always safe to call: any failure returns False rather than raising, because no
    ref-moving operation should fail on account of a relay hiccup. PRIVATE repos are skipped (they
    must not publish any public 30617/30618).

    Runs its own event loop, so call it from a plain thread or a one-shot process (the git host
    subprocess, a git hook) — NEVER from inside the app's running loop; use nostr_store.publish_event
    directly there."""
    import asyncio
    rid = sanitize_repo_id(repo_id)
    if not rid or not repo_exists(owner_hex, rid) or is_private(owner_hex, rid):
        return False
    try:
        from app.services import keystore
        op_nsec = keystore.get_operator_nsec()
        if not op_nsec:
            return False
        from app.services.nostr import nostr_service
        from app.services.nostr.event import build_event
        from app.services import nostr_store
        ev = build_event(nostr_service.decode_seckey(op_nsec), 30618, "",
                         tags=state_tags(owner_hex, rid))
        port = int(os.environ.get("GRASP_RELAY_PORT", "3052"))
        loop = asyncio.new_event_loop()
        try:
            asyncio.set_event_loop(loop)
            ok, msg = loop.run_until_complete(nostr_store.publish_event(port, ev, timeout=6.0))
        finally:
            loop.close()
            asyncio.set_event_loop(None)
        if not ok:
            logger.warning("[git-host] 30618 witness not published for %s/%s: %s",
                           owner_hex[:12], rid, msg)
        return bool(ok)
    except Exception as e:
        logger.warning("[git-host] 30618 witness publish failed for %s/%s: %s", owner_hex[:12], rid, e)
        return False


def dir_size_bytes(path: str) -> int:
    total = 0
    for root, _dirs, files in os.walk(path):
        for fn in files:
            try:
                total += os.path.getsize(os.path.join(root, fn))
            except OSError:
                pass
    return total


def list_repos() -> list:
    """Enumerate hosted repos (owner_hex, repo_id, size_mb, refs count, created_at)."""
    out = []
    root = git_project_root()
    if not os.path.isdir(root):
        return out
    for owner in os.listdir(root):
        odir = os.path.join(root, owner)
        if not (os.path.isdir(odir) and len(owner) == 64):
            continue
        for name in os.listdir(odir):
            if not name.endswith(".git"):
                continue
            d = os.path.join(odir, name)
            rid = name[:-4]
            meta = {}
            try:
                with open(os.path.join(d, "grasp.json")) as f:
                    meta = json.load(f)
            except (OSError, ValueError):
                pass
            out.append({
                "owner": owner, "repo_id": rid,
                "size_mb": round(dir_size_bytes(d) / (1024 * 1024), 2),
                "refs": len(repo_refs(owner, rid)),
                "created_at": meta.get("created_at"),
                "private": bool(meta.get("private")),
                "readers": meta.get("readers", []),
                "announcement_addr": meta.get("announcement_addr", ""
                                              if meta.get("private") else "30617:%s:%s" % (owner, rid)),
            })
    return out


def total_size_gb() -> float:
    root = git_project_root()
    if not os.path.isdir(root):
        return 0.0
    return round(dir_size_bytes(root) / (1024 ** 3), 3)


# Rate-limited gc reaper: gc is CPU/IO heavy, so NEVER per-push (receive.autogc already bounds loose
# objects). This runs at most once per repo per interval, invoked by a daily scheduler.
_GC_MIN_INTERVAL = 6 * 3600
_last_gc: dict = {}


def maybe_gc(owner_hex: str, repo_id: str, *, force: bool = False) -> bool:
    d = repo_dir(owner_hex, repo_id)
    if not d or not os.path.isdir(d):
        return False
    key = d
    now = time.time()
    if not force and (now - _last_gc.get(key, 0)) < _GC_MIN_INTERVAL:
        return False
    _last_gc[key] = now
    try:
        _git(d, "gc", "--auto", "--quiet", check=False)
        return True
    except Exception as e:
        logger.debug("[git-host] gc %s failed: %s", key, e)
        return False


def reap_all(total_cap_gb: float) -> dict:
    """Daily best-effort reaper: gc each repo (rate-limited) and warn if the global cap is exceeded.
    Intentionally does NOT delete data — bounding is per-repo push-time (the hook) + operator action."""
    repos = list_repos()
    for r in repos:
        maybe_gc(r["owner"], r["repo_id"])
    total = total_size_gb()
    over = total > total_cap_gb if total_cap_gb > 0 else False
    if over:
        logger.warning("[git-host] total git storage %.2f GB exceeds cap %.2f GB — consider pruning",
                       total, total_cap_gb)
    return {"repos": len(repos), "total_gb": total, "cap_gb": total_cap_gb, "over_cap": over}
