package place.poster.app.home;

import place.poster.app.R;

/**
 * A SPRITE NAME -> A DRAWABLE.
 *
 * GENERATED by scripts/gen_android_icons.py beside the drawables themselves; do not edit.
 * A switch rather than getIdentifier() because that is a runtime string lookup, invisible to
 * lint and to the resource shrinker, which answers 0 for a typo -- an icon that silently does
 * not draw. This one is checked by the compiler.
 */
public final class TileIcons {

    private TileIcons() { }

    /** 0 when there is no such icon -- the caller draws nothing rather than crashing on a bad id. */
    public static int of(String icon) {
        if (icon == null) return 0;
        if ("ai".equals(icon)) return R.drawable.ic_pc_ai;
        if ("arrow-left".equals(icon)) return R.drawable.ic_pc_arrow_left;
        if ("article".equals(icon)) return R.drawable.ic_pc_article;
        if ("bag".equals(icon)) return R.drawable.ic_pc_bag;
        if ("bars".equals(icon)) return R.drawable.ic_pc_bars;
        if ("bell".equals(icon)) return R.drawable.ic_pc_bell;
        if ("bookmark".equals(icon)) return R.drawable.ic_pc_bookmark;
        if ("calendar".equals(icon)) return R.drawable.ic_pc_calendar;
        if ("call".equals(icon)) return R.drawable.ic_pc_call;
        if ("cards".equals(icon)) return R.drawable.ic_pc_cards;
        if ("chart".equals(icon)) return R.drawable.ic_pc_chart;
        if ("chat".equals(icon)) return R.drawable.ic_pc_chat;
        if ("check".equals(icon)) return R.drawable.ic_pc_check;
        if ("clock".equals(icon)) return R.drawable.ic_pc_clock;
        if ("close".equals(icon)) return R.drawable.ic_pc_close;
        if ("cloud".equals(icon)) return R.drawable.ic_pc_cloud;
        if ("coin".equals(icon)) return R.drawable.ic_pc_coin;
        if ("compass".equals(icon)) return R.drawable.ic_pc_compass;
        if ("concord".equals(icon)) return R.drawable.ic_pc_concord;
        if ("discs".equals(icon)) return R.drawable.ic_pc_discs;
        if ("draft".equals(icon)) return R.drawable.ic_pc_draft;
        if ("eye".equals(icon)) return R.drawable.ic_pc_eye;
        if ("flower".equals(icon)) return R.drawable.ic_pc_flower;
        if ("folder".equals(icon)) return R.drawable.ic_pc_folder;
        if ("gamepad".equals(icon)) return R.drawable.ic_pc_gamepad;
        if ("gear".equals(icon)) return R.drawable.ic_pc_gear;
        if ("git".equals(icon)) return R.drawable.ic_pc_git;
        if ("globe".equals(icon)) return R.drawable.ic_pc_globe;
        if ("grid".equals(icon)) return R.drawable.ic_pc_grid;
        if ("hash".equals(icon)) return R.drawable.ic_pc_hash;
        if ("home".equals(icon)) return R.drawable.ic_pc_home;
        if ("image".equals(icon)) return R.drawable.ic_pc_image;
        if ("key".equals(icon)) return R.drawable.ic_pc_key;
        if ("logout".equals(icon)) return R.drawable.ic_pc_logout;
        if ("magnet".equals(icon)) return R.drawable.ic_pc_magnet;
        if ("mail".equals(icon)) return R.drawable.ic_pc_mail;
        if ("menu".equals(icon)) return R.drawable.ic_pc_menu;
        if ("mic".equals(icon)) return R.drawable.ic_pc_mic;
        if ("music".equals(icon)) return R.drawable.ic_pc_music;
        if ("news".equals(icon)) return R.drawable.ic_pc_news;
        if ("note".equals(icon)) return R.drawable.ic_pc_note;
        if ("paperclip".equals(icon)) return R.drawable.ic_pc_paperclip;
        if ("pause".equals(icon)) return R.drawable.ic_pc_pause;
        if ("pawn".equals(icon)) return R.drawable.ic_pc_pawn;
        if ("phone".equals(icon)) return R.drawable.ic_pc_phone;
        if ("pin".equals(icon)) return R.drawable.ic_pc_pin;
        if ("play".equals(icon)) return R.drawable.ic_pc_play;
        if ("plus".equals(icon)) return R.drawable.ic_pc_plus;
        if ("refresh".equals(icon)) return R.drawable.ic_pc_refresh;
        if ("reply".equals(icon)) return R.drawable.ic_pc_reply;
        if ("search".equals(icon)) return R.drawable.ic_pc_search;
        if ("send".equals(icon)) return R.drawable.ic_pc_send;
        if ("shield".equals(icon)) return R.drawable.ic_pc_shield;
        if ("smile".equals(icon)) return R.drawable.ic_pc_smile;
        if ("spade".equals(icon)) return R.drawable.ic_pc_spade;
        if ("speech".equals(icon)) return R.drawable.ic_pc_speech;
        if ("star".equals(icon)) return R.drawable.ic_pc_star;
        if ("target".equals(icon)) return R.drawable.ic_pc_target;
        if ("terminal".equals(icon)) return R.drawable.ic_pc_terminal;
        if ("translate".equals(icon)) return R.drawable.ic_pc_translate;
        if ("trash".equals(icon)) return R.drawable.ic_pc_trash;
        if ("tv".equals(icon)) return R.drawable.ic_pc_tv;
        if ("user".equals(icon)) return R.drawable.ic_pc_user;
        if ("users".equals(icon)) return R.drawable.ic_pc_users;
        if ("volume".equals(icon)) return R.drawable.ic_pc_volume;
        if ("warn".equals(icon)) return R.drawable.ic_pc_warn;
        return 0;
    }
}
