"""The XRP codec decides where somebody's money goes, and nothing has ever tested it.

Run: venv-unified/bin/python -m unittest tests.test_an_xrp_payment_goes_where_you_typed

`app/services/exodus_xrp_codec.py` was one of 22 modules a coverage audit found with no test and no
check mentioning it anywhere. Most of that list is cosmetic; this one resolves a destination address
and signs a payment, so every guard in it is the difference between a transfer and a loss:

  * an X-address carries its own destination tag, and a tag typed beside one that disagrees with it
    is a contradiction — silently preferring either is a payment credited to the wrong account at
    the receiving exchange, which is indistinguishable from money that never arrived;
  * a TESTNET X-address is well-formed and worthless: paying it on mainnet is a real transfer to a
    key nobody controls;
  * `sign` refuses a payment whose `account` is not the selected wallet's address.

IT RUNS THE REAL CODEC IN THE REAL SDK ENVIRONMENT — `/usr/local/libexec/pc-exodus/xrp-venv`, the
same interpreter `exodus_xrp_sdk.call()` spawns in production, with the same `-I` isolation. The
app's own venv has no `xrpl` at all (deliberately: the SDK is confined to that subprocess), so a
test that stubbed the codec's imports would be asserting against a library that is not the one
running when money moves. With the SDK absent this SKIPS with its reason, and never passes.

The vectors are real, generated by the SDK from one classic address:
    rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh
    X-address, tag 42   XVPcpSm47b1CZkf5AkKM9a84dQHe3mTCLZc5ZAoh11sd5nY
    X-address, no tag   XVPcpSm47b1CZkf5AkKM9a84dQHe3m4sBhsrA4XtnBECTAc
    testnet, tag 42     TVK3SYvMLZR6rEtLDZh3saYHaqFSeMf6Hj2w1dpb7SnJgqn
"""
import json
import os
import subprocess
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CODEC = ROOT / "app/services/exodus_xrp_codec.py"
# The same default `exodus_xrp_sdk._call` uses; the env var is the documented override.
SDK = Path(os.environ.get("EXODUS_XRP_PYTHON",
                          "/usr/local/libexec/pc-exodus/xrp-venv/bin/python"))

CLASSIC = "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh"
X_TAGGED = "XVPcpSm47b1CZkf5AkKM9a84dQHe3mTCLZc5ZAoh11sd5nY"      # embeds tag 42
X_UNTAGGED = "XVPcpSm47b1CZkf5AkKM9a84dQHe3m4sBhsrA4XtnBECTAc"
X_TESTNET = "TVK3SYvMLZR6rEtLDZh3saYHaqFSeMf6Hj2w1dpb7SnJgqn"     # tag 42, test network
# A SECOND address, because the SDK refuses a payment whose sender and destination are the same —
# which is a refusal that has nothing to do with the guard being measured.
OTHER = "rLHzPsX6oXkzU2qL12kHCH8G8cnZv1rBJh"


def _sdk_ok():
    if not SDK.is_file():
        return f"the XRP SDK environment is not installed at {SDK}"
    probe = subprocess.run([str(SDK), "-c", "import xrpl"], capture_output=True)
    return "" if probe.returncode == 0 else "the XRP SDK environment has no xrpl"


@unittest.skipIf(_sdk_ok(), _sdk_ok() or "sdk")
class AnXrpPaymentGoesWhereYouTyped(unittest.TestCase):

    def codec(self, data):
        """Exactly how production runs it: the SDK interpreter, `-I`, JSON over a pipe."""
        done = subprocess.run([str(SDK), "-I", str(CODEC)],
                              input=json.dumps(data).encode(),
                              capture_output=True, timeout=120)
        self.assertEqual(done.returncode, 0,
                         f"the codec crashed rather than answering: {done.stderr.decode()[-400:]}")
        return json.loads(done.stdout.decode() or "{}")

    # ---------------------------------------------------------------- where the money is going

    def test_a_plain_address_is_passed_through_with_its_tag(self):
        self.assertEqual(self.codec({"operation": "recipient", "address": CLASSIC, "tag": None}),
                         {"address": CLASSIC, "tag": None})
        self.assertEqual(self.codec({"operation": "recipient", "address": CLASSIC, "tag": 42}),
                         {"address": CLASSIC, "tag": 42})

    def test_an_x_address_carries_its_own_tag(self):
        """The tag is IN the address, and that is the one the receiving exchange credits."""
        self.assertEqual(self.codec({"operation": "recipient", "address": X_TAGGED, "tag": None}),
                         {"address": CLASSIC, "tag": 42})

    def test_a_tag_that_contradicts_the_address_is_refused(self):
        """Not resolved in either direction — that is the whole point. Preferring the typed tag
        credits the wrong account; preferring the embedded one ignores what the person typed. Both
        arrive at the exchange as somebody else's deposit."""
        answer = self.codec({"operation": "recipient", "address": X_TAGGED, "tag": 7})
        self.assertIn("error", answer, f"a contradicting tag was accepted: {answer}")
        self.assertIn("destination tag", answer["error"].lower())

    def test_a_matching_tag_is_not_a_contradiction(self):
        self.assertEqual(self.codec({"operation": "recipient", "address": X_TAGGED, "tag": 42}),
                         {"address": CLASSIC, "tag": 42})

    def test_an_x_address_with_no_tag_keeps_the_one_you_typed(self):
        self.assertEqual(self.codec({"operation": "recipient", "address": X_UNTAGGED, "tag": 7}),
                         {"address": CLASSIC, "tag": 7})

    def test_a_testnet_address_is_refused(self):
        """Well-formed, and worthless: paying it on mainnet is a transfer to a key nobody controls."""
        answer = self.codec({"operation": "recipient", "address": X_TESTNET, "tag": None})
        self.assertIn("error", answer, "a TESTNET address was accepted as a mainnet recipient")
        self.assertIn("mainnet", answer["error"].lower())

    # ---------------------------------------------------------------- what is refused outright

    def test_nonsense_is_refused(self):
        for address in ("not-an-address", "", CLASSIC[:-1], CLASSIC + "x", "r" * 200):
            answer = self.codec({"operation": "recipient", "address": address, "tag": None})
            self.assertIn("error", answer, f"{address!r} was accepted as an XRP address")

    def test_a_tag_that_is_not_a_tag_is_refused(self):
        """A destination tag is an unsigned 32-bit integer. `True` is an int to Python and is not a
        tag, which is why the check is `type(tag) is not int` and not `isinstance`."""
        for tag in ("42", 4.2, -1, 2 ** 32, True, [], {}):
            answer = self.codec({"operation": "recipient", "address": CLASSIC, "tag": tag})
            self.assertIn("error", answer, f"tag {tag!r} was accepted")

    def test_an_unknown_operation_is_refused(self):
        for op in ("", "Recipient", "sign_all", None):
            answer = self.codec({"operation": op, "address": CLASSIC})
            self.assertIn("error", answer, f"operation {op!r} was accepted")

    # ---------------------------------------------------------------- signing somebody else's money

    def _throwaway_wallet(self):
        """SECP256K1, because that is the only algorithm the codec builds a Wallet with — a default
        `Wallet.create()` is ED25519 and would be refused for the wrong reason. Generated per run
        and never broadcast."""
        gen = subprocess.run(
            [str(SDK), "-c",
             "from xrpl.wallet import Wallet;from xrpl.constants import CryptoAlgorithm;"
             "w=Wallet.create(algorithm=CryptoAlgorithm.SECP256K1);"
             "print(w.public_key);print(w.private_key);print(w.address)"],
            capture_output=True, timeout=120)
        self.assertEqual(gen.returncode, 0, gen.stderr.decode()[-300:])
        public, private, address = gen.stdout.decode().split()
        # The codec prepends the '00' SECP256K1 prefix itself, so hand it the key without one.
        self.assertTrue(private.startswith("00"), "the SDK stopped prefixing secp256k1 keys")
        return public, private[2:], address

    def _payment(self, account, public, destination=OTHER):
        return {"TransactionType": "Payment", "Account": account, "Destination": destination,
                "Amount": "1000000", "Fee": "12", "Sequence": 1,
                "LastLedgerSequence": 100, "SigningPubKey": public}

    def test_signing_is_refused_when_the_payment_is_not_from_this_wallet(self):
        """The guard that stops a payment being signed out of an account the wallet does not own."""
        public, private, address = self._throwaway_wallet()
        answer = self.codec({"operation": "sign", "public": public, "private": private,
                             "payment": self._payment(CLASSIC, public)})
        self.assertIn("error", answer,
                      "a payment was signed out of an account this wallet does not own")
        # THE MESSAGE, not merely "an error". The codec collapses anything it did not expect to
        # "XRP signing could not be completed", so a malformed payment refuses too — and a test
        # that accepted any refusal would pass while the guard itself was gone. Measured: the first
        # version of this test asserted only that an error came back, and it was passing because
        # the SDK rejected a payment whose sender and destination were the same address.
        self.assertIn("does not match", answer["error"].lower(),
                      f"refused, but not by the ownership guard: {answer['error']!r}")

    def test_signing_the_wallet_own_payment_produces_a_blob(self):
        """The other half: with the guard satisfied the codec must actually sign, or the test above
        would pass just as well against a `sign` that refuses everything."""
        public, private, address = self._throwaway_wallet()
        answer = self.codec({"operation": "sign", "public": public, "private": private,
                             "payment": self._payment(address, public)})
        self.assertNotIn("error", answer, f"a wallet could not sign its own payment: {answer}")
        self.assertEqual(answer["address"], address)
        self.assertTrue(answer["blob"], "signed with an empty blob")
        self.assertEqual(len(answer["hash"]), 64, f"not a transaction hash: {answer['hash']!r}")


if __name__ == "__main__":
    unittest.main()
