"""Bitcoin Cash addresses: validated, and never written to a profile the user didn't put them in.

Run: venv-unified/bin/python -m pytest tests/test_bch_address.py

Two separate defects are pinned here, both reported as "poster.place is adding BCH addresses to
their profile".

FIRST, the write. `bchOf()` scans EVERY string field of a profile for something CashAddr-shaped, so
it finds an address someone merely mentioned in their bio. The Edit Profile form pre-filled its BCH
input from that scan — so opening the editor, changing a display name and saving wrote `bch` and
`bitcoincash_address` into that user's kind-0. Fields they never entered, published to every other
Nostr client. The editor must read `bchDirect()` (the canonical keys only); the scan stays for
READING someone else's profile, where nothing is written back.

SECOND, the validation. The old check was `/^[qp][a-z0-9]{41}$/` — pure shape, no checksum — and
this value is shown to people as "the address to send money to". Any 42-character token starting q
or p passed, which is exactly the sort of string that turns up in a bio, so the scan could present
a garbage address and a tip would go nowhere recoverable. CashAddr's bech32-style checksum settles
it.

The helpers live inside app.js's IIFE, so they are sliced out by name and evaluated — the real
shipped code, not a copy.
"""
import json
import os
import shutil
import subprocess
import textwrap

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, "static", "js", "client", "app.js")

pytestmark = pytest.mark.skipif(shutil.which("node") is None, reason="node not installed")

# Verified against an independent implementation, not copied from memory: the P2SH vector was
# generated by computing the checksum in Python (see the commit that added this file).
VALID = [
    "qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a",
    "bitcoincash:qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a",
    "qr95sy3j9xwd2ap32xkykttr4cvcu7as4y0qverfuy",
    "pqq3728yw0y47sqn6l2na30mcw6zm78dzq5ucqzc37",
]
INVALID = [
    "qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6b",   # one character flipped
    "qzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",   # right shape, junk
    "q" + "a" * 41,                                  # right shape, junk
    "pAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",   # a plausible token in a bio
]


def _run(body):
    harness = textwrap.dedent(f"""
        const fs = require('fs');
        const src = fs.readFileSync({json.dumps(APP)}, 'utf8');
        const grab = (name) => {{
          const i = src.indexOf('function ' + name);
          if (i < 0) throw new Error('missing function ' + name);
          let d = 0;
          for (let k = src.indexOf('{{', i); k < src.length; k++) {{
            if (src[k] === '{{') d++;
            else if (src[k] === '}}') {{ d--; if (!d) return src.slice(i, k + 1); }}
          }}
          throw new Error('unbalanced ' + name);
        }};
        eval([
          "const _CA_CHARSET='qpzry9x8gf2tvdw0s3jn54khce6mua7l';",
          "const _BCH_CASHADDR=/(?:bitcoincash:)?[qp][a-z0-9]{{41}}/i;",
          grab('_caPolymod'), grab('isCashAddr'), grab('isBchAddr'),
          grab('bchDirect'), grab('bchOf'),
        ].join('\\n'));
        {body}
    """)
    path = "/tmp/pcai-bch-harness.js"
    with open(path, "w") as f:
        f.write(harness)
    out = subprocess.run(["node", path], capture_output=True, timeout=60)
    assert out.returncode == 0, out.stderr.decode()[:2000]
    return json.loads(out.stdout.decode())


def test_valid_addresses_are_accepted():
    r = _run(f"process.stdout.write(JSON.stringify({json.dumps(VALID)}.map(a => isBchAddr(a))));")
    assert all(r), [a for a, ok in zip(VALID, r) if not ok]


def test_checksum_rejects_wrong_shaped_junk():
    """The whole point: a 42-char token that merely LOOKS like an address is not one, and this
    value is presented to people as where to send money."""
    r = _run(f"process.stdout.write(JSON.stringify({json.dumps(INVALID)}.map(a => isBchAddr(a))));")
    assert not any(r), [a for a, ok in zip(INVALID, r) if ok]


def test_legacy_base58_still_accepted():
    """Legacy addresses keep the shape check — their checksum needs a double SHA-256, and they only
    ever arrive from someone typing one into their own profile field."""
    r = _run("process.stdout.write(JSON.stringify(isBchAddr('1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2')));")
    assert r is True


def test_bch_direct_ignores_an_address_mentioned_in_a_bio():
    """THE profile bug. bchDirect is what the editor pre-fills from, so it must see only fields the
    user deliberately set — otherwise saving an unrelated change writes an address into their kind-0
    that they never entered."""
    r = _run("""
        const bio = { name:'alice', about:'tips: qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a thanks!' };
        const set = { name:'bob', bitcoincash_address:'qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a' };
        process.stdout.write(JSON.stringify({
          bioDirect: bchDirect(bio),   // must be empty — nothing was deliberately set
          bioScan:   bchOf(bio),       // the read-only tip path may still find it
          setDirect: bchDirect(set),
        }));
    """)
    assert r["bioDirect"] == "", "an address from a BIO would be written back into the profile"
    assert r["bioScan"].startswith("qpm2"), "the read-only tip path should still find it"
    assert r["setDirect"].startswith("qpm2")


def test_the_profile_editor_prefills_from_direct_keys_only():
    """Source-level, because the editor markup lives inside the IIFE: the BCH input must not be
    populated from the heuristic scan, or the write bug comes straight back."""
    with open(APP) as f:
        src = f.read()
    i = src.index('id="pf-bch"')
    field = src[i:i + 260]
    assert "bchDirect(p)" in field, "the BCH profile field is not pre-filled from the direct keys"
    assert "bchOf(p)" not in field, "the BCH profile field is pre-filled from the heuristic scan"
