import { clientSource, installStateGlobals } from './client_source.mjs';
const app=clientSource();
installStateGlobals();
const authStart=app.indexOf('  let _aiAuth = null;');
const authEnd=app.indexOf('  // In-app Admin:',authStart);
const aiStart=app.indexOf('  async function renderAI(');
const aiEnd=app.indexOf('  async function requestAiAccess(){',aiStart);
const shipped=app.slice(authStart,authEnd)+app.slice(aiStart,aiEnd);
globalThis.window=globalThis;globalThis.ME=null;globalThis.VIEW='ai';
globalThis.requests=[];globalThis.fetch=async(...a)=>{requests.push(a);throw Error('must not fetch')};
globalThis.sign=async()=>{throw Error('must not sign')};globalThis._sendAdminToken=()=>{};
globalThis.enc=x=>String(x);globalThis.showAuthGate=()=>{};
globalThis.feed={innerHTML:''};globalThis.$=sel=>sel==='#feed'?feed:null;
const run=new Function(`return (async()=>{${shipped}await renderAI();return {html:feed.innerHTML,requests};})()`);
process.stdout.write(JSON.stringify(await run()));
