import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import {createHash,createHmac,hkdfSync,createCipheriv} from 'node:crypto';
globalThis.window=globalThis;
vm.runInThisContext(fs.readFileSync('static/vendor/nostr/nostr.bundle.js','utf8')+'\nglobalThis.NT=NostrTools');
vm.runInThisContext(fs.readFileSync(process.env.PC_CORD_REKEY_SOURCE||'static/js/client/cord-reader.js','utf8').replace('return __toCommonJS(pc_cord_reader_exports);','globalThis.fixture={encodeRekeyBlob,decodeRekeyBlob,epochKeyCommitment,rekeyLocator};return __toCommonJS(pc_cord_reader_exports);')+'\nglobalThis.reader=PosterCordReader;');
const hex=b=>Buffer.from(b).toString('hex'),bytes=h=>Buffer.from(h,'hex'),hash=b=>createHash('sha256').update(b).digest(),cat=(...b)=>Buffer.concat(b.map(x=>Buffer.from(x))),u64=n=>{const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(n));return b;},derive=(secret,label,id,epoch)=>Buffer.from(hkdfSync('sha256',secret,Buffer.alloc(0),cat(Buffer.from(label+'\0'),bytes(id),...(epoch===undefined?[]:[u64(epoch)])),32));
const sk=Buffer.alloc(32,3),memberSk=Buffer.alloc(32,4),otherSk=Buffer.alloc(32,5),owner=NT.getPublicKey(sk),member=NT.getPublicKey(memberSk),other=NT.getPublicKey(otherSk),salt=Buffer.alloc(32,6),cid=hex(hash(cat(Buffer.from('concord/community'),bytes(owner),salt))),zero='0'.repeat(64),channel='ab'.repeat(32);
const bundle={community_id:cid,owner,owner_salt:hex(salt),community_root:'f1'.repeat(32),root_epoch:0,channels:[{id:channel,key:'d1'.repeat(32),epoch:0,name:'private'}],relays:['wss://invalid.example']};
const commitment=(epoch,key)=>hex(hash(cat(Buffer.from('concord/epoch-key-commitment'),u64(epoch),bytes(key))));
const locator=(actor,recipient,scope,epoch)=>hex(derive(cat(bytes(actor),bytes(recipient)),'concord/recipient-pseudonym',scope,epoch));
const group=(scope=zero,epoch=1,root=bundle.community_root)=>{const sk=derive(bytes(root),scope===zero?'concord/base-rekey-pseudonym':'concord/rekey-pseudonym',scope===zero?cid:scope,epoch),pk=NT.getPublicKey(sk);return {sk,pk,key:NT.nip44.getConversationKey(sk,pk)};};
const padded=n=>n<=32?32:(()=>{const p=2**Math.ceil(Math.log2(n)),c=p<=256?32:p/8;return c*Math.ceil(n/c);})();
function keys(key,nonce){let prior=Buffer.alloc(0),out=Buffer.alloc(0);for(let i=1;out.length<76;i++){prior=createHmac('sha256',key).update(cat(prior,nonce,[i])).digest();out=cat(out,prior);}return [out.subarray(0,32),out.subarray(32,44),out.subarray(44,76)];}
function encryptBytes(peer,plain,key=sk){const conv=NT.nip44.getConversationKey(key,peer),nonce=Buffer.alloc(32,23),[ck,cn,mk]=keys(conv,nonce),pad=Buffer.alloc(2+padded(plain.length));pad.writeUInt16BE(plain.length);Buffer.from(plain).copy(pad,2);const cipher=createCipheriv('chacha20',ck,cat(Buffer.alloc(4),cn)),ct=cipher.update(pad),mac=createHmac('sha256',mk).update(cat(nonce,ct)).digest();return cat([2],nonce,ct,mac).toString('base64');}
function decryptBytes(actor,payload,key=memberSk){const b=Buffer.from(payload,'base64'),nonce=b.subarray(1,33),ct=b.subarray(33,-32),[ck,cn,mk]=keys(NT.nip44.getConversationKey(key,actor),nonce);assert.deepEqual(createHmac('sha256',mk).update(cat(nonce,ct)).digest(),b.subarray(-32));const plain=createCipheriv('chacha20',ck,cat(Buffer.alloc(4),cn)).update(ct);return new Uint8Array(plain.subarray(2,2+plain.readUInt16BE(0)));}
const controlRoot='81'.repeat(32),controlPk=NT.getPublicKey(derive(bytes(controlRoot),'concord/control-signer',cid,1));
const blob=(scope=zero,width=104,key='91'.repeat(32),epoch=1)=>cat(bytes(scope),u64(epoch),bytes(key),...(width>=104?[bytes(controlPk)]:[]),...(width===136?[bytes(controlRoot)]:[]));
async function event({scope=zero,rows,plain=blob(scope),recipient=member,actor=sk,i=1,n=1,prev=0,commit,epoch=1,tags=[],sealKind=20013}={}){const pubkey=NT.getPublicKey(actor),g=group(scope,epoch),rumor={kind:3303,pubkey,created_at:1700000000,tags:[['scope',scope],['newepoch',String(epoch)],['prevepoch',String(prev)],['prevcommit',commit||commitment(prev,scope===zero?bundle.community_root:bundle.channels[0].key)],['chunk',String(i),String(n)],...tags],content:JSON.stringify(rows||[{locator:locator(pubkey,recipient,scope,epoch),wrapped:encryptBytes(recipient,plain,actor)}])};rumor.id=NT.getEventHash(rumor);const seal=NT.finalizeEvent({kind:sealKind,created_at:rumor.created_at,tags:[],content:sealKind===20013?NT.nip44.encrypt(JSON.stringify(rumor),g.key):JSON.stringify(rumor)},actor);return NT.finalizeEvent({kind:1059,created_at:1700000000,tags:[['p',other]],content:NT.nip44.encrypt(JSON.stringify(seal),g.key)},g.sk);}
const inspect=async(w,b=bundle,recipient=member,dec=decryptBytes)=>reader.inspectRekeys(b,[],w,recipient,dec);
assert.equal(fixture.epochKeyCommitment(0,bundle.community_root),commitment(0,bundle.community_root));assert.equal(fixture.rekeyLocator(owner,member,zero,1),locator(owner,member,zero,1));
assert(reader.inspectRekeyStreams(bundle).includes(group().pk));assert(reader.inspectRekeyStreams(bundle).includes(group(channel).pk));
for(const [scope,width] of [[channel,72],[zero,72],[zero,104],[zero,136]]){const r=await inspect([await event({scope,plain:blob(scope,width)})]);assert.equal(r.updates.length,1,`independent ${scope===zero?'base':'channel'} ${width}-byte vector`);assert.equal(r.updates[0].control_pk,width>=104?controlPk:undefined);assert.equal(r.updates[0].control_root,width===136?controlRoot:undefined);}
for(const plain of [blob(zero,104).subarray(0,103),blob(zero,104).subarray(0,73),cat(blob(zero,136),[0]),blob(channel,104),blob(channel,72),blob(zero,104,'91'.repeat(32),2)]){const r=await inspect([await event({plain})]);assert.equal(r.updates.length,0,'reject malformed width/scope/epoch');assert.equal(r.removed.length,0);}
const mismatch=blob(zero,136);mismatch[mismatch.length-1]^=1;assert.equal((await inspect([await event({plain:mismatch})])).updates.length,0);
const good=await event();for(const bad of [{...good,sig:'0'.repeat(128)},await event({actor:otherSk}),await event({commit:'a1'.repeat(32)}),await event({tags:[['scope',zero]]}),await event({sealKind:20014})])assert.equal((await inspect([bad])).updates.length,0,'reject signature/authority/continuity/duplicate/plaintext');
assert.equal((await inspect([good],bundle,other,async()=>{throw Error('wrong recipient decrypt called');})).updates.length,0);
const partial=await event({recipient:other,n:2});assert.equal((await inspect([partial])).removed.length,0,'incomplete chunk set never removes');
const complete=await inspect([partial,await event({recipient:other,i:2,n:2})]);assert.equal(complete.removed.length,1,'complete authorized removal');assert.equal((await inspect([partial,await event({recipient:other,i:2,n:2,actor:otherSk})])).removed.length,0,'rotators never merge');
assert.equal((await inspect([good],bundle,member,async()=>new TextDecoder().decode(blob()))).updates.length,0,'lossy string signer must fail closed');
const tampered=encryptBytes(member,blob());const badCipher=Buffer.from(tampered,'base64');badCipher[40]^=1;assert.equal((await inspect([await event({rows:[{locator:locator(owner,member,zero,1),wrapped:badCipher.toString('base64')} ]})])).updates.length,0);
const low=await inspect([await event({plain:blob(zero,136,'11'.repeat(32))})]),high=await inspect([await event({plain:blob(zero,136,'ee'.repeat(32))})]);
let next=reader.applyRekeyUpdates(bundle,high.updates);next=reader.applyRekeyUpdates(next,low.updates);assert.equal(next.community_root,'11'.repeat(32));assert(next.held_roots.some(k=>k.key==='ee'.repeat(32)));assert(next.held_roots.some(k=>k.key===bundle.community_root));next=reader.applyRekeyUpdates(next,high.updates);assert.equal(next.community_root,'11'.repeat(32),'same epoch converges down only');assert(reader.inspectRekeyStreams(next).includes(group().pk),'previous address remains watched');assert.equal(reader.inspectControl(next,[]).controlPubkeys[0],controlPk,'split staff usable');
const made=await reader.createRekeyWraps(bundle,[],{scope:zero,key:'91'.repeat(32),controlRoot,recipients:[{pubkey:owner},{pubkey:member,staff:true},{pubkey:other}]},owner,async e=>NT.finalizeEvent(e,sk),encryptBytes);const reopened=await inspect(made.wraps);assert.equal(reopened.updates[0].control_root,undefined,'caller cannot hand control root to nonstaff');const ownUpdate=await inspect(made.wraps,bundle,owner,(a,c)=>decryptBytes(a,c,sk));assert.equal(ownUpdate.updates[0].control_root,controlRoot);const memberOnly=await inspect(made.wraps,bundle,other,(author,ct)=>decryptBytes(author,ct,otherSk));assert.equal(memberOnly.updates[0].control_root,undefined);assert.equal(memberOnly.updates[0].control_pk,controlPk);assert.throws(()=>fixture.encodeRekeyBlob(zero,1,'91'.repeat(32)),/split/);
console.log('CORD06 independent binary vectors and authenticated rekey lifecycle passed');
// Real local worker: arbitrary invalid-UTF8 bytes survive with its key kept inside.
const workerContext={self:{},TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,DataView,crypto:globalThis.crypto,console,Map,Set,setTimeout,clearTimeout};workerContext.globalThis=workerContext;workerContext.self=workerContext;
vm.createContext(workerContext);workerContext.importScripts=path=>vm.runInContext(fs.readFileSync('.'+path,'utf8'),workerContext);
vm.runInContext(fs.readFileSync('static/js/client/signer-worker.js','utf8'),workerContext);
let reply;workerContext.postMessage=value=>{reply=value;};
const call=async(op,args)=>{reply=null;await workerContext.onmessage({data:{id:1,op,args}});assert(reply);return reply;};
assert((await call('setKey',{sk:hex(memberSk)})).ok);
let opened=await call('cordRekeyDecrypt',{owner:member,peer:owner,ct:encryptBytes(member,blob(zero,136))});assert(opened.ok,opened.error);assert.deepEqual(Buffer.from(opened.data.bytes),blob(zero,136));
const ciphertext=await call('cordRekeyEncrypt',{owner:member,peer:owner,bytes:new Uint8Array(blob(zero,136))});assert(ciphertext.ok,ciphertext.error);assert.deepEqual(Buffer.from(decryptBytes(member,ciphertext.data.ct,sk)),blob(zero,136));
assert(!(await call('cordRekeyDecrypt',{owner:other,peer:owner,ct:encryptBytes(member,blob())})).ok,'worker rejects queued request from retired account');
// Actual adapter subscription+decryption+save path, with only IO replaced.
const source=fs.readFileSync('static/js/client/concord.js','utf8'),section=source.slice(source.indexOf('  const rekeySubscriptions='),source.indexOf('  async function refreshRoomMetadata(p){'));
let activeOwner=member,stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}],callbacks=[],published=[],saveCount=0;
const p={cordRekeyDecrypt:decryptBytes},ctx={window:{PosterCordReader:reader,Relay:{subscribe:(_f,o)=>{callbacks.push(o.onEvent);return 1;},subscribeFrom:(_u,_f,o)=>{callbacks.push(o.onEvent);return ()=>{};},close:()=>{}}},console,Map,Set,Promise,JSON,deliveryOwner:()=>activeOwner,roomIdentity:r=>r.id,saved:()=>structuredClone(stored),save:rooms=>{stored=structuredClone(rooms);saveCount++;},cordControlStamp:controls=>(controls||[]).map(e=>e.id).sort(),queryEnvelopeHistory:async()=>[],roomRelays:()=>[],cordPlaneContext:()=>null,roomControls:new Map(),persistArmadaMembership:async(_p,r)=>{published.push(structuredClone(r));},backgroundRender:()=>{},state:{community:0},stopChatLive:()=>{}};
vm.createContext(ctx);vm.runInContext(section+'\nglobalThis.begin=startRekeyLive;globalThis.stop=stopRekeyLive;',ctx);
ctx.begin(p,stored[0],[]);assert(callbacks.length===2);for(const callback of callbacks)callback(good);await new Promise(r=>setImmediate(r));assert.equal(saveCount,1,'duplicate delivery across transports adopts once');assert.equal(published.length,1);assert.equal(stored[0].cord.bundle.community_root,'91'.repeat(32));ctx.stop();
activeOwner=member;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];callbacks=[];saveCount=0;published=[];let release;const blocked={cordRekeyDecrypt:async(a,c)=>{await new Promise(r=>{release=r;});return decryptBytes(a,c);}};ctx.begin(blocked,stored[0],[]);callbacks[0](good);await new Promise(r=>setImmediate(r));assert(release);activeOwner=other;release();await new Promise(r=>setImmediate(r));assert.equal(saveCount,0,'old account decrypt never writes membership');assert.equal(published.length,0);ctx.stop();
console.log('CORD06 actual worker and account-owned adapter passed');
// Independent owner-signed role/grant vector: a nonowner's citation is a sync
// floor, never permission to survive a later demotion.
const roleId='77'.repeat(32),grantId=hex(derive(bytes(cid),'concord/grant',member)),role={role_id:roleId,name:'Admin',permissions:'16',position:10,scope:{kind:'server'}},grant={member,role_ids:[roleId]};
const editionHash=(id,v,prev,body)=>{const label=Buffer.from('vector-community/v1/edition'),content=Buffer.from(JSON.stringify(body));return hex(hash(cat(u64(label.length),label,bytes(id),u64(v),[prev?1:0],prev?bytes(prev):Buffer.alloc(32),u64(content.length),content)));};
async function controlEdition(vsk,id,body,v=1,prev){const secret=derive(bytes(bundle.community_root),'concord/control',cid,0),pk=NT.getPublicKey(secret),conv=NT.nip44.getConversationKey(secret,pk),rumor={kind:3308,pubkey:owner,created_at:1700000000,tags:[['vsk',vsk],['eid',id],['ev',String(v)],...(prev?[['ep',prev]]:[])],content:JSON.stringify(body)};rumor.id=NT.getEventHash(rumor);const seal=NT.finalizeEvent({kind:20014,created_at:rumor.created_at,tags:[],content:JSON.stringify(rumor)},sk);return NT.finalizeEvent({kind:1059,created_at:1700000000,tags:[['p',other]],content:NT.nip44.encrypt(JSON.stringify(seal),conv)},secret);}
const controls=[await controlEdition('1',roleId,role),await controlEdition('3',grantId,grant)],grantHash=editionHash(grantId,1,null,grant),staffEvent=await event({actor:memberSk,recipient:other,tags:[['vac',grantId,'1',grantHash]]}),staffInspect=(wraps,editions=controls)=>reader.inspectRekeys(bundle,editions,wraps,other,(a,c)=>decryptBytes(a,c,otherSk));
assert.equal((await staffInspect([staffEvent])).updates.length,1,'current staff citation authorizes rotation');assert.equal((await staffInspect([await event({actor:memberSk,recipient:other})])).updates.length,0,'staff must cite grant');
const revoke=await controlEdition('3',grantId,{member,role_ids:[]},2,grantHash);assert.equal((await staffInspect([staffEvent],[...controls,revoke])).updates.length,0,'demotion wins over old valid citation');
const staffMade=await reader.createRekeyWraps(bundle,controls,{scope:zero,recipients:[{pubkey:owner},{pubkey:member},{pubkey:other}]},member,async e=>NT.finalizeEvent(e,memberSk),(peer,b)=>encryptBytes(peer,b,memberSk));assert.equal((await reader.inspectRekeys(bundle,controls,staffMade.wraps,member,decryptBytes)).updates[0].control_root,staffMade.control_root,'writer determines staff from actual roster');
await assert.rejects(()=>reader.createRekeyWraps(bundle,controls,{scope:zero,recipients:[{pubkey:member},{pubkey:other}]},member,async e=>NT.finalizeEvent(e,memberSk),(peer,b)=>encryptBytes(peer,b,memberSk)),/retain the owner/);
console.log('CORD06 staff citation, demotion and write authority passed');
const appSource=fs.readFileSync('static/js/client/app.js','utf8'),bridgeStart=appSource.indexOf('    cordRekeyDecrypt: async'),bridgeEnd=appSource.indexOf('    // NIP-51',bridgeStart),bridge=new Function('initial',`let signer=initial,ME={pubkey:'first'};return {api:{${appSource.slice(bridgeStart,bridgeEnd)}},set:(s,p)=>{signer=s;ME={pubkey:p};}};`)({});
await assert.rejects(()=>bridge.api.cordRekeyDecrypt(owner,'ct'),/does not support binary/);
let resolveBridge;bridge.set({cordRekeyDecrypt:()=>new Promise(r=>{resolveBridge=r;})},'first');const delayed=bridge.api.cordRekeyDecrypt(owner,'ct');bridge.set({},'second');resolveBridge(new Uint8Array(blob()));await assert.rejects(()=>delayed,/account changed/);
console.log('CORD06 signer capability bridge boundaries passed');
const oldMessage=await reader.createChatWrap(bundle,[],channel,'history survives rotation',owner,async e=>NT.finalizeEvent(e,sk));const channelUpdate=(await inspect([await event({scope:channel,plain:blob(channel,72)})])).updates,channelNext=reader.applyRekeyUpdates(bundle,channelUpdate);assert.equal(channelNext.channels[0].held_keys[0].key,bundle.channels[0].key);assert((await reader.inspectChat(channelNext,[],channel,[oldMessage.wrap])).messages.some(m=>m.text==='history survives rotation'));
for(const state of [{removed:true},{dissolved:true},{removed_channels:[channel]}])await assert.rejects(()=>reader.createChatWrap({...bundle,...state},[],channel,'must not send',owner,()=>{throw new Error('signer must not be reached');}),/read-only/);
console.log('CORD06 archived private-channel history and read-only writes passed');
const grave=reader.inspectRekeyStreams(bundle).find(pk=>pk===NT.getPublicKey(derive(bytes(cid),'concord/dissolved',zero))),graveKey=derive(bytes(cid),'concord/dissolved',zero),graveConv=NT.nip44.getConversationKey(graveKey,grave);
async function tombstone({eid=cid,actor=sk,extra=[],sealKind=20014}={}){const pubkey=NT.getPublicKey(actor),rumor={kind:3308,pubkey,created_at:1700000000,content:'',tags:[['vsk','10'],['eid',eid],...extra]};rumor.id=NT.getEventHash(rumor);const seal=NT.finalizeEvent({kind:sealKind,tags:[],created_at:rumor.created_at,content:sealKind===20014?JSON.stringify(rumor):NT.nip44.encrypt(JSON.stringify(rumor),graveConv)},actor);return NT.finalizeEvent({kind:1059,tags:[['p',other]],created_at:rumor.created_at,content:NT.nip44.encrypt(JSON.stringify(seal),graveConv)},graveKey);}
const dissolved=await tombstone();assert.equal(reader.inspectDissolution(bundle,[dissolved]).community_id,cid);
for(const wrong of [await tombstone({eid:zero}),await tombstone({eid:'ac'.repeat(32)}),await tombstone({actor:otherSk}),await tombstone({extra:[['ev','1']]}),await tombstone({extra:[['eid',cid]]}),await tombstone({sealKind:20013})])assert.equal(reader.inspectDissolution(bundle,[wrong]),null,'reject cross-community replay, forged owner and invalid tombstone form');
const refounded={...bundle,community_root:'11'.repeat(32),root_epoch:50};assert.equal(reader.inspectDissolution(refounded,[dissolved]).id,reader.inspectDissolution(bundle,[dissolved]).id,'dissolution address survives every root rotation');assert(reader.inspectDissolution(bundle,[(await reader.createDissolutionWrap(bundle,owner,async e=>NT.finalizeEvent(e,sk))).wrap]));await assert.rejects(()=>reader.createDissolutionWrap(bundle,other,async e=>NT.finalizeEvent(e,otherSk)),/only the owner/);
assert.deepEqual(reader.applyRekeyUpdates({...bundle,dissolved:{id:'sealed'}},low.updates),{...bundle,dissolved:{id:'sealed'}},'no epoch advances after death');
console.log('CORD02 dissolution owner binding and terminal rekey state passed');
activeOwner=member;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];callbacks=[];published=[];saveCount=0;let stops=0;ctx.stopChatLive=()=>{stops++;};ctx.begin(p,stored[0],[]);callbacks[0](dissolved);await new Promise(r=>setImmediate(r));assert(stored[0].cord.bundle.dissolved,'actual subscription persists tombstone');assert.equal(stored[0].cord.bundle.community_root,bundle.community_root);assert.equal(published.length,1);assert.equal(stops,1);const staleCallback=callbacks[0];staleCallback(good);await new Promise(r=>setImmediate(r));assert.equal(saveCount,1,'closed dissolved subscription cannot accept later rekey');ctx.stop();
assert.equal((await inspect([good],bundle,member,async()=>{throw Error('unsupported signer');})).blocked.length,1,'unsupported signer is distinguishable from no rotation');
for(const address of reader.inspectRekeyStreams(bundle)){
 const auth=reader.createPlaneAuth(bundle,[],address,['wss://relay.example']);assert.equal(auth.pubkey,address);
 const signed=auth.sign({kind:22242,created_at:Math.floor(Date.now()/1000),content:'',tags:[['relay','wss://relay.example'],['challenge','challenge']]});assert(NT.verifyEvent(signed));assert.equal(signed.pubkey,address);
 assert.throws(()=>auth.sign({kind:1,content:'not an auth request',created_at:Math.floor(Date.now()/1000),tags:[]}),/invalid/);
}
console.log('CORD06 live rekey/dissolution plane authentication passed');
// Exercise the shipped subscription/auth composition, not a plane=null shortcut.
ctx.stop();activeOwner=member;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];callbacks=[];published=[];saveCount=0;
vm.runInContext(source.slice(source.indexOf('  function cordControlStamp('),source.indexOf('  async function cordQuery(')),ctx);
let authed=0;ctx.window.Relay.subscribeFrom=(_urls,filters,opts)=>{assert(opts.authScope);assert.equal(opts.authScope.pubkey,filters[0].authors[0]);authed++;callbacks.push(opts.onEvent);const close=()=>{};close.ready=Promise.resolve(true);return close;};
ctx.begin({...p,viewer:()=>({pubkey:activeOwner})},stored[0],[]);assert.equal(authed,reader.inspectRekeyStreams(bundle).length);callbacks[0](dissolved);await new Promise(r=>setImmediate(r));assert.equal(published.length,1);assert(stored[0].cord.bundle.dissolved);ctx.stop();
console.log('CORD06 actual plane subscription and dissolution delivery passed');
