import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
globalThis.window=globalThis;
const load=(p,name)=>vm.runInThisContext(fs.readFileSync(new URL(p,import.meta.url),'utf8')+`\nglobalThis.${name}=${name};`);
load('../../static/vendor/nostr/nostr.bundle.js','NostrTools');load('../../static/js/client/cord-protocol.js','PosterCord');
let reader=fs.readFileSync(new URL('../../static/js/client/cord-reader.js',import.meta.url),'utf8');
// Only the test harness exposes fixture minting internals. Production exports no group keys.
reader=reader.replace('return __toCommonJS(pc_cord_reader_exports);','globalThis.fixture={runtime,controlGroups,buildRumor,sealRumor,wrapSeal,grantLocator,hex32,bytesToHex2,editionHash};return __toCommonJS(pc_cord_reader_exports);');
vm.runInThisContext(reader+'\nglobalThis.PosterCordReader=PosterCordReader;');
const sk=new Uint8Array(32).fill(3),owner=NostrTools.getPublicKey(sk),member=NostrTools.getPublicKey(new Uint8Array(32).fill(4)),stranger=NostrTools.getPublicKey(new Uint8Array(32).fill(5)),signEvent=async e=>NostrTools.finalizeEvent(e,sk);
const made=await PosterCord.createCommunity({name:'Roster test',owner,relays:['wss://example.test'],base:'https://example.test',signEvent});
const bundle={community_id:made.communityId,owner,owner_salt:made.secrets.ownerSalt,community_root:made.secrets.root,root_epoch:0,channels:[],relays:['wss://example.test'],name:'Roster test'},community=fixture.runtime(bundle),group=fixture.controlGroups(community)[0],controls=made.events.slice(0,2),rid='a'.repeat(64),eid=fixture.bytesToHex2(fixture.grantLocator(community.id,fixture.hex32(member)));
async function edition(vsk,id,content,key=sk,version=1,prev){const author=NostrTools.getPublicKey(key),tags=[['vsk',vsk],['eid',id],['ev',String(version)]];if(prev)tags.push(['ep',prev]);const rumor=fixture.buildRumor({kind:3308,content:JSON.stringify(content),pubkey:author,ms:1700000000000+version,tags});const seal=await fixture.sealRumor(rumor,20014,group,{signEvent:async e=>NostrTools.finalizeEvent(e,key)});return fixture.wrapSeal(seal,group);}
const role={role_id:rid,name:'Member',permissions:'0',position:50,color:0},grant={member,role_ids:[rid]};
const roleWrap=await edition('1',rid,role),grantWrap=await edition('3',eid,grant);const view=PosterCordReader.inspectControl(bundle,[...controls,roleWrap,grantWrap]);assert.deepEqual(view.members,[member],'valid owner-signed grant exposes a silent member');
const forged=await edition('3',eid,grant,new Uint8Array(32).fill(5));assert.deepEqual(PosterCordReader.inspectControl(bundle,[...controls,roleWrap,forged]).members,[],'stranger cannot grant membership');
const prev=fixture.bytesToHex2(fixture.editionHash(fixture.hex32(eid),1n,undefined,new TextEncoder().encode(JSON.stringify(grant)))),revoke=await edition('3',eid,{member,role_ids:[]},sk,2,prev);assert.deepEqual(PosterCordReader.inspectControl(bundle,[...controls,roleWrap,grantWrap,revoke]).members,[],'authorized emptygrant revokes presence');
console.log('verified silent grant, forged grant rejection and revocation passed');
const code=fs.readFileSync(new URL('../../static/js/client/concord.js',import.meta.url),'utf8'),start=code.indexOf('  var _partsCache='),end=code.indexOf('  function mentionAliases(',start),room={communityId:made.communityId,cord:{bundle}};
const ctx={window:{PosterCordReader},roomControls:new Map([[made.communityId,[...controls,roleWrap,grantWrap]]]),channelsOf:()=>[],channelStoreId:()=>'',testMessages:()=>[]};vm.createContext(ctx);vm.runInContext(code.slice(start,end),ctx);assert(Array.from(ctx.roomParticipants(room,owner)).includes(member),'silent authenticated grantee appears in actual UI candidate projection');ctx.roomControls.set(made.communityId,[...controls,roleWrap,grantWrap,revoke]);assert(!Array.from(ctx.roomParticipants(room,owner)).includes(member),'revoked silent member disappears from UI candidate projection');

const bannedWrap=await PosterCordReader.createBanWrap(bundle,[...controls,roleWrap,grantWrap],member,owner,signEvent);ctx.roomControls.set(made.communityId,[...controls,roleWrap,grantWrap,bannedWrap.wrap]);ctx.channelsOf=()=>[{name:'general'}];ctx.testMessages=()=>[{pubkey:member}];assert(!Array.from(ctx.roomParticipants(room,member)).includes(member),'banned viewer/grantee and old author never reenter mention/call candidates');
