import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {createHash,hkdfSync} from 'node:crypto';
globalThis.window=globalThis;
for(const file of ['static/vendor/nostr/nostr.bundle.js','static/js/client/cord-reader.js','static/js/client/cord-protocol.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'));
const NT=NostrTools,R=PosterCordReader,sk=NT.generateSecretKey(),owner=NT.getPublicKey(sk),sign=e=>NT.finalizeEvent(e,sk),made=await PosterCord.createCommunity({owner,name:'Migration',relays:['wss://old.example'],base:'https://fixture.example',signEvent:sign}),bundle={...PosterCord.openInvite(made.url,made.events).bundle,control_root:made.secrets.controlRoot},id=made.generalChannelId,controls=made.events.filter(e=>e.kind===1059);
const b=h=>Buffer.from(h,'hex'),u64=n=>{const a=Buffer.alloc(8);a.writeBigUInt64BE(BigInt(n));return a;},concat=(...parts)=>Buffer.concat(parts),derive=(secret,label,id,epoch)=>Buffer.from(hkdfSync('sha256',b(secret),Buffer.alloc(0),concat(Buffer.from(label+'\0'),b(id),u64(epoch)),32));
const readSk=derive(bundle.community_root,'concord/control',bundle.community_id,0),readKey=NT.nip44.getConversationKey(readSk,NT.getPublicKey(readSk)),writeSk=derive(bundle.control_root,'concord/control-signer',bundle.community_id,0);
const open=e=>JSON.parse(JSON.parse(NT.nip44.decrypt(e.content,readKey)).content),genesis=controls.map(open),channelGenesis=genesis.find(e=>e.tags.some(t=>t[0]==='vsk'&&t[1]==='2')),metadataGenesis=genesis.find(e=>e.tags.some(t=>t[0]==='vsk'&&t[1]==='0'));
const editionHash=(eid,version,prev,content)=>{const label=Buffer.from('vector-community/v1/edition'),text=Buffer.from(content);return createHash('sha256').update(concat(u64(label.length),label,b(eid),u64(version),Buffer.from([prev?1:0]),prev?b(prev):Buffer.alloc(32),u64(text.length),text)).digest('hex');};
// Independent owner producer: explicit edition hashes and split read/write keys.
function edition(vsk,eid,body,version,previous,actor=sk){const content=JSON.stringify(body),rumor={kind:3308,pubkey:NT.getPublicKey(actor),created_at:Math.floor(Date.now()/1000),tags:[['vsk',vsk],['eid',eid],['ev',String(version)],...(previous?[['ep',previous]]:[])],content};rumor.id=NT.getEventHash(rumor);const seal=NT.finalizeEvent({kind:20014,created_at:rumor.created_at,tags:[],content:JSON.stringify(rumor)},actor);return {hash:editionHash(eid,version,previous,content),event:NT.finalizeEvent({kind:1059,created_at:rumor.created_at,tags:[],content:NT.nip44.encrypt(JSON.stringify(seal),readKey)},writeSk)};}
const metadataHash=editionHash(bundle.community_id,1,null,metadataGenesis.content),channelHash=editionHash(id,1,null,channelGenesis.content),move=edition('0',bundle.community_id,{name:'Moved',relays:['wss://new.example']},2,metadataHash);
assert.deepEqual(R.inspectControl(bundle,[...controls,move.event]).relays,['wss://new.example']);assert(R.inspectControl(bundle,[...controls,move.event]).relaysAuthoritative);
const foreign=edition('0',bundle.community_id,{name:'Stolen',relays:['wss://attacker.example']},3,move.hash,NT.generateSecretKey());assert.deepEqual(R.inspectControl(bundle,[...controls,move.event,foreign.event]).relays,['wss://new.example']);
const source=fs.readFileSync('static/js/client/concord.js','utf8');globalThis.roomControls=new Map();globalThis.normalizeRelay=x=>x;globalThis.CORD_RELAYS=['wss://fallback.example'];vm.runInThisContext(source.slice(source.indexOf('  function roomRelays('),source.indexOf('  function cordControlStamp(')));
assert.deepEqual(roomRelays(bundle),['wss://old.example']);roomControls.set(bundle.community_id,[...controls,move.event]);assert.deepEqual(roomRelays(bundle),['wss://new.example']);
const emptied=edition('0',bundle.community_id,{name:'Offline',relays:[]},3,move.hash);roomControls.set(bundle.community_id,[...controls,move.event,emptied.event]);assert.deepEqual(roomRelays(bundle),[],'authoritative empty set must not fall back to obsolete relay');
console.log('authenticated metadata relay migration passed');
const before=await R.createChatWrap(bundle,controls,id,'public before conversion',owner,sign),privateMeta=edition('2',id,{name:'general',private:true},2,channelHash),privateBundle={...bundle,channels:[{id,key:'44'.repeat(32),epoch:1,name:'general'}]},privateControls=[...controls,privateMeta.event];
const privateMessage=await R.createChatWrap(privateBundle,privateControls,id,'private generation one',owner,sign);
let rows=await R.inspectChat(privateBundle,privateControls,id,[before.wrap,privateMessage.wrap]);assert.deepEqual(new Set(rows.messages.map(m=>m.text)),new Set(['public before conversion','private generation one']));
rows=await R.inspectChat(bundle,privateControls,id,[before.wrap,privateMessage.wrap]);assert.deepEqual(rows.messages.map(m=>m.text),['public before conversion']);await assert.rejects(()=>R.createChatWrap(bundle,privateControls,id,'no private key',owner,sign),/not writable/);
const publicMeta=edition('2',id,{name:'general',private:false},3,privateMeta.hash),publicControls=[...privateControls,publicMeta.event],publicMessage=await R.createChatWrap(bundle,publicControls,id,'public after conversion',owner,sign);
rows=await R.inspectChat(privateBundle,publicControls,id,[before.wrap,privateMessage.wrap,publicMessage.wrap]);assert.equal(rows.messages.length,3);
rows=await R.inspectChat(bundle,publicControls,id,[before.wrap,privateMessage.wrap,publicMessage.wrap]);assert.equal(rows.messages.length,2);assert(!rows.messages.some(m=>m.text==='private generation one'));
const privateAgain=edition('2',id,{name:'general',private:true},4,publicMeta.hash),nextBundle={...bundle,channels:[{id,key:'55'.repeat(32),epoch:2,held_keys:[{epoch:1,key:'44'.repeat(32)}]}]},nextControls=[...publicControls,privateAgain.event],nextMessage=await R.createChatWrap(nextBundle,nextControls,id,'private generation two',owner,sign);
assert.equal((await R.inspectChat(nextBundle,nextControls,id,[before.wrap,privateMessage.wrap,publicMessage.wrap,nextMessage.wrap])).messages.length,4);
const deleted=edition('2',id,{name:'general',private:true,deleted:true},5,privateAgain.hash),resurrected=edition('2',id,{name:'reused',private:false,deleted:false},6,deleted.hash),terminal=[...nextControls,deleted.event,resurrected.event];
assert(!R.inspectControl(nextBundle,terminal).channels.some(c=>c.id===id),'terminal deletion must not fall through to held private key or resurrect via later metadata');
const unrelated=edition('2',id,{name:'unrelated deletion',private:true,deleted:true},4,'ee'.repeat(32));assert(R.inspectControl(privateBundle,[...publicControls,unrelated.event]).channels.some(c=>c.id===id),'unrelated tombstone cannot delete the chosen chain');
console.log('conversion history, granted keys and terminal channel deletion passed');
const onlyPrivateId='66'.repeat(32),onlyPrivate=edition('2',onlyPrivateId,{name:'Private from birth',private:true},1),fakePublic=edition('2',onlyPrivateId,{name:'Wrong public version',private:false},1),onlyBundle={...bundle,channels:[{id:onlyPrivateId,key:'77'.repeat(32),epoch:0}]},publicForgery=await R.createChatWrap(bundle,[...controls,fakePublic.event],onlyPrivateId,'never a public channel',owner,sign);
assert.equal(R.inspectControl(onlyBundle,[...controls,onlyPrivate.event]).channels.find(c=>c.id===onlyPrivateId).streamPubkeys.length,1);
assert.equal((await R.inspectChat(onlyBundle,[...controls,onlyPrivate.event],onlyPrivateId,[publicForgery.wrap])).messages.length,0);
assert(R.inspectControl(bundle,privateControls).channels.find(c=>c.id===id).readOnly);
const copiedTombstone=edition('2',id,{name:'general',private:true,deleted:true},5,privateAgain.hash,NT.generateSecretKey());assert.equal(copiedTombstone.hash,deleted.hash);assert(!R.inspectControl(nextBundle,[...terminal,copiedTombstone.event]).channels.some(c=>c.id===id));
vm.runInThisContext(source.slice(source.indexOf('  function channelsOf('),source.indexOf('  function activeMessages(')));
assert.deepEqual(channelsOf({channels:[]}),[{name:'general',private:false}]);
assert.deepEqual(channelsOf({channels:[],deletedChannels:[id]}),[],'deleted final channel must not become a synthetic general channel');
console.log('private-only streams, history-only membership and deleted UI fallback passed');

// Legacy naddr-indexed rooms use the same authenticated migration proof.
globalThis.saved=()=>[{naddr:'legacy-room',cord:{bundle}}];roomControls.clear();roomControls.set('legacy-room',[...controls,move.event]);assert.deepEqual(roomRelays(bundle),['wss://new.example']);
const compactPrivate=await R.prepareRefounding(privateBundle,privateControls,{historyComplete:true,recipients:[{pubkey:owner}],channelRecipients:{[id]:[{pubkey:owner}]}},owner,sign,async()=> 'independent encrypted fixture');
assert(compactPrivate.next.public_channel_history.includes(id));assert.equal((await R.inspectChat(compactPrivate.next,compactPrivate.phases[1].events,id,[before.wrap,privateMessage.wrap])).messages.length,2,'compaction must preserve authenticated prior-public visibility');
assert(!R.validateInviteBundle({...privateBundle,public_channel_history:[id]},{forJoin:true}).public_channel_history,'external invite cannot supply authenticated history provenance');
const compactPublic=await R.prepareRefounding(privateBundle,publicControls,{historyComplete:true,recipients:[{pubkey:owner}],channelRecipients:{[id]:[{pubkey:owner}]}},owner,sign,async()=> 'independent encrypted fixture');
assert.equal((await R.inspectChat(compactPublic.next,compactPublic.phases[1].events,id,[before.wrap,privateMessage.wrap,publicMessage.wrap])).messages.length,3,'compacted public head retains held private history without prior metadata ancestors');
console.log('legacy relay lookup and compacted conversion provenance passed');
