import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import {createHash,createHmac,hkdfSync,createCipheriv} from 'node:crypto';
import { clientSource, clientSourceAt, installStateGlobals } from './client_source.mjs';
globalThis.window=globalThis;
vm.runInThisContext(fs.readFileSync('static/vendor/nostr/nostr.bundle.js','utf8')+'\nglobalThis.NT=NostrTools');
vm.runInThisContext(fs.readFileSync(process.env.PC_CORD_REKEY_SOURCE||'static/js/client/cord-reader.js','utf8').replace('return __toCommonJS(pc_cord_reader_exports);','globalThis.fixture={encodeRekeyBlob,decodeRekeyBlob,epochKeyCommitment,rekeyLocator};return __toCommonJS(pc_cord_reader_exports);')+'\nglobalThis.reader=PosterCordReader;');
const hex=b=>Buffer.from(b).toString('hex'),bytes=h=>Buffer.from(h,'hex'),hash=b=>createHash('sha256').update(b).digest(),cat=(...b)=>Buffer.concat(b.map(x=>Buffer.from(x))),u64=n=>{const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(n));return b;},derive=(secret,label,id,epoch)=>Buffer.from(hkdfSync('sha256',secret,Buffer.alloc(0),cat(Buffer.from(label+'\0'),bytes(id),...(epoch===undefined?[]:[u64(epoch)])),32));
const sk=Buffer.alloc(32,3),memberSk=Buffer.alloc(32,4),otherSk=Buffer.alloc(32,5),owner=NT.getPublicKey(sk),member=NT.getPublicKey(memberSk),other=NT.getPublicKey(otherSk),salt=Buffer.alloc(32,6),cid=hex(hash(cat(Buffer.from('concord/community'),bytes(owner),salt))),zero='0'.repeat(64),channel='ab'.repeat(32);
const bundle={community_id:cid,owner,owner_salt:hex(salt),community_root:'f1'.repeat(32),root_epoch:0,channels:[{id:channel,key:'d1'.repeat(32),epoch:0,name:'private'}],relays:['wss://invalid.example']};
const commitment=(epoch,key)=>hex(hash(cat(Buffer.from('concord/epoch-key-commitment'),u64(epoch),bytes(key))));
const locator=(actor,recipient,scope,epoch)=>hex(derive(cat(bytes(actor),bytes(recipient)),'concord/recipient-pseudonym',scope,epoch));
const group=(scope=zero,epoch=1,root=bundle.community_root)=>{const sk=derive(bytes(root),scope===zero?'concord/base-rekey-pseudonym':'concord/rekey-pseudonym',scope===zero?cid:scope,epoch),pk=NT.getPublicKey(sk);return {sk,pk,key:NT.nip44.getConversationKey(sk,pk)};};
const padded=n=>n<=32?32:(()=>{const p=2**Math.ceil(Math.log2(n)),c=p<=256?32:p/8;return c*Math.ceil(n/c);})();
function keys(key,nonce){let prior=Buffer.alloc(0),out=Buffer.alloc(0);for(let i=1;out.length<76;i++){prior=createHmac('sha256',key).update(cat(prior,nonce,[i])).digest();out=cat(out,prior);}return [out.subarray(0,32),out.subarray(32,44),out.subarray(44,76)];}
function encryptBytes(peer,plain,key=sk){const conv=NT.nip44.getConversationKey(key,peer),nonce=Buffer.alloc(32,23),[ck,cn,mk]=keys(conv,nonce),pad=Buffer.alloc(2+padded(plain.length));pad.writeUInt16BE(plain.length);Buffer.from(plain).copy(pad,2);const cipher=createCipheriv('chacha20',ck,cat(Buffer.alloc(4),cn)),ct=cipher.update(pad),mac=createHmac('sha256',mk).update(cat(nonce,ct)).digest();return cat([2],nonce,ct,mac).toString('base64');}
function decryptBytes(actor,payload,key=memberSk){const b=Buffer.from(payload,'base64'),nonce=b.subarray(1,33),ct=b.subarray(33,-32),[ck,cn,mk]=keys(NT.nip44.getConversationKey(key,actor),nonce);assert.deepEqual(createHmac('sha256',mk).update(cat(nonce,ct)).digest(),b.subarray(-32));const plain=createCipheriv('chacha20',ck,cat(Buffer.alloc(4),cn)).update(ct);return new Uint8Array(plain.subarray(2,2+plain.readUInt16BE(0)));}
const controlRoot='81'.repeat(32),controlPk=NT.getPublicKey(derive(bytes(controlRoot),'concord/control-signer',cid,1));
const blob=(scope=zero,width=104,key='91'.repeat(32),epoch=1)=>cat(bytes(scope),u64(epoch),bytes(key),...(width>=104?[bytes(controlPk)]:[]),...(width===136?[bytes(controlRoot)]:[]));
async function event({scope=zero,rows,plain=blob(scope),recipient=member,actor=sk,i=1,n=1,prev=0,commit,epoch=1,tags=[],sealKind=20013}={}){const pubkey=NT.getPublicKey(actor),g=group(scope,epoch),rumor={kind:3303,pubkey,created_at:1700000000,tags:[['scope',scope],['newepoch',String(epoch)],['prevepoch',String(prev)],['prevcommit',commit||commitment(prev,scope===zero?bundle.community_root:bundle.channels[0].key)],['chunk',String(i),String(n)],...tags],content:JSON.stringify(rows||[{locator:locator(pubkey,recipient,scope,epoch),wrapped:encryptBytes(recipient,plain,actor)}])};rumor.id=NT.getEventHash(rumor);const seal=NT.finalizeEvent({kind:sealKind,created_at:rumor.created_at,tags:[],content:sealKind===20013?NT.nip44.encrypt(JSON.stringify(rumor),g.key):JSON.stringify(rumor)},actor);return NT.finalizeEvent({kind:1059,created_at:1700000000,tags:[['p',other]],content:NT.nip44.encrypt(JSON.stringify(seal),g.key)},g.sk);}
const inspect=async(w,b=bundle,recipient=member,dec=decryptBytes)=>reader.inspectRekeys(b,[],w,recipient,dec);
assert.equal(fixture.epochKeyCommitment(0,bundle.community_root),commitment(0,bundle.community_root));assert.equal(fixture.rekeyLocator(owner,member,zero,1),locator(owner,member,zero,1));
assert(reader.inspectRekeyStreams(bundle).includes(group().pk));assert(reader.inspectRekeyStreams(bundle).includes(group(channel).pk));
for(const [scope,width] of [[channel,72],[zero,72],[zero,104],[zero,136]]){const r=await inspect([await event({scope,plain:blob(scope,width)})]);assert.equal(r.updates.length,1,`independent ${scope===zero?'base':'channel'} ${width}-byte vector`);assert.equal(r.updates[0].control_pk,width>=104?controlPk:undefined);assert.equal(r.updates[0].control_root,width===136?controlRoot:undefined);}
for(const plain of [blob(zero,104).subarray(0,103),blob(zero,104).subarray(0,73),cat(blob(zero,136),[0]),blob(channel,104),blob(channel,72),blob(zero,104,'91'.repeat(32),2)]){const r=await inspect([await event({plain})]);assert.equal(r.updates.length,0,'reject malformed width/scope/epoch');assert.equal(r.removed.length,0);}
const mismatch=blob(zero,136);mismatch[mismatch.length-1]^=1;assert.equal((await inspect([await event({plain:mismatch})])).updates.length,0);
const good=await event();for(const bad of [{...good,sig:'0'.repeat(128)},await event({actor:otherSk}),await event({commit:'a1'.repeat(32)}),await event({tags:[['scope',zero]]}),await event({sealKind:20014})])assert.equal((await inspect([bad])).updates.length,0,'reject signature/authority/continuity/duplicate/plaintext');
assert.equal((await inspect([good],bundle,other,async()=>{throw Error('wrong recipient decrypt called');})).updates.length,0);
const partial=await event({recipient:other,n:2});assert.equal((await inspect([partial])).removed.length,0,'incomplete chunk set never removes');
const complete=await inspect([partial,await event({recipient:other,i:2,n:2})]);assert.equal(complete.removed.length,1,'complete authorized removal');assert.equal((await inspect([partial,await event({recipient:other,i:2,n:2,actor:otherSk})])).removed.length,0,'rotators never merge');
assert.equal((await inspect([good],bundle,member,async()=>new TextDecoder().decode(blob()))).updates.length,0,'lossy string signer must fail closed');
const tampered=encryptBytes(member,blob());const badCipher=Buffer.from(tampered,'base64');badCipher[40]^=1;assert.equal((await inspect([await event({rows:[{locator:locator(owner,member,zero,1),wrapped:badCipher.toString('base64')} ]})])).updates.length,0);
const low=await inspect([await event({plain:blob(zero,136,'11'.repeat(32))})]),high=await inspect([await event({plain:blob(zero,136,'ee'.repeat(32))})]);
let next=reader.applyRekeyUpdates(bundle,high.updates);next=reader.applyRekeyUpdates(next,low.updates);assert.equal(next.community_root,'11'.repeat(32));assert(next.held_roots.some(k=>k.key==='ee'.repeat(32)));assert(next.held_roots.some(k=>k.key===bundle.community_root));next=reader.applyRekeyUpdates(next,high.updates);assert.equal(next.community_root,'11'.repeat(32),'same epoch converges down only');assert(reader.inspectRekeyStreams(next).includes(group().pk),'previous address remains watched');assert.equal(reader.inspectControl(next,[]).controlPubkeys[0],controlPk,'split staff usable');
const made=await reader.createRekeyWraps(bundle,[],{scope:zero,key:'91'.repeat(32),controlRoot,recipients:[{pubkey:owner},{pubkey:member,staff:true},{pubkey:other}]},owner,async e=>NT.finalizeEvent(e,sk),encryptBytes);const reopened=await inspect(made.wraps);assert.equal(reopened.updates[0].control_root,undefined,'caller cannot hand control root to nonstaff');const ownUpdate=await inspect(made.wraps,bundle,owner,(a,c)=>decryptBytes(a,c,sk));assert.equal(ownUpdate.updates[0].control_root,controlRoot);const memberOnly=await inspect(made.wraps,bundle,other,(author,ct)=>decryptBytes(author,ct,otherSk));assert.equal(memberOnly.updates[0].control_root,undefined);assert.equal(memberOnly.updates[0].control_pk,controlPk);assert.throws(()=>fixture.encodeRekeyBlob(zero,1,'91'.repeat(32)),/split/);
console.log('CORD06 independent binary vectors and authenticated rekey lifecycle passed');
// Real local worker: arbitrary invalid-UTF8 bytes survive with its key kept inside.
const workerContext={self:{},TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,DataView,crypto:globalThis.crypto,console,Map,Set,setTimeout,clearTimeout};workerContext.globalThis=workerContext;workerContext.self=workerContext;
vm.createContext(installStateGlobals(workerContext) && workerContext);workerContext.importScripts=path=>vm.runInContext(fs.readFileSync('.'+path,'utf8'),workerContext);
vm.runInContext(fs.readFileSync('static/js/client/signer-worker.js','utf8'),workerContext);
let reply;workerContext.postMessage=value=>{reply=value;};
const call=async(op,args)=>{reply=null;await workerContext.onmessage({data:{id:1,op,args}});assert(reply);return reply;};
assert((await call('setKey',{sk:hex(memberSk)})).ok);
let opened=await call('cordRekeyDecrypt',{owner:member,peer:owner,ct:encryptBytes(member,blob(zero,136))});assert(opened.ok,opened.error);assert.deepEqual(Buffer.from(opened.data.bytes),blob(zero,136));
const ciphertext=await call('cordRekeyEncrypt',{owner:member,peer:owner,bytes:new Uint8Array(blob(zero,136))});assert(ciphertext.ok,ciphertext.error);assert.deepEqual(Buffer.from(decryptBytes(member,ciphertext.data.ct,sk)),blob(zero,136));
assert(!(await call('cordRekeyDecrypt',{owner:other,peer:owner,ct:encryptBytes(member,blob())})).ok,'worker rejects queued request from retired account');
// Actual adapter subscription+decryption+save path, with only IO replaced.
const source=fs.readFileSync('static/js/client/concord.js','utf8'),section=source.slice(source.indexOf('  const rekeySubscriptions='),source.indexOf('  async function refreshRoomMetadata(p){'));
let activeOwner=member,stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}],callbacks=[],published=[],saveCount=0;
const p={cordRekeyDecrypt:decryptBytes},ctx={window:{PosterCordReader:reader,Relay:{subscribe:(_f,o)=>{callbacks.push(o.onEvent);return 1;},subscribeFrom:(_u,_f,o)=>{callbacks.push(o.onEvent);return ()=>{};},close:()=>{}}},console,Map,Set,Promise,JSON,deliveryOwner:()=>activeOwner,roomIdentity:r=>r.id,saved:()=>structuredClone(stored),save:rooms=>{stored=structuredClone(rooms);saveCount++;},cachedEnvelopes:async()=>[],envelopeCacheKey:(...args)=>JSON.stringify(args),cordControlStamp:controls=>(controls||[]).map(e=>e.id).sort(),queryEnvelopeHistory:async()=>[],roomRelays:()=>[],cordPlaneContext:()=>null,roomControls:new Map(),persistArmadaMembership:async(_p,r)=>{published.push(structuredClone(r));},backgroundRender:()=>{},state:{community:0},stopChatLive:()=>{}};
vm.createContext(installStateGlobals(ctx) && ctx);vm.runInContext(section+'\nglobalThis.begin=startRekeyLive;globalThis.stop=stopRekeyLive;',ctx);
ctx.begin(p,stored[0],[]);assert(callbacks.length===2);for(const callback of callbacks)callback(good);await new Promise(r=>setImmediate(r));assert.equal(saveCount,1,'duplicate delivery across transports adopts once');assert.equal(published.length,1);assert.equal(stored[0].cord.bundle.community_root,'91'.repeat(32));ctx.stop();
activeOwner=member;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];callbacks=[];saveCount=0;published=[];let release;const blocked={cordRekeyDecrypt:async(a,c)=>{await new Promise(r=>{release=r;});return decryptBytes(a,c);}};ctx.begin(blocked,stored[0],[]);callbacks[0](good);await new Promise(r=>setImmediate(r));assert(release);activeOwner=other;release();await new Promise(r=>setImmediate(r));assert.equal(saveCount,0,'old account decrypt never writes membership');assert.equal(published.length,0);ctx.stop();
console.log('CORD06 actual worker and account-owned adapter passed');
// Independent owner-signed role/grant vector: a nonowner's citation is a sync
// floor, never permission to survive a later demotion.
const roleId='77'.repeat(32),grantId=hex(derive(bytes(cid),'concord/grant',member)),role={role_id:roleId,name:'Admin',permissions:'16',position:10,scope:{kind:'server'}},grant={member,role_ids:[roleId]};
const editionHash=(id,v,prev,body)=>{const label=Buffer.from('vector-community/v1/edition'),content=Buffer.from(JSON.stringify(body));return hex(hash(cat(u64(label.length),label,bytes(id),u64(v),[prev?1:0],prev?bytes(prev):Buffer.alloc(32),u64(content.length),content)));};
async function controlEdition(vsk,id,body,v=1,prev,actor=sk,extra=[]){const secret=derive(bytes(bundle.community_root),'concord/control',cid,0),pk=NT.getPublicKey(secret),conv=NT.nip44.getConversationKey(secret,pk),rumor={kind:3308,pubkey:NT.getPublicKey(actor),created_at:1700000000,tags:[['vsk',vsk],['eid',id],['ev',String(v)],...(prev?[['ep',prev]]:[]),...extra],content:JSON.stringify(body)};rumor.id=NT.getEventHash(rumor);const seal=NT.finalizeEvent({kind:20014,created_at:rumor.created_at,tags:[],content:JSON.stringify(rumor)},actor);return NT.finalizeEvent({kind:1059,created_at:1700000000,tags:[['p',other]],content:NT.nip44.encrypt(JSON.stringify(seal),conv)},secret);}
const controls=[await controlEdition('1',roleId,role),await controlEdition('3',grantId,grant)],grantHash=editionHash(grantId,1,null,grant),staffEvent=await event({actor:memberSk,recipient:other,tags:[['vac',grantId,'1',grantHash]]}),staffInspect=(wraps,editions=controls)=>reader.inspectRekeys(bundle,editions,wraps,other,(a,c)=>decryptBytes(a,c,otherSk));
assert.equal((await staffInspect([staffEvent])).updates.length,1,'current staff citation authorizes rotation');assert.equal((await staffInspect([await event({actor:memberSk,recipient:other})])).updates.length,0,'staff must cite grant');
const revoke=await controlEdition('3',grantId,{member,role_ids:[]},2,grantHash);assert.equal((await staffInspect([staffEvent],[...controls,revoke])).updates.length,0,'demotion wins over old valid citation');
const staffMade=await reader.createRekeyWraps(bundle,controls,{scope:zero,recipients:[{pubkey:owner},{pubkey:member},{pubkey:other}]},member,async e=>NT.finalizeEvent(e,memberSk),(peer,b)=>encryptBytes(peer,b,memberSk));assert.equal((await reader.inspectRekeys(bundle,controls,staffMade.wraps,member,decryptBytes)).updates[0].control_root,staffMade.control_root,'writer determines staff from actual roster');
await assert.rejects(()=>reader.createRekeyWraps(bundle,controls,{scope:zero,recipients:[{pubkey:member},{pubkey:other}]},member,async e=>NT.finalizeEvent(e,memberSk),(peer,b)=>encryptBytes(peer,b,memberSk)),/retain the owner/);
console.log('CORD06 staff citation, demotion and write authority passed');
const appSource=clientSourceAt('static/js/client/app.js'),bridgeStart=appSource.indexOf('    cordRekeyDecrypt: async'),bridgeEnd=appSource.indexOf('    // NIP-51',bridgeStart),bridge=new Function('initial',`let signer=initial,ME={pubkey:'first'};return {api:{${appSource.slice(bridgeStart,bridgeEnd)}},set:(s,p)=>{signer=s;ME={pubkey:p};}};`)({});
await assert.rejects(()=>bridge.api.cordRekeyDecrypt(owner,'ct'),/does not support binary/);
let resolveBridge;bridge.set({cordRekeyDecrypt:()=>new Promise(r=>{resolveBridge=r;})},'first');const delayed=bridge.api.cordRekeyDecrypt(owner,'ct');bridge.set({},'second');resolveBridge(new Uint8Array(blob()));await assert.rejects(()=>delayed,/account changed/);
console.log('CORD06 signer capability bridge boundaries passed');
const oldMessage=await reader.createChatWrap(bundle,[],channel,'history survives rotation',owner,async e=>NT.finalizeEvent(e,sk));const channelUpdate=(await inspect([await event({scope:channel,plain:blob(channel,72)})])).updates,channelNext=reader.applyRekeyUpdates(bundle,channelUpdate);assert.equal(channelNext.channels[0].held_keys[0].key,bundle.channels[0].key);assert((await reader.inspectChat(channelNext,[],channel,[oldMessage.wrap])).messages.some(m=>m.text==='history survives rotation'));
for(const state of [{removed:true},{dissolved:true},{removed_channels:[channel]}])await assert.rejects(()=>reader.createChatWrap({...bundle,...state},[],channel,'must not send',owner,()=>{throw new Error('signer must not be reached');}),/read-only/);
console.log('CORD06 archived private-channel history and read-only writes passed');
const grave=reader.inspectRekeyStreams(bundle).find(pk=>pk===NT.getPublicKey(derive(bytes(cid),'concord/dissolved',zero))),graveKey=derive(bytes(cid),'concord/dissolved',zero),graveConv=NT.nip44.getConversationKey(graveKey,grave);
async function tombstone({eid=cid,actor=sk,extra=[],sealKind=20014}={}){const pubkey=NT.getPublicKey(actor),rumor={kind:3308,pubkey,created_at:1700000000,content:'',tags:[['vsk','10'],['eid',eid],...extra]};rumor.id=NT.getEventHash(rumor);const seal=NT.finalizeEvent({kind:sealKind,tags:[],created_at:rumor.created_at,content:sealKind===20014?JSON.stringify(rumor):NT.nip44.encrypt(JSON.stringify(rumor),graveConv)},actor);return NT.finalizeEvent({kind:1059,tags:[['p',other]],created_at:rumor.created_at,content:NT.nip44.encrypt(JSON.stringify(seal),graveConv)},graveKey);}
const dissolved=await tombstone();assert.equal(reader.inspectDissolution(bundle,[dissolved]).community_id,cid);
for(const wrong of [await tombstone({eid:zero}),await tombstone({eid:'ac'.repeat(32)}),await tombstone({actor:otherSk}),await tombstone({extra:[['ev','1']]}),await tombstone({extra:[['eid',cid]]}),await tombstone({sealKind:20013})])assert.equal(reader.inspectDissolution(bundle,[wrong]),null,'reject cross-community replay, forged owner and invalid tombstone form');
const refounded={...bundle,community_root:'11'.repeat(32),root_epoch:50};assert.equal(reader.inspectDissolution(refounded,[dissolved]).id,reader.inspectDissolution(bundle,[dissolved]).id,'dissolution address survives every root rotation');assert(reader.inspectDissolution(bundle,[(await reader.createDissolutionWrap(bundle,owner,async e=>NT.finalizeEvent(e,sk))).wrap]));await assert.rejects(()=>reader.createDissolutionWrap(bundle,other,async e=>NT.finalizeEvent(e,otherSk)),/only the owner/);
assert.deepEqual(reader.applyRekeyUpdates({...bundle,dissolved:{id:'sealed'}},low.updates),{...bundle,dissolved:{id:'sealed'}},'no epoch advances after death');
console.log('CORD02 dissolution owner binding and terminal rekey state passed');
activeOwner=member;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];callbacks=[];published=[];saveCount=0;let stops=0;ctx.stopChatLive=()=>{stops++;};ctx.begin(p,stored[0],[]);callbacks[0](dissolved);await new Promise(r=>setImmediate(r));assert(stored[0].cord.bundle.dissolved,'actual subscription persists tombstone');assert.equal(stored[0].cord.bundle.community_root,bundle.community_root);assert.equal(published.length,1);assert.equal(stops,1);const staleCallback=callbacks[0];staleCallback(good);await new Promise(r=>setImmediate(r));assert.equal(saveCount,1,'closed dissolved subscription cannot accept later rekey');ctx.stop();
assert.equal((await inspect([good],bundle,member,async()=>{throw Error('unsupported signer');})).blocked.length,1,'unsupported signer is distinguishable from no rotation');
for(const address of reader.inspectRekeyStreams(bundle)){
 const auth=reader.createPlaneAuth(bundle,[],address,['wss://relay.example']);assert.equal(auth.pubkey,address);
 const signed=auth.sign({kind:22242,created_at:Math.floor(Date.now()/1000),content:'',tags:[['relay','wss://relay.example'],['challenge','challenge']]});assert(NT.verifyEvent(signed));assert.equal(signed.pubkey,address);
 assert.throws(()=>auth.sign({kind:1,content:'not an auth request',created_at:Math.floor(Date.now()/1000),tags:[]}),/invalid/);
}
console.log('CORD06 live rekey/dissolution plane authentication passed');
// Exercise the shipped subscription/auth composition, not a plane=null shortcut.
ctx.stop();activeOwner=member;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];callbacks=[];published=[];saveCount=0;
vm.runInContext(source.slice(source.indexOf('  function cordControlStamp('),source.indexOf('  async function cordQuery(')),ctx);
let authed=0;ctx.window.Relay.subscribeFrom=(_urls,filters,opts)=>{assert(opts.authScope);assert.equal(opts.authScope.pubkey,filters[0].authors[0]);authed++;callbacks.push(opts.onEvent);const close=()=>{};close.ready=Promise.resolve(true);return close;};
ctx.begin({...p,viewer:()=>({pubkey:activeOwner})},stored[0],[]);assert.equal(authed,reader.inspectRekeyStreams(bundle).length);callbacks[0](dissolved);await new Promise(r=>setImmediate(r));assert.equal(published.length,1);assert(stored[0].cord.bundle.dissolved);ctx.stop();
console.log('CORD06 actual plane subscription and dissolution delivery passed');
const metadata1={name:'Refounding fixture',description:'first'},metadata2={name:'Refounding fixture',description:'updated'},metaHash=editionHash(cid,1,null,metadata1),refoundControls=[await controlEdition('0',cid,metadata1),await controlEdition('0',cid,metadata2,2,metaHash),...controls];
const options={historyComplete:true,recipients:[{pubkey:owner},{pubkey:member}],channelRecipients:{[channel]:[{pubkey:owner},{pubkey:member}]},removed:[other]};
const plan=await reader.prepareRefounding(bundle,refoundControls,options,owner,async e=>NT.finalizeEvent(e,sk),encryptBytes);
assert.equal(plan.phases.map(p=>p.name).join(','),'root,control,channels,guestbook');assert.equal(plan.phases[1].events.length,3,'compaction keeps one head per entity');
const freshJoin={...plan.next,held_roots:[]};assert.equal(reader.inspectControl(freshJoin,plan.phases[1].events).description,'updated','fresh join bootstraps compacted version-two metadata');assert(reader.inspectControl(freshJoin,plan.phases[1].events).members.includes(member),'original signed grant survives compaction');
const oldChannelRekey=plan.phases[2].events[0];assert.equal(oldChannelRekey.pubkey,group(channel).pk,'channel rotation addressed under prior base root');assert.equal((await inspect(plan.phases[0].events)).updates.length,1);assert.equal((await inspect(plan.phases[0].events,bundle,other,(a,c)=>decryptBytes(a,c,otherSk))).removed.length,1,'excluded member gets no new base key');
for(const bad of [{...options,historyComplete:false},{...options,channelRecipients:{}},{...options,recipients:[{pubkey:owner},{pubkey:other}]}])await assert.rejects(()=>reader.prepareRefounding(bundle,refoundControls,bad,owner,async e=>NT.finalizeEvent(e,sk),encryptBytes));
let writes=[],checkpoints=[],fail=true;const resumable=structuredClone(plan),execute=()=>reader.resumeRefounding(resumable,{current:()=>true,persist:async p=>checkpoints.push(structuredClone(p)),publish:async(e,phase)=>{assert(checkpoints.length,'checkpoint precedes first write');writes.push({id:e.id,phase});if(phase==='control'&&fail){fail=false;throw Error('offline');}return {ok:true};}});
await assert.rejects(execute,/offline/);assert.equal(resumable.phase,1);const rootWrites=writes.filter(w=>w.phase==='root').length;await execute();assert.equal(writes.filter(w=>w.phase==='root').length,rootWrites,'resume does not restart already-confirmed root roll');assert.equal(resumable.phase,4);assert.equal(writes.filter(w=>w.phase==='control')[0].id,writes.filter(w=>w.phase==='control')[1].id,'uncertain publication retries exact signed event');
let beforeRoot=[];await assert.rejects(()=>reader.resumeRefounding(structuredClone(plan),{current:()=>true,persist:async()=>{},publish:async(e,phase)=>{beforeRoot.push(phase);return {ok:false};}}),/root publication/);assert.deepEqual(beforeRoot,['root'],'no compacted control before confirmed root publication');
const guestFailure=structuredClone(plan);await reader.resumeRefounding(guestFailure,{current:()=>true,persist:async()=>{},publish:async(_e,phase)=>{if(phase==='guestbook')throw Error('optional snapshot offline');return {ok:true};}});assert.equal(guestFailure.phase,4,'snapshot failure does not roll back a completed refounding');
console.log('CORD06 refounding compaction, publication order and resumable checkpoints passed');
const sealedBundle={...bundle,dissolved:{id:'grave'}},realNow=Date.now;let injection;try{Date.now=()=>oldMessage.ms-1000000;injection=await reader.createChatWrap(bundle,[],channel,'new content after death',member,async e=>NT.finalizeEvent(e,memberSk));}finally{Date.now=realNow;}assert(injection.ms<oldMessage.ms,'new injection is deliberately backdated');
const sealedRows=await reader.inspectChat(sealedBundle,[],channel,[oldMessage.wrap,injection.wrap],[oldMessage.wrap.id]);assert.deepEqual(sealedRows.messages.map(m=>m.text),['history survives rotation'],'sealed admission uses prior authenticated wrap identities, not author timestamps');
const selfDelete=await reader.createChatWrap(sealedBundle,[],channel,'',owner,async e=>NT.finalizeEvent(e,sk),[['e',oldMessage.rumorId]],5);assert.equal((await reader.inspectChat(sealedBundle,[],channel,[oldMessage.wrap,selfDelete.wrap],[oldMessage.wrap.id])).messages.length,0,'self-delete remains effective after dissolution');
const foreignDelete=await reader.createChatWrap(sealedBundle,[],channel,'',member,async e=>NT.finalizeEvent(e,memberSk),[['e',oldMessage.rumorId]],5);assert.equal((await reader.inspectChat(sealedBundle,[],channel,[oldMessage.wrap,foreignDelete.wrap],[oldMessage.wrap.id])).messages.length,1,'post-seal delete cannot remove another author');
console.log('CORD02 sealed history rejects new content and honors only self-deletes');
await assert.rejects(()=>reader.prepareRefounding(bundle,refoundControls.slice(1),options,owner,async e=>NT.finalizeEvent(e,sk),encryptBytes),/history has a gap/);
assert.equal(reader.inspectGuestbook(plan.next,plan.phases[1].events,plan.phases[3].events).snapshotEvents,1);
// Actual coordinator IO seams: a failed compacted-control publication leaves a
// durable resumable plan, and its resumed root events are not regenerated.
vm.runInContext(source.slice(source.indexOf('  async function acquireRefoundingControls('),source.indexOf('  const rekeySubscriptions=')),ctx);
ctx.stop();activeOwner=owner;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];ctx.roomControls.set(cid,refoundControls);ctx.roomRelays=()=>['wss://relay.example'];ctx.normalizeRelay=s=>String(s).replace(/\/$/,'');ctx.cachedEnvelopes=async()=>refoundControls;ctx.cacheEnvelopes=async()=>{};ctx.startRekeyLive=()=>{};
let sent=[],failControl=true;const transport={viewer:()=>({pubkey:owner}),cordRekeyEncrypt:encryptBytes,signTemplate:async e=>NT.finalizeEvent(e,sk),relayQueryFrom:async(relays,filters,opts)=>{opts.report.ok=relays;return refoundControls.filter(e=>filters[0].authors.includes(e.pubkey));},relayPublishRoom:async(_relays,event,auth)=>{assert(auth.current());assert.equal(auth.pubkey,event.pubkey);assert(NT.verifyEvent(event));sent.push(event.id);const plan=stored[0].cord.refounding;if(failControl&&event.pubkey===plan.next.control_pk){failControl=false;throw Error('relay disconnected');}return {ok:true};}};
await assert.rejects(()=>ctx.refoundRoom(transport,stored[0],{...options,banTarget:other}),/relay disconnected/);assert(stored[0].cord.bundle.refounding_pending);assert(stored[0].cord.refounding.phase===1);const rootIds=stored[0].cord.refounding.phases[0].events.map(e=>e.id);await ctx.refoundRoom(transport,stored[0],{});assert(!stored[0].cord.refounding);assert(!stored[0].cord.bundle.refounding_pending);for(const id of rootIds)assert.equal(sent.filter(x=>x===id).length,1);assert.notEqual(stored[0].cord.bundle.community_root,bundle.community_root);assert(stored[0].banned.includes(other),'ban head is compacted into new control plane');
let noPublish=0;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];const partialTransport={...transport,relayQueryFrom:async(_r,_f,opts)=>{opts.report.failed=['wss://relay.example'];return refoundControls;},relayPublishRoom:async()=>{noPublish++;return {ok:true};}};await assert.rejects(()=>ctx.refoundRoom(partialTransport,stored[0],options),/every control relay/);assert.equal(noPublish,0,'partial control acquisition aborts before first publish');
console.log('CORD06 actual adapter acquisition, durable resume and publication passed');
const staffRole=await controlEdition('1',roleId,{...role,permissions:'20'}),staffMetadata=await controlEdition('0',cid,metadata2,2,metaHash,memberSk,[['vac',grantId,'1',grantHash]]),staffHeads=[refoundControls[0],staffRole,controls[1],staffMetadata],staffPlan=await reader.prepareRefounding(bundle,staffHeads,options,owner,async e=>NT.finalizeEvent(e,sk),encryptBytes);
const readSk=derive(bytes(staffPlan.next.community_root),'concord/control',cid,1),readConv=NT.nip44.getConversationKey(readSk,NT.getPublicKey(readSk)),oldReadSk=derive(bytes(bundle.community_root),'concord/control',cid,0),oldReadConv=NT.nip44.getConversationKey(oldReadSk,NT.getPublicKey(oldReadSk)),originalSeal=JSON.parse(NT.nip44.decrypt(staffMetadata.content,oldReadConv)),compactedSeals=staffPlan.phases[1].events.map(e=>JSON.parse(NT.nip44.decrypt(e.content,readConv)));
assert(compactedSeals.some(s=>s.pubkey===member&&s.id===originalSeal.id&&s.sig===originalSeal.sig),'compaction retains another author’s exact signed seal');
console.log('CORD06 compaction preserves original nonowner signatures');
assert.equal(reader.validateInviteBundle({...bundle,root_refounder:other},{forJoin:true}).root_refounder,undefined);assert.equal(reader.validateInviteBundle({...bundle,root_refounder:other}).root_refounder,other);
const offCurve=blob(zero,104);offCurve.fill(255,72);assert.equal((await inspect([await event({plain:offCurve})])).updates.length,0,'invalid control public key is rejected before adoption');
activeOwner=owner;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}},{id:'other-room',sentinel:'unchanged'}];ctx.state.community=0;
await ctx.refoundRoom({...transport,relayPublishRoom:async()=>{ctx.state.community=1;return {ok:true};}},stored[0],options);assert.notEqual(stored[0].cord.bundle.community_root,bundle.community_root);assert.deepEqual(stored[1],{id:'other-room',sentinel:'unchanged'});
activeOwner=owner;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];let releasePublication;
const pendingRefound=ctx.refoundRoom({...transport,viewer:()=>({pubkey:activeOwner}),relayPublishRoom:async()=>{await new Promise(r=>releasePublication=r);return {ok:true};}},stored[0],options);
for(let i=0;i<30&&!releasePublication;i++)await new Promise(r=>setImmediate(r));assert(releasePublication);activeOwner=other;stored=[{id:'room',newAccountSentinel:true}];releasePublication();await assert.rejects(()=>pendingRefound,/account or membership changed/);assert.deepEqual(stored,[{id:'room',newAccountSentinel:true}]);
console.log('CORD06 refounding stays bound to original account and room');
// A terminal link retirement is a durable prerequisite, never an ephemeral callback.
const retirement=NT.finalizeEvent({kind:33301,created_at:Math.floor(Date.now()/1000),tags:[['d',''],['vsk','9']],content:''},otherSk),beforeRelays=['wss://bootstrap.example','wss://relay.example'];
const retirementOptions={...options,beforeEvents:[retirement],beforeRelays};
for(const invalid of [{...retirementOptions,beforeEvents:[{...retirement,content:'tampered'}]},{...retirementOptions,beforeRelays:['https://wrong.example']}])await assert.rejects(()=>reader.prepareRefounding(bundle,refoundControls,invalid,owner,async e=>NT.finalizeEvent(e,sk),encryptBytes),/prerequisite/);
const retirementPlan=await reader.prepareRefounding(bundle,refoundControls,retirementOptions,owner,async e=>NT.finalizeEvent(e,sk),encryptBytes);let checkpoint,attempts=[];
await assert.rejects(()=>reader.resumeRefounding(retirementPlan,{current:()=>true,persist:async value=>{checkpoint=structuredClone(value);},publish:async(e,phase)=>{assert.equal(checkpoint.beforeEvents[0].id,retirement.id);attempts.push([e.id,phase]);return {ok:false};}}),/prerequisite publication/);
assert.deepEqual(attempts,[[retirement.id,'before']]);assert.equal(checkpoint.phase,0);assert.equal(checkpoint.beforeEvent,0);
const restored=JSON.parse(JSON.stringify(checkpoint));attempts=[];
await reader.resumeRefounding(restored,{current:()=>true,persist:async()=>{},publish:async(e,phase)=>{attempts.push([e.id,phase]);return {ok:true};}});assert.deepEqual(attempts[0],[retirement.id,'before']);assert.equal(attempts[1][1],'root');assert.equal(restored.beforeEvent,1);
// Actual adapter persists before publication and routes to each original bootstrap relay.
activeOwner=owner;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];let beforeCalls=[],denySecond=true;
const retirementTransport={...transport,relayPublishRoom:async(urls,e,auth)=>{if(e.kind===33301){assert.equal(stored[0].cord.refounding.beforeEvents[0].id,retirement.id);assert.deepEqual([...stored[0].cord.refounding.beforeRelays],beforeRelays);assert(!auth?.pubkey,'public link tombstone must not use control-plane AUTH');beforeCalls.push([...urls]);return {ok:!(denySecond&&urls[0]===beforeRelays[1])};}assert(!denySecond,'root cannot publish before all retirement relays ACK');return {ok:true};}};
await assert.rejects(()=>ctx.refoundRoom(retirementTransport,stored[0],retirementOptions),/prerequisite publication/);assert.equal(stored[0].cord.refounding.phase,0);assert.equal(stored[0].cord.refounding.beforeEvent,0);
denySecond=false;await ctx.refoundRoom(retirementTransport,stored[0],{});assert.deepEqual(beforeCalls,beforeRelays.concat(beforeRelays).map(url=>[url]));assert(!stored[0].cord.refounding);assert.notEqual(stored[0].cord.bundle.community_root,bundle.community_root);
console.log('CORD06 durable invitation prerequisites survive plain resume and require every bootstrap ACK');
// Integrated CORD05 -> CORD06 path: the actual creator controller supplies the
// tombstone, a failed ACK checkpoints it, and ordinary resume reconciles13303.
vm.runInThisContext(fs.readFileSync('static/js/client/cord-protocol.js','utf8'));
vm.runInThisContext(fs.readFileSync('static/js/client/cord-invite-links.js','utf8'));
const links=globalThis.PCCordInviteLinks,creatorKey=NT.nip44.getConversationKey(sk,owner),creatorContext={pubkey:owner,isCurrent:()=>activeOwner===owner,verify:async es=>es.filter(e=>NT.verifyEvent(structuredClone(e))),encrypt:async(_p,t)=>NT.nip44.encrypt(t,creatorKey),decrypt:async(_p,t)=>NT.nip44.decrypt(t,creatorKey),sign:async e=>NT.finalizeEvent(e,sk)};
activeOwner=owner;
const link=await links.create(bundle,creatorContext,{base:'https://fixture.example'}),registry=await reader.createInviteRegistryWrap(bundle,refoundControls,[links.details(link.entry).pubkey],owner,creatorContext.sign);
let integratedControls=[...refoundControls,registry.wrap],listEnvelope=await creatorContext.sign({kind:13303,created_at:Math.floor(Date.now()/1000),tags:[],content:await creatorContext.encrypt(owner,JSON.stringify({entries:[link.entry],tombstones:[]}))}),latestLink=link.event,denyPrerequisite=true,integratedSent=[];
stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];ctx.roomControls.set(cid,integratedControls);ctx.CORD_RELAYS=[];ctx.cachedEnvelopes=async()=>integratedControls;ctx.roomRelays=()=>['wss://relay.example'];ctx.mergeEnvelopes=(...sets)=>[...new Map(sets.flat().map(e=>[e.id,e])).values()];
vm.runInContext(source.slice(source.indexOf('  async function ownedInviteContext('),source.indexOf('  async function saveCommunitySettings(')),ctx);
ctx.window.PCConcord={refoundingBeforeEvents:true,reviewRefoundingRecipients:async()=>options,refoundRoom:ctx.refoundRoom,refreshOwnedInviteLinks:ctx.refreshOwnedInviteLinks};
ctx.cordQuery=async(_p,relays,filters,opts)=>{opts.report.ok=relays;return integratedControls.filter(e=>filters.some(f=>f.authors.includes(e.pubkey)));};
const integratedTransport={...transport,cordDirectContext:()=>creatorContext,cordInviteLinksModule:async()=>links,relayQueryFrom:async(relays,filters,opts)=>{opts.report.ok=relays;const kind=filters[0].kinds[0];if(kind===13303)return [listEnvelope];if(kind===33301)return [latestLink];return integratedControls.filter(e=>filters[0].authors.includes(e.pubkey));},relayPublishRoom:async(relays,e,auth)=>{
 integratedSent.push([e.kind,e.id]);
 if(e.kind===33301){assert(stored[0].cord.refounding,'checkpoint must exist before retiring link');assert.equal(stored[0].cord.refounding.beforeEvents[0].id,e.id);assert(!auth?.pubkey);if(denyPrerequisite)return {ok:false};latestLink=e;return {ok:true};}
 if(e.kind===13303){listEnvelope=e;return {ok:true};}
 assert(!denyPrerequisite,'no root publication before tombstone ACK');assert(auth.current());integratedControls.push(e);return {ok:true};
}};
await assert.rejects(()=>ctx.changeOwnedInviteLink(integratedTransport,stored[0],link.entry),/prerequisite publication/);
assert.equal(integratedSent.length,1);const checkpointedId=stored[0].cord.refounding.beforeEvents[0].id;assert.equal(stored[0].cord.refounding.phase,0);assert.equal(stored[0].cord.refounding.beforeEvent,0);
// Serialize and reload membership exactly as an application restart would.
stored=JSON.parse(JSON.stringify(stored));denyPrerequisite=false;await ctx.refoundRoom(integratedTransport,stored[0],{});
assert.equal(integratedSent[1][1],checkpointedId);assert(!stored[0].cord.refounding);assert.notEqual(stored[0].cord.bundle.community_root,bundle.community_root);
assert.equal(reader.inspectControl(stored[0].cord.bundle,integratedControls).liveInviteLinks.length,0);
assert(latestLink.tags.some(t=>t[0]==='vsk'&&t[1]==='9'));
const reconciled=JSON.parse(NT.nip44.decrypt(listEnvelope.content,creatorKey));assert(!reconciled.entries.some(e=>e.token===link.entry.token));assert(reconciled.tombstones.some(e=>e.token===link.entry.token));
assert.equal(integratedSent.filter(([kind])=>kind===13303).length,1,'plain resume performs eventual creator-list cleanup');
console.log('CORD05 actual creator retirement to durable CORD06 resume and bookkeeping passed');
// Independent 40-byte staff delivery: same binary framing, distinct application layout.
const staffTarget=other,staffCipher=plain=>encryptBytes(staffTarget,plain),staffWire=cat(u64(staffPlan.next.root_epoch),bytes(staffPlan.next.control_root));
assert.equal(staffWire.length,40);assert.deepEqual(Buffer.from(reader.decryptRekeyBytes(encryptBytes(other,staffWire),NT.nip44.getConversationKey(otherSk,owner))),staffWire);
const promotion=await reader.createRoleGrantWrap(staffPlan.next,staffPlan.phases[1].events,other,[roleId],owner,async e=>NT.finalizeEvent(e,sk),async(peer,plain)=>{assert.equal(peer,other);assert.deepEqual(Buffer.from(plain),staffWire);return encryptBytes(peer,plain);});
const promotedControls=[...staffPlan.phases[1].events,promotion.wrap],ordinary={...staffPlan.next};delete ordinary.control_root;
const promoted=await reader.adoptStaffControlWrap(ordinary,promotedControls,other,(actor,cipher)=>decryptBytes(actor,cipher,otherSk));assert.equal(promoted.control_root,staffPlan.next.control_root);
await assert.rejects(()=>reader.adoptStaffControlWrap(ordinary,promotedControls,other,(actor,cipher)=>decryptBytes(actor,cipher,memberSk)),/MAC|deep-equal/);
await assert.rejects(()=>reader.adoptStaffControlWrap(ordinary,promotedControls,other,async()=>new Uint8Array(cat(u64(ordinary.root_epoch),Buffer.alloc(32,99)))),/held control signer/);
assert.equal(await reader.adoptStaffControlWrap(ordinary,promotedControls,other,async()=>new Uint8Array(cat(u64(0),bytes(staffPlan.next.control_root)))),ordinary,'compacted stale grant must not install a current write key');
assert.equal(await reader.adoptStaffControlWrap(ordinary,staffPlan.phases[1].events,other,async()=>{throw Error('no valid grant must not decrypt');}),ordinary);
await assert.rejects(()=>reader.createRoleGrantWrap(staffPlan.next,staffPlan.phases[1].events,other,[roleId],member,async e=>NT.finalizeEvent(e,memberSk),staffCipher),/authorized staff|outrank/);
await assert.rejects(()=>reader.createRoleGrantWrap(ordinary,staffPlan.phases[1].events,other,[roleId],owner,async e=>NT.finalizeEvent(e,sk)),/binary control key/);
console.log('CORD04 independent40-byte staff delivery, rank and held-signer adoption passed');
const pinChannelHead=await controlEdition('2',channel,{name:'Private pins',private:true}),pinControls=[...refoundControls,pinChannelHead],pinEid=hex(derive(bytes(cid),'concord/pins',channel));
const pinProof=reader.makePinProof(bundle,pinControls,channel,oldMessage.wrap),chatSk=derive(bytes(bundle.channels[0].key),'concord/channel',channel,0),chatConv=NT.nip44.getConversationKey(chatSk,NT.getPublicKey(chatSk)),nonce=Buffer.from(pinProof.seal.content,'base64').subarray(1,33);
assert.equal(pinProof.keys,hex(cat(...keys(chatConv,nonce))),'pin discloses exact independent HKDF expansion, never conversation key');
assert.equal(reader.verifyPinProof(pinProof,channel).content,'history survives rotation');
assert.equal(reader.verifyPinProof(pinProof,'00'.repeat(32)),null,'proof cannot cross channel binding');
assert.equal(reader.verifyPinProof({...pinProof,keys:'00'.repeat(76)},channel),null,'wrong disclosure MAC rejected');
assert.equal(reader.verifyPinProof({...pinProof,seal:{...pinProof.seal,pubkey:other}},channel),null,'forged author rejected');
const initialPins=await controlEdition('11',pinEid,{entries:[pinProof]}),withPins=[...pinControls,initialPins];
assert.equal(reader.inspectPinList(bundle,withPins,channel).entries[0].id,oldMessage.rumorId);
await assert.rejects(()=>reader.createPinListWrap(bundle,pinControls,channel,[],owner,async e=>NT.finalizeEvent(e,sk)),/history is unavailable/);
const replacedPins=await reader.createPinListWrap(bundle,withPins,channel,[pinProof],owner,async e=>NT.finalizeEvent(e,sk)),sealedPins=[...withPins,replacedPins.wrap];
assert.equal(reader.inspectPinList(bundle,sealedPins,channel).entries.length,1);
assert.equal(reader.inspectPinList({...bundle,channels:[]},sealedPins,channel).available,false,'unheld private pin envelope cannot be overwritten');
const tooMany=await controlEdition('11',pinEid,{entries:Array(26).fill(pinProof)});assert.equal(reader.inspectPinList(bundle,[...pinControls,tooMany],channel).entries.length,0,'whole oversized content folds empty');
const mixedPins=await controlEdition('11',pinEid,{entries:[{...pinProof,keys:'00'.repeat(76)},pinProof]});assert.equal(reader.inspectPinList(bundle,[...pinControls,mixedPins],channel).entries.length,1,'bad entry drops without dropping valid siblings');
const pinDeletion=await reader.createChatWrap(bundle,pinControls,channel,'',owner,async e=>NT.finalizeEvent(e,sk),[['e',oldMessage.rumorId]],5);assert.equal(reader.inspectPinList(bundle,withPins,channel,[pinDeletion.wrap]).entries.length,0,'author deletion hides curated entry');
const pinEdit=await reader.createChatWrap(bundle,pinControls,channel,'corrected pin',owner,async e=>NT.finalizeEvent(e,sk),[['e',oldMessage.rumorId]],3302),editProof=reader.makePinProof(bundle,pinControls,channel,pinEdit.wrap),editedPins=await controlEdition('11',pinEid,{entries:[{...pinProof,edit:editProof}]});assert.equal(reader.inspectPinList(bundle,[...pinControls,editedPins],channel).entries[0].content,'corrected pin');
assert.equal(reader.inspectPinList(bundle,withPins,channel,[pinEdit.wrap]).entries[0].content,'corrected pin','held newer edit wins without curator publication');
const pinPlan=await reader.prepareRefounding(bundle,withPins,options,owner,async e=>NT.finalizeEvent(e,sk),encryptBytes);assert.equal(reader.inspectPinList(pinPlan.next,pinPlan.phases[1].events,channel).entries.length,1,'authenticated pin head survives refounding');
console.log('CORD04 Pin List disclosure vectors, sealed epochs, chain-preserving limits, edits and deletion passed');
const workerStaff=await call('cordRekeyDecrypt',{owner:member,peer:owner,ct:encryptBytes(member,staffWire)});assert(workerStaff.ok,workerStaff.error);assert.deepEqual(Buffer.from(workerStaff.data.bytes),staffWire);
activeOwner=other;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(ordinary)}}];published=[];ctx.roomControls.set(cid,promotedControls);
await ctx.adoptStaffGrant({cordRekeyDecrypt:(actor,cipher)=>decryptBytes(actor,cipher,otherSk)},stored[0],promotedControls);assert.equal(stored[0].cord.bundle.control_root,staffPlan.next.control_root);assert.equal(published.length,1,'adopted staff secret persists through membership writer');
activeOwner=other;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(ordinary)}}];published=[];ctx.roomControls.set(cid,promotedControls);let releaseStaff;
const pendingStaff=ctx.adoptStaffGrant({cordRekeyDecrypt:async(actor,cipher)=>{await new Promise(r=>releaseStaff=r);return decryptBytes(actor,cipher,otherSk);}},stored[0],promotedControls);await new Promise(r=>setImmediate(r));assert(releaseStaff);activeOwner=owner;stored=[{id:'new-account',sentinel:'safe'}];releaseStaff();await pendingStaff;assert.deepEqual(stored,[{id:'new-account',sentinel:'safe'}]);assert.equal(published.length,0);
console.log('CORD04 actual worker40-byte framing and account-owned staff adoption passed');
const pinRoleBody={...role,permissions:'2048',scope:{kind:'channel',channel_id:'ee'.repeat(32)}},pinRoleWrong=await controlEdition('1',roleId,pinRoleBody),scopeControls=[refoundControls[0],pinChannelHead,pinRoleWrong,controls[1],initialPins];
await assert.rejects(()=>reader.createPinListWrap(bundle,scopeControls,channel,[],member,async e=>NT.finalizeEvent(e,memberSk)),/pin permission/);
const pinRoleRight=await controlEdition('1',roleId,{...pinRoleBody,scope:{kind:'channel',channel_id:channel}}),authorizedPins=[refoundControls[0],pinChannelHead,pinRoleRight,controls[1],initialPins];assert((await reader.createPinListWrap(bundle,authorizedPins,channel,[pinProof],member,async e=>NT.finalizeEvent(e,memberSk))).wrap,'scoped PIN_MESSAGES with valid grant can publish');
const hugePins=await controlEdition('11',pinEid,{entries:[],padding:'x'.repeat(32768)}),hugeState=reader.inspectPinList(bundle,[...pinControls,hugePins],channel);assert(hugeState.available&&hugeState.invalid);assert.equal(hugeState.version,'1');const healPins=await reader.createPinListWrap(bundle,[...pinControls,hugePins],channel,[],owner,async e=>NT.finalizeEvent(e,sk));assert.equal(reader.inspectPinList(bundle,[...pinControls,hugePins,healPins.wrap],channel).version,'2','oversized content does not erase version chain');
const malformedRumor=JSON.parse(NT.nip44.decrypt(pinProof.seal.content,chatConv));malformedRumor.id='ff'.repeat(32);const customContent=NT.nip44.encrypt(JSON.stringify(malformedRumor),chatConv),customSeal=NT.finalizeEvent({...pinProof.seal,content:customContent},sk),customKeys=hex(cat(...keys(chatConv,Buffer.from(customContent,'base64').subarray(1,33))));assert.equal(reader.verifyPinProof({seal:customSeal,keys:customKeys},channel).id,NT.getEventHash(malformedRumor),'embedded rumor id is never trusted');
console.log('CORD04 Pin List scope authority and chain-preserving byte cap passed');
activeOwner=other;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(ordinary)}}];published=[];ctx.roomControls.set(cid,promotedControls);let releaseDemotion;
const staffRevocation=await reader.createRoleGrantWrap(staffPlan.next,promotedControls,other,[],owner,async e=>NT.finalizeEvent(e,sk));
const decryptingGrant=ctx.adoptStaffGrant({cordRekeyDecrypt:async(actor,cipher)=>{await new Promise(r=>releaseDemotion=r);return decryptBytes(actor,cipher,otherSk);}},stored[0],promotedControls);await new Promise(r=>setImmediate(r));assert(releaseDemotion);ctx.roomControls.set(cid,[...promotedControls,staffRevocation.wrap]);releaseDemotion();await decryptingGrant;assert(!stored[0].cord.bundle.control_root);assert.equal(published.length,0,'grant revocation during decrypt cannot install retired staff authority');
// Actual queued curator path: authenticated self-delete, relay ACK, and head/account races.
ctx.setTimeout=fn=>{queueMicrotask(fn);return 1;};
activeOwner=owner;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];ctx.roomControls.set(cid,withPins);ctx.cachedEnvelopes=async()=>[pinDeletion.wrap];let pinWrites=[],pinAcks=true;
const pinTransport={...transport,relayQueryFrom:async(relays,_filters,opts)=>{opts.report.ok=relays;return ctx.roomControls.get(cid);},relayPublishRoom:async(_relays,e,auth)=>{assert(auth.current());pinWrites.push(e);return {ok:pinAcks};}};
await ctx.reconcilePins(pinTransport,stored[0],channel,[pinDeletion.wrap]);assert.equal(pinWrites.length,1);assert.equal(reader.inspectPinList(bundle,ctx.roomControls.get(cid),channel).entries.length,0);
// A subsequently seated signed head carrying the deleted entry re-arms omission.
ctx.roomControls.set(cid,withPins);await ctx.reconcilePins(pinTransport,stored[0],channel);assert.equal(pinWrites.length,2);
ctx.roomControls.set(cid,withPins);pinAcks=false;await assert.rejects(()=>ctx.reconcilePins(pinTransport,stored[0],channel),/not confirmed/);assert.equal(reader.inspectPinList(bundle,ctx.roomControls.get(cid),channel).entries.length,1,'failed ACK cannot commit a local omission');pinAcks=true;
ctx.roomControls.set(cid,withPins);let releasePin;const beforePin=pinWrites.length;const signingPin=ctx.reconcilePins({...pinTransport,signTemplate:async e=>{await new Promise(r=>releasePin=r);return NT.finalizeEvent(e,sk);}},stored[0],channel);for(let i=0;i<50&&!releasePin;i++)await new Promise(r=>setImmediate(r));assert(releasePin);ctx.roomControls.set(cid,[...withPins,replacedPins.wrap]);releasePin();await signingPin;assert.equal(pinWrites.length,beforePin,'new pin head during signing cancels stale omission');
ctx.roomControls.set(cid,withPins);let releaseOwnerPin;const ownerPin=ctx.reconcilePins({...pinTransport,signTemplate:async e=>{await new Promise(r=>releaseOwnerPin=r);return NT.finalizeEvent(e,sk);}},stored[0],channel);for(let i=0;i<50&&!releaseOwnerPin;i++)await new Promise(r=>setImmediate(r));assert(releaseOwnerPin);activeOwner=other;stored=[{id:'new-account',safe:true}];releaseOwnerPin();await ownerPin;assert.equal(pinWrites.length,beforePin);assert.deepEqual(stored,[{id:'new-account',safe:true}]);
activeOwner=owner;stored=[{id:'room',communityId:cid,cord:{bundle:{...bundle,dissolved:{id:'grave'}}}}];await ctx.reconcilePins(pinTransport,stored[0],channel,[pinDeletion.wrap]);assert.equal(pinWrites.length,beforePin,'dissolution forbids curator republishing');
console.log('CORD04 late staff demotion and queued pin self-erasure ACK/account/head races passed');
const unauthorizedEdit=await reader.createChatWrap(bundle,pinControls,channel,'forged correction',member,async e=>NT.finalizeEvent(e,memberSk),[['e',oldMessage.rumorId]],3302),foreignEditProof=reader.makePinProof(bundle,pinControls,channel,unauthorizedEdit.wrap),invalidEditedPins=await controlEdition('11',pinEid,{entries:[{...pinProof,edit:foreignEditProof}]});assert.equal(reader.inspectPinList(bundle,[...pinControls,invalidEditedPins],channel).entries[0].content,'history survives rotation','another author cannot revise a pinned proof');
console.log('CORD04 foreign pin edit proof is ignored without losing original');
// A re-arm during an in-flight signer must drain into a fresh edition, not vanish.
activeOwner=owner;stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(bundle)}}];ctx.roomControls.set(cid,withPins);let releaseQueuedPin,signPinCount=0;const queueStart=pinWrites.length;
const queueTransport={...pinTransport,signTemplate:async e=>{if(++signPinCount===1)await new Promise(r=>releaseQueuedPin=r);return NT.finalizeEvent(e,sk);}};
const firstQueue=ctx.reconcilePins(queueTransport,stored[0],channel,[pinDeletion.wrap]);for(let i=0;i<50&&!releaseQueuedPin;i++)await new Promise(r=>setImmediate(r));assert(releaseQueuedPin);ctx.roomControls.set(cid,[...withPins,replacedPins.wrap]);const rearmedQueue=ctx.reconcilePins(queueTransport,stored[0],channel,[pinDeletion.wrap]);releaseQueuedPin();await Promise.all([firstQueue,rearmedQueue]);assert.equal(pinWrites.length,queueStart+1,'only freshly re-folded omission publishes');assert.equal(reader.inspectPinList(bundle,ctx.roomControls.get(cid),channel).version,'3');assert.equal(reader.inspectPinList(bundle,ctx.roomControls.get(cid),channel).entries.length,0);
// Fetch completion cannot replace a newer control head delivered during the query.
ctx.roomControls.set(cid,withPins);let deliverNewHead=true;const fetchRace={...pinTransport,relayQueryFrom:async(relays,_filters,opts)=>{opts.report.ok=relays;if(deliverNewHead){deliverNewHead=false;ctx.roomControls.set(cid,[...withPins,replacedPins.wrap]);}return withPins;}};await ctx.reconcilePins(fetchRace,stored[0],channel,[pinDeletion.wrap]);assert.equal(reader.inspectPinList(bundle,ctx.roomControls.get(cid),channel).version,'3','query response merges newer in-memory head before signing');
console.log('CORD04 pin reconciliation drains queued re-arms and merges live heads received during fetch');
const multiTargetEdit=await reader.createChatWrap(bundle,pinControls,channel,'other message revision',owner,async e=>NT.finalizeEvent(e,sk),[['e','ff'.repeat(32)],['e',oldMessage.rumorId]],3302),multiTargetProof=reader.makePinProof(bundle,pinControls,channel,multiTargetEdit.wrap),multiTargetPins=await controlEdition('11',pinEid,{entries:[{...pinProof,edit:multiTargetProof}]});assert.equal(reader.inspectPinList(bundle,[...pinControls,multiTargetPins],channel).entries[0].content,'history survives rotation');assert.equal(reader.inspectPinList(bundle,withPins,channel,[multiTargetEdit.wrap]).entries[0].content,'history survives rotation','pin edit targeting matches keyed timeline first-e semantics');
console.log('CORD04 pin proof and local edits use timeline-compatible first target');
// A recipient records authenticated conversion history before adopting another
// member's3303, so a compacted-only cache after restart retains old public chat.
ctx.stop();activeOwner=member;callbacks=[];ctx.window.PCConcord={};
const conversionPublicBody={name:'converted',private:false},conversionPublic=await controlEdition('2',channel,conversionPublicBody),conversionPrivate=await controlEdition('2',channel,{name:'converted',private:true},2,editionHash(channel,1,null,conversionPublicBody)),conversionControls=[...refoundControls,conversionPublic,conversionPrivate];
const conversionBundle={...bundle,channels:[{...bundle.channels[0],epoch:1}]},oldPublic=await reader.createChatWrap(bundle,[...refoundControls,conversionPublic],channel,'public before recipient conversion',owner,async e=>NT.finalizeEvent(e,sk));
stored=[{id:'room',communityId:cid,cord:{bundle:structuredClone(conversionBundle)}}];ctx.roomControls.set(cid,conversionControls);
ctx.begin({viewer:()=>({pubkey:activeOwner}),cordRekeyDecrypt:decryptBytes},stored[0],conversionControls);assert(callbacks.length);callbacks[0](good);
for(let i=0;i<30&&!stored[0].cord.bundle.public_channel_history;i++)await new Promise(r=>setImmediate(r));ctx.stop();
assert(stored[0].cord.bundle.public_channel_history.includes(channel));assert.equal(stored[0].cord.bundle.community_root,'91'.repeat(32));
const received=JSON.parse(JSON.stringify(stored[0].cord.bundle)),receivedReadSk=derive(bytes(received.community_root),'concord/control',cid,1),receivedReadKey=NT.nip44.getConversationKey(receivedReadSk,NT.getPublicKey(receivedReadSk)),receivedWriteSk=derive(bytes(controlRoot),'concord/control-signer',cid,1);
const preservedSeal=NT.nip44.decrypt(conversionPrivate.content,oldReadConv),compactedPrivate=NT.finalizeEvent({kind:1059,created_at:Math.floor(Date.now()/1000),tags:[],content:NT.nip44.encrypt(preservedSeal,receivedReadKey)},receivedWriteSk);
assert.deepEqual((await reader.inspectChat(received,[compactedPrivate],channel,[oldPublic.wrap])).messages.map(m=>m.text),['public before recipient conversion']);
console.log('recipient rekey preserves authenticated conversion provenance after compacted-only reload');
