import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const code=fs.readFileSync(new URL('../../static/js/client/concord.js',import.meta.url),'utf8'),start=code.indexOf('  var _partsCache='),end=code.indexOf('  function mentionAliases(',start);
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
function fixture(){let owner='a'.repeat(64),rooms=[{communityId:'room',cord:{bundle:{owner:'b'.repeat(64),root_epoch:1}}}],reads=deferred(),writes=0,paints=0,queries=0;const controls=[{id:'control'}];const context={Map,Set,Date,JSON,console,cordControlStamp:w=>[...new Set((w||[]).map(e=>e.id))].sort(),window:{PosterCordReader:{inspectControl:()=>({guestbookPubkeys:['plane'],members:[]}),inspectGuestbook:(_b,_c,w)=>({members:w.map(e=>e.member)})}},deliveryOwner:()=>owner,roomIdentity:r=>r&&r.communityId,saved:()=>JSON.parse(JSON.stringify(rooms)),roomControls:new Map([['room',controls]]),envelopeCacheKey:JSON.stringify,cachedEnvelopes:async()=>[],mergeEnvelopes:(a,b)=>[...a,...b],cordPlaneContext:()=>({bounded:true}),roomRelays:()=>[],queryEnvelopeHistory:async(_p,_r,_a,_c,o)=>{assert.equal(o.plane.bounded,true);queries++;return reads.promise;},cacheEnvelopes:async()=>{writes++;},preserveChatScroll:fn=>fn(),backgroundRender:()=>{paints++;},channelsOf:()=>[],channelStoreId:()=>'',testMessages:()=>[]};vm.createContext(context);vm.runInContext(code.slice(start,end),context);return{context,controls,reads,room:rooms[0],switchOwner:()=>{owner='c'.repeat(64);},removeRoom:()=>{rooms=[];},counts:()=>({writes,paints,queries})};}
for(const mode of ['owner','removed','controls','material','superseded']){const f=fixture(),job=f.context.refreshGuestbookMembers({},f.room,f.controls);await Promise.resolve();await Promise.resolve();if(mode==='owner')f.switchOwner();if(mode==='removed')f.removeRoom();if(mode==='controls')f.context.roomControls.set('room',[{id:'new'}]);if(mode==='material')f.room.cord.bundle.root_epoch=2;if(mode==='superseded')vm.runInContext("roomGuestbooks.set('a'.repeat(64)+'\\nroom',{})",f.context);f.reads.resolve([{id:'private',member:'d'.repeat(64)}]);await job;assert.equal(f.counts().writes,0,mode+' late history cannot persist');assert.equal(f.counts().paints,0,mode+' late history cannot repaint');}
const f=fixture(),job=f.context.refreshGuestbookMembers({},f.room,f.controls);await Promise.resolve();f.reads.resolve([{id:'joined',member:'d'.repeat(64)}]);await job;assert.equal(f.counts().writes,1);assert.equal(f.counts().paints,1);assert.deepEqual(Array.from(f.context.roomParticipants(JSON.parse(JSON.stringify(f.room)),'a'.repeat(64))),['d'.repeat(64)],'fresh saved-room objects use authenticated guestbook projection');await f.context.refreshGuestbookMembers({},JSON.parse(JSON.stringify(f.room)),f.controls);assert.equal(f.counts().queries,1,'identical material does not poll per repaint');
console.log('guestbook account/removal/control races, immutable room reload projection and bounded refresh passed');

const cached=fixture(),held=deferred();cached.context.cachedEnvelopes=()=>held.promise;const cacheJob=cached.context.refreshGuestbookMembers({},cached.room,cached.controls);cached.room.cord.bundle.root_epoch=2;held.resolve([{id:'old',member:'d'.repeat(64)}]);await cacheJob;assert.deepEqual(cached.counts(),{writes:0,paints:0,queries:0},'in-place rekey during encrypted cache read cancels old job');
const offline=fixture(),cachedRead=deferred();offline.context.cachedEnvelopes=()=>cachedRead.promise;const offlineJob=offline.context.refreshGuestbookMembers({},offline.room,offline.controls);const empty=offline.context.roomParticipants(offline.room,'a'.repeat(64));assert.equal(empty.length,0);cachedRead.resolve([{id:'cached',member:'d'.repeat(64)}]);await new Promise(resolve=>setImmediate(resolve));assert.equal(offline.counts().paints,1,'cached roster repaints before held relay response');assert.deepEqual(Array.from(offline.context.roomParticipants(offline.room,'a'.repeat(64))),['d'.repeat(64)],'cached arrival invalidates prematurely computed empty projection');offline.reads.resolve([]);await offlineJob;offline.context.roomParticipants(offline.room,'c'.repeat(64));assert.equal(vm.runInContext('roomGuestbooks.size',offline.context),0,'account switch clears prior decrypted roster state');
