import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
globalThis.window=globalThis;
const noop=()=>{};
globalThis.document={querySelector:()=>({}),createElement:()=>({dataset:{}}),head:{appendChild:noop},documentElement:{appendChild:noop},addEventListener:noop};
globalThis.addEventListener=noop;
globalThis.localStorage={getItem:()=>null,setItem:noop,removeItem:noop};
globalThis.sessionStorage=localStorage;
for(const [path,name] of [['../../static/vendor/nostr/nostr.bundle.js','NostrTools'],['../../static/js/client/cord-protocol.js','PosterCord']])
  vm.runInThisContext(fs.readFileSync(new URL(path,import.meta.url),'utf8')+`\nglobalThis.${name}=${name};`);
vm.runInThisContext(fs.readFileSync(new URL('../../static/js/client/concord.js',import.meta.url),'utf8'));
const signer='a'.repeat(64),token=Buffer.alloc(16,7);
const address=relays=>NostrTools.nip19.naddrEncode({kind:33301,pubkey:signer,identifier:'',relays});
const fragment=(relay,tok=token)=>{const text=Buffer.from(relay);return Buffer.concat([Buffer.from([4,0,1,255,text.length]),text,tok]).toString('base64url');};
const room=(host,hints,relay,tok)=>({url:`https://${host}/invite/${address(hints)}#${fragment(relay,tok)}`,name:'Same name'});
const first=room('armada.buzz',['wss://first.example'],'wss://first.example');
const repost=room('poster.place',['wss://second.example'],'wss://second.example');
assert.equal(PosterCord.inviteDetails(first.url).linkSigner,signer);
assert.equal(PosterCord.inviteDetails(repost.url).linkSigner,signer);
const sameInvite=PCConcord.uniqueRooms([first,repost,first,repost]);
assert.equal(sameInvite.length,1,'real v4 routing hints produced duplicate room');
assert.equal((sameInvite[0].inviteAliases||[]).length,0,'routing-only variants accumulated redundant aliases');
const distinct=room('poster.place',[],'wss://second.example',Buffer.alloc(16,8));
assert.equal(PCConcord.uniqueRooms([first,repost,distinct]).length,2,'different token was merged at same signer');
const unknown={...first,url:first.url.split('#')[0]+'#'+Buffer.concat([Buffer.from([5,0]),token]).toString('base64url')};
assert.throws(()=>PosterCord.inviteDetails(unknown.url));
assert.equal(PCConcord.sameRoom(first,unknown),false,'unknown format was decoded as v4');
const hydrated={...repost,communityId:'b'.repeat(64),cord:{bundle:{community_id:'b'.repeat(64)},hydrated:true},channels:[{id:'general-channel',name:'general'}]};
const repaired=PCConcord.uniqueRooms([{...first,communityId:address([])},hydrated]);
assert.equal(repaired.length,1);
assert.equal(repaired[0].communityId,hydrated.communityId);
assert.equal(repaired[0].channels[0].id,'general-channel');
assert.equal(PCConcord.uniqueRooms([...repaired,{...distinct,communityId:hydrated.communityId}]).length,1,'rotated token recreated hydrated room');
console.log('Concord real invite identity runtime ok');
