import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
import {makeRealm,loadInto,into} from '../../botframework/cord_realm.mjs';
const root=new URL('../../',import.meta.url),ctx=makeRealm(),copy=into(ctx);
for(const f of ['static/vendor/nostr/nostr.bundle.js','static/js/client/cord-protocol.js','static/js/client/cord-reader.js'])loadInto(ctx,new URL(f,root));
const NT=ctx.NostrTools,R=ctx.PosterCordReader,sk=NT.generateSecretKey(),owner=NT.getPublicKey(sk),sign=async tpl=>NT.finalizeEvent(copy(tpl),sk),opts=copy({owner,name:'Timers',relays:['wss://timer.fixture'],base:'https://timer.fixture'});opts.signEvent=sign;
const made=await ctx.PosterCord.createCommunity(opts),bundle=copy({...ctx.PosterCord.openInvite(made.url,made.events).bundle,control_root:made.secrets.controlRoot}),initial=copy(made.events.filter(e=>e.kind===1059));

const memberSk=NT.generateSecretKey(),member=NT.getPublicKey(memberSk),stranger=NT.getPublicKey(NT.generateSecretKey());
const plan=await R.createPrivateChannelPlan(bundle,initial,copy({name:'Private lounge',recipients:[member]}),owner,sign),controls=copy([...initial,...plan.wraps]);
assert.equal(plan.wraps.length,3);assert(R.inspectControl(plan.bundle,controls).channels.some(c=>c.id===plan.channelId&&c.private));
assert(!R.inspectControl(bundle,controls).channels.some(c=>c.id===plan.channelId),'public member cannot derive the private key');
const invite=R.privateChannelInvite(plan.bundle,controls,plan.channelId,member);assert.equal(invite.channels.length,1);assert(!invite.control_root);assert(!invite.held_roots);
const msg=await R.createChatWrap(plan.bundle,controls,plan.channelId,'Only granted members',owner,sign);
assert.equal((await R.inspectChat(invite,controls,plan.channelId,copy([msg.wrap]))).messages[0].text,'Only granted members');
assert.throws(()=>R.privateChannelInvite(plan.bundle,initial,plan.channelId,member),/unavailable/);
assert.throws(()=>R.privateChannelInvite(plan.bundle,controls,plan.channelId,stranger),/no verified/);
await assert.rejects(R.createPrivateChannelPlan(bundle,initial,copy({name:'intrusion',recipients:[member]}),member,sign),/only the community owner/);
const banned=await R.createBanWrap(plan.bundle,controls,member,owner,sign);
assert.throws(()=>R.privateChannelInvite(plan.bundle,copy([...controls,banned.wrap]),plan.channelId,member),/unavailable/);
const nextPlan=await R.createPrivateChannelPlan(plan.bundle,controls,copy({name:'Second private',recipients:[member]}),owner,sign),nextControls=copy([...controls,...nextPlan.wraps]);
assert(R.privateChannelInvite(nextPlan.bundle,nextControls,plan.channelId,member),'adding a channel role preserves the old role grant');
assert(R.privateChannelInvite(nextPlan.bundle,nextControls,nextPlan.channelId,member));
const dirty=copy({...plan.bundle,held_roots:[{community_root:'aa'.repeat(32)}],future_secret:'secret'});dirty.channels[0].held_keys=[{epoch:0,key:'bb'.repeat(32)}];
const clean=R.privateChannelInvite(dirty,controls,plan.channelId,member);assert(!clean.future_secret);assert(!clean.channels[0].held_keys);
console.log('Private channels: independent key, owner-rooted role/grant proof, member-only access, ban rejection, and invite secret allowlist passed');
const source=fs.readFileSync(new URL('static/js/client/concord.js',root),'utf8');
vm.runInContext(source.slice(source.indexOf('  function cordControlStamp('),source.indexOf('  function cordPlaneSubscribe('))+source.slice(source.indexOf('  async function createPrivateRoomChannel('),source.indexOf('  function canAddChannel(')),ctx);
let room=copy({communityId:made.communityId,url:made.url,cord:{bundle},channels:R.inspectControl(bundle,initial).channels}),rooms=copy([room]),sent=[],published=[],failAt=0;
ctx.roomControls=new Map([[room.communityId,initial]]);ctx.roomIdentity=r=>r?.communityId;ctx.saved=()=>rooms;ctx.save=a=>rooms=a;ctx.roomRelays=b=>b.relays;ctx.persistArmadaMembership=async()=>true;ctx.cacheEnvelopes=async()=>{};ctx.envelopeCacheKey=(a,b)=>a+b;
const api={viewer:()=>({pubkey:owner}),signTemplate:sign,relayPublishRoom:async(_relays,wrap)=>{published.push(wrap);return {ok:published.length!==failAt};},sendCordDirectInvite:async(invite,recipient,guard)=>{assert(guard.isCurrent());assert(published.length>=3,'proof must be accepted before giftwrapping key');sent.push({invite,recipient});}};
const created=await ctx.createPrivateRoomChannel(api,room,'Adapter private',copy([member]));assert.equal(sent.length,1);assert.equal(created.failures,0);assert.equal(sent[0].recipient,member);assert(rooms[0].channels.some(c=>c.id===created.channelId));assert.equal(sent[0].invite.channels.length,1);
room=copy({communityId:made.communityId,url:made.url,cord:{bundle},channels:R.inspectControl(bundle,initial).channels});rooms=copy([room]);ctx.roomControls.set(room.communityId,initial);published=[];sent=[];failAt=2;
await assert.rejects(ctx.createPrivateRoomChannel(api,room,'Rejected grant',copy([member])),/did not accept/);assert.equal(sent.length,0,'failed grant publishes must never release the key');assert.equal(rooms[0].cord.bundle.channels.length,bundle.channels.length+1,'interrupted create retains independent key for recovery');
console.log('Private adapter: key backup precedes controls, accepted role proofs precede delivery, rejected grants release no key');
