import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {hkdfSync} from 'node:crypto';
import {makeRealm,loadInto,into} from '../../botframework/cord_realm.mjs';
const root=new URL('../../',import.meta.url),ctx=makeRealm(),copy=into(ctx);
for(const file of ['static/vendor/nostr/nostr.bundle.js','static/js/client/cord-protocol.js'])loadInto(ctx,new URL(file,root));
// Only this test exposes the bundled lenient cipher, to produce the oversized negative vector.
vm.runInContext(fs.readFileSync(new URL('static/js/client/cord-reader.js',root),'utf8').replace('return __toCommonJS(pc_cord_reader_exports);','globalThis.testLenientEncrypt=encrypt;return __toCommonJS(pc_cord_reader_exports);'),ctx);
const NT=ctx.NostrTools,R=ctx.PosterCordReader,P=ctx.PosterCord,sk=NT.generateSecretKey(),owner=NT.getPublicKey(sk);
const bytes=buffer=>vm.runInContext(`Uint8Array.from(${JSON.stringify([...buffer])})`,ctx);
const derive=(label,key,id,epoch)=>{const tail=Buffer.alloc(8);if(epoch!==undefined)tail.writeBigUInt64BE(BigInt(epoch));return Buffer.from(hkdfSync('sha256',Buffer.from(key,'hex'),Buffer.alloc(0),Buffer.concat([Buffer.from(label),Buffer.from([0]),Buffer.from(id,'hex'),...(epoch===undefined?[]:[tail])]),32));};
const sign=template=>NT.finalizeEvent(copy(template),sk),options=copy({owner,name:'测试社区',description:'€'.repeat(3000),relays:['wss://relay.example'],base:'https://example.test'});options.signEvent=sign;
const made=await P.createCommunity(options),details=P.inviteDetails(made.url),opened=P.openInvite(made.url,copy(made.events)),bundle=opened.bundle;
const expectedSigner=NT.getPublicKey(bytes(derive('concord/control-signer',made.secrets.controlRoot,made.communityId,0)));
assert.equal(bundle.control_pk,expectedSigner);assert(!('control_root'in bundle),'invite must never distribute staff root');
const controls=made.events.filter(e=>e.kind===1059);assert.equal(controls.length,2,'genesis is metadata plus general');assert(controls.every(e=>e.pubkey===expectedSigner&&NT.verifyEvent(copy(e))));
assert.equal(R.inspectControl(bundle,controls).name,options.name);assert.equal(R.inspectControl(bundle,controls).channels[0].name,'general');
const creator=copy({...bundle,control_root:made.secrets.controlRoot});assert(R.createPlaneAuth(creator,controls,expectedSigner,copy(bundle.relays)));assert.equal(R.createPlaneAuth(bundle,controls,expectedSigner,copy(bundle.relays)),null);
// Independently decrypt the public bundle using the frozen token HKDF bytes.
const invite=made.events.find(e=>e.kind===33301),bundleKey=bytes(derive('concord/invite-key',made.secrets.token,'00'.repeat(32)));
assert.equal(JSON.parse(NT.nip44.v2.decrypt(invite.content,bundleKey)).control_pk,expectedSigner);
const linkSecret=bytes(Buffer.from(made.secrets.linkSignerSk,'hex'));
const linkEvent=(content,tags=[['d',''],['vsk','6']],at=invite.created_at+1)=>NT.finalizeEvent(copy({kind:33301,created_at:at,tags,content}),linkSecret);
const revoked=linkEvent('',[['d',''],['vsk','9']]);
assert.throws(()=>P.openInvite(made.url,copy([invite,revoked])),/revoked/,'latest signed tombstone must not roll back');
assert.equal(P.openInvite(made.url,copy([invite,{...revoked,sig:'0'.repeat(128)}])).bundle.name,bundle.name,'unsigned tombstone cannot revoke');
assert.equal(P.openInvite(made.url,copy([invite,linkEvent('wrong coordinate',[['d','not-empty'],['vsk','9']])])).bundle.name,bundle.name);
const expiry=Date.now()-1000,expired=linkEvent(NT.nip44.v2.encrypt(JSON.stringify({...bundle,expires_at:expiry}),bundleKey));
assert.equal(P.openInvite(made.url,copy([expired])).bundle.expires_at,expiry,'expired preview remains available');
assert.throws(()=>P.openInvite(made.url,copy([expired]),{forJoin:true}),/expired/);
assert.throws(()=>R.validateInviteBundle(copy({...bundle,owner:'aa'.repeat(32)})),/commitment/);
assert.throws(()=>R.validateInviteBundle(copy({...bundle,control_root:'bb'.repeat(32)})),/mismatch/);
assert.throws(()=>R.validateInviteBundle(copy({...bundle,channels:Array(257).fill({})})),/too many/);
const legacy={...bundle};delete legacy.control_pk;
assert.equal(R.validateInviteBundle(copy({...legacy,root_epoch:'7'})).root_epoch,7);
assert.equal(R.validateInviteBundle(copy({...legacy,root_epoch:'18446744073709551615'})).root_epoch,'18446744073709551615');
assert.throws(()=>R.validateInviteBundle(copy({...legacy,root_epoch:'18446744073709551616'})),/epoch/);
assert.throws(()=>R.validateInviteBundle(copy({...legacy,root_epoch:9007199254740992})),/epoch/);
const channel={id:'aa'.repeat(32),key:'bb'.repeat(32),epoch:0,name:'private',future:{opaque:'Keep'}};
const bounded=R.validateInviteBundle(copy({...bundle,channels:Array(256).fill(channel),relays:Array.from({length:50},(_,i)=>'wss://relay'+i+'.example'),future:{opaque:'EXACT'}}));
assert.equal(bounded.channels.length,256);assert.equal(bounded.relays.length,5);assert.equal(JSON.stringify(bounded.future),' {"opaque":"EXACT"}'.trim());assert.equal(bounded.channels[0].future.opaque,'Keep');
await assert.rejects(P.createCommunity({...options,name:'€'.repeat(22)}),/UTF-8/);
await assert.rejects(R.createMetadataWrap(creator,controls,copy({name:'€'.repeat(22)}),owner,sign),/UTF-8/);
const edit=await R.createMetadataWrap(creator,controls,copy({name:'€'.repeat(21),description:'€'.repeat(3000)}),owner,sign);
assert.equal(R.inspectControl(bundle,copy([...controls,edit.wrap])).name,'€'.repeat(21));
const oversize=linkEvent(ctx.testLenientEncrypt(JSON.stringify({...bundle,opaque:'x'.repeat(66000)}),bundleKey));
assert.throws(()=>P.openInvite(made.url,copy([oversize])),/65,535-byte cap/,'lenient crypto libraries cannot admit oversized wire plaintext');
console.log('CORD genesis/invites: independent split signer, private staff keys, preview expiry, signed revocation, bounds and UTF-8 passed');
