import assert from 'node:assert/strict';
import vm from 'node:vm';
import {hkdfSync,webcrypto} from 'node:crypto';
import {makeRealm,loadInto,into} from '../../botframework/cord_realm.mjs';
const root=new URL('../../',import.meta.url),ctx=makeRealm(),copy=into(ctx);ctx.crypto.subtle=webcrypto.subtle;
for(const f of ['static/vendor/nostr/nostr.bundle.js','static/js/client/cord-reader.js','static/js/client/cord-protocol.js','static/js/client/cord-invite-links.js'])loadInto(ctx,new URL(f,root));
const NT=ctx.NostrTools,P=ctx.PosterCord,R=ctx.PosterCordReader,A=ctx.PCCordInviteLinks,sk=NT.generateSecretKey(),pk=NT.getPublicKey(sk);
const bytes=b=>vm.runInContext(`Uint8Array.from(${JSON.stringify([...b])})`,ctx);
const sign=t=>NT.finalizeEvent(copy(t),sk),key=NT.nip44.getConversationKey(sk,pk),storage=new Map();ctx.localStorage={getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)};
const made=await P.createCommunity({...copy({owner:pk,name:'Links',relays:['wss://relay.example'],base:'https://example.test'}),signEvent:sign});
const bundle=P.openInvite(made.url,copy(made.events)).bundle,creator=copy({...bundle,control_root:made.secrets.controlRoot});
let current=true,events=[],published=[],complete=true;
const context={pubkey:pk,isCurrent:()=>current,verify:async es=>es.filter(e=>NT.verifyEvent(copy(e))),decrypt:async(_,text)=>NT.nip44.decrypt(text,key),encrypt:async(_,text)=>NT.nip44.encrypt(text,key),sign:async t=>sign(t),query:async()=>({events,complete}),publish:async e=>{published.push(e);}};
const minted=await A.create(creator,context,{base:'https://example.test'}),entry=minted.entry;
assert(NT.verifyEvent(copy(minted.event)));
const derived=bytes(Buffer.from(hkdfSync('sha256',Buffer.from(entry.token,'hex'),Buffer.alloc(0),Buffer.concat([Buffer.from('concord/invite-key'),Buffer.from([0]),Buffer.alloc(32)]),32)));
const plaintext=NT.nip44.decrypt(minted.event.content,derived);assert.equal(JSON.parse(plaintext).community_id,bundle.community_id);assert(!plaintext.includes('control_root'));
assert.equal(P.openInvite(entry.url,copy([minted.event])).bundle.community_id,bundle.community_id);
assert.equal(A.details(entry).pubkey,minted.event.pubkey);
assert.throws(()=>A.details({...entry,token:'00'.repeat(16)}));
await A.remember(entry,context);assert.equal(published.length,1);assert.equal(published[0].kind,13303);assert(!JSON.stringify([...storage]).includes(entry.signer_sk));
assert.equal(JSON.parse(NT.nip44.decrypt(published[0].content,key)).entries[0].url,entry.url);
// A relay that returns stale list data must not erase a locally acknowledged tombstone.
await A.forget(entry,context);await assert.rejects(()=>A.remember(entry,context),/retired/);
const unknown=copy({entries:[entry],tombstones:[],future:{z:2},__proto__:{}});
const merged=A.mergeLists(copy([unknown,{entries:[],tombstones:[{token:entry.token,community_id:entry.community_id}],future:{a:1}}]));
assert.equal(merged.entries.length,0);assert.equal(merged.future.a,1);assert.equal(merged.future.z,2);
const proto=A.mergeLists(vm.runInContext(`JSON.parse('[{"entries":[],"tombstones":[],"__proto__":{"polluted":true},"constructor":{"opaque":1}}]')`,ctx));assert.equal(proto.__proto__.polluted,true);assert.equal({}.polluted,undefined);assert.equal(proto.constructor.opaque,1);
complete=false;const before=published.length;await assert.rejects(()=>A.forget(entry,context),/incomplete/);assert.equal(published.length,before);complete=true;
await assert.rejects(()=>A.remember(entry,{...context,query:async()=>{current=false;return {events:[],complete:true};}}),/account/);current=true;
const refreshed=await A.refreshEvent(entry,copy({...bundle,name:'New name'}),copy([minted.event]),context);assert(refreshed.created_at>minted.event.created_at);assert.equal(P.openInvite(entry.url,copy([refreshed])).bundle.name,'New name');
const retired=A.revokeEvent(entry,copy([refreshed]),context);assert(NT.verifyEvent(copy(retired)));await assert.rejects(()=>A.refreshEvent(entry,bundle,copy([retired]),context),/retired/);
events=[retired];assert((await A.linkState(entry,context)).retired);
const controls=made.events.filter(e=>e.kind===1059),registry=await R.createInviteRegistryWrap(creator,copy(controls),copy([minted.event.pubkey]),pk,sign);
const folded=R.inspectControl(bundle,copy([...controls,registry.wrap]));assert.equal(folded.liveInviteLinks[0],minted.event.pubkey);assert.equal(folded.registriesByCreator[pk][0],minted.event.pubkey);assert(folded.inviteCreators.includes(pk));
const empty=await R.createInviteRegistryWrap(creator,copy([...controls,registry.wrap]),copy([]),pk,sign);assert.equal(R.inspectControl(bundle,copy([...controls,registry.wrap,empty.wrap])).liveInviteLinks.length,0);
await assert.rejects(()=>R.createInviteRegistryWrap(creator,copy(controls),copy([entry.url]),pk,sign),/invalid/);
const other=NT.getPublicKey(NT.generateSecretKey());await assert.rejects(()=>R.createInviteRegistryWrap(creator,copy(controls),copy([]),other,sign),/authorized/);
console.log('creator invite links passed');
// Exercise the shipped adoption hook with real signed lists, registry folds and links.
const fs=await import('node:fs');const source=fs.readFileSync(new URL('static/js/client/concord.js',root),'utf8');
vm.runInContext(source.slice(source.indexOf('  async function ownedInviteContext('),source.indexOf('  async function saveCommunitySettings(')),ctx);
const second=await A.create(creator,context,{base:'https://example.test'}),secondPk=A.details(second.entry).pubkey;
const liveRegistry=await R.createInviteRegistryWrap(creator,copy(controls),copy([secondPk]),pk,sign);
const room=copy({communityId:bundle.community_id,cord:{bundle:{...creator,channels:[{id:'aa'.repeat(32),key:'bb'.repeat(32),epoch:0}]}}});let rooms=[room],wire=[],incomplete=false,revoked=false;
ctx.saved=()=>rooms;ctx.roomIdentity=r=>r.communityId;ctx.roomRelays=b=>b.relays;ctx.CORD_RELAYS=copy([]);ctx.roomControls=new Map([[room.communityId,controls]]);ctx.cordPlaneContext=()=>({current:()=>current});ctx.mergeEnvelopes=(...sets)=>sets.flat();
ctx.cordQuery=async(_p,relays,_filters,options)=>{options.report.ok=relays;return copy([liveRegistry.wrap]);};
const listEvent=sign({kind:13303,created_at:Math.floor(Date.now()/1000)+10,tags:[],content:NT.nip44.encrypt(JSON.stringify({entries:[second.entry],tombstones:[]}),key)});
const host={cordDirectContext:()=>context,cordInviteLinksModule:async()=>A,relayQueryFrom:async(relays,filters,options)=>{options.report.ok=incomplete?[]:relays;return filters[0].kinds[0]===13303?[listEvent]:[revoked?A.revokeEvent(second.entry,copy([second.event]),context):second.event];},relayPublishRoom:async(_relays,e)=>{wire.push(e);return {ok:true};}};
assert.equal(await ctx.refreshOwnedInviteLinks(host,room),1);assert.equal(P.openInvite(second.entry.url,copy(wire)).bundle.channels.length,0,'public link must not acquire privately granted channel keys');
wire=[];revoked=true;assert.equal(await ctx.refreshOwnedInviteLinks(host,room),0);assert.equal(wire.length,0,'lagging creator list cannot revive a signed tombstone');
revoked=false;incomplete=true;await assert.rejects(()=>ctx.refreshOwnedInviteLinks(host,room),/incomplete/);assert.equal(wire.length,0);
incomplete=false;ctx.cordQuery=async(_p,relays,_f,options)=>{options.report.failed=relays;return [];};await assert.rejects(()=>ctx.refreshOwnedInviteLinks(host,room),/registry sync is incomplete/);assert.equal(wire.length,0);
console.log('creator refresh hook passed');
