from typing import List, Dict

def buildWeb(entries: List[Dict], stats: Dict) -> str:
    h = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
    h += '<title>CYBERPUNK FIREWALL TERMINAL</title><style>'
    h += '*{margin:0;padding:0;box-sizing:border-box}'
    h += 'body{background:#0a0a0f;color:#e0e0ff;font-family:"Courier New",monospace;min-height:100vh}'
    h += '.neon{color:#00ffff;text-shadow:0 0 8px #00ffff,0 0 16px #00ffff}'
    h += '.glow{box-shadow:0 0 10px #ff00ff,0 0 20px #ff00ff,inset 0 0 10px rgba(255,0,255,0.1)}'
    h += '.cyberpunk{border:1px solid #00ffff;background:#050510}'
    h += '.glitch{position:relative}'
    h += '@keyframes neon-pulse{0%,100%{text-shadow:0 0 5px #0ff}50%{text-shadow:0 0 20px #0ff,0 0 40px #0ff}}'
    h += '.terminal{font-family:"Courier New",monospace;background:#050510;padding:4px 8px}'
    h += '.scanline{background:repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,255,255,0.02) 2px,rgba(0,255,255,0.02) 4px)}'
    h += '.header{padding:16px;border-bottom:2px solid #00ffff;display:flex;align-items:center;justify-content:space-between}'
    h += '.search-btn{background:transparent;border:1px solid #00ffff;color:#00ffff;padding:6px 14px;cursor:pointer;font-family:monospace}'
    h += '.search-btn:hover{background:rgba(0,255,255,0.1);box-shadow:0 0 8px #0ff}'
    h += '.entry{margin:6px;padding:10px;border-left:3px solid #333}'
    h += '.entry.blocked{border-left-color:#ff00ff}.entry.allowed{border-left-color:#00ff00}'
    h += '.modal{display:none;position:fixed;top:0;left:0;width:100%;height:100%;z-index:1000}'
    h += '.overlay{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.85);cursor:pointer}'
    h += '.modal-box{position:relative;margin:8% auto;width:70%;max-width:640px;background:#0a0a0f;border:2px solid #00ffff;padding:24px;z-index:1001;box-shadow:0 0 30px #00ffff}'
    h += '#modal-input{width:100%;background:transparent;border:none;border-bottom:2px solid #00ffff;color:#00ffff;font-size:18px;padding:10px 4px;outline:none;font-family:"Courier New",monospace}'
    h += '#modal-input::placeholder{color:rgba(0,255,255,0.4)}'
    h += '.close-btn{float:right;background:transparent;border:1px solid #ff00ff;color:#ff00ff;padding:4px 10px;cursor:pointer;font-family:monospace;margin-top:12px}'
    h += '</style></head>'
    h += '<body class="scanline"><div id="modal" class="modal">'
    h += '<div class="overlay" onclick="closeModal()"></div>'
    h += '<div class="modal-box cyberpunk">'
    h += '<div class="neon" style="margin-bottom:12px;font-size:14px">&#9889; SEARCH TERMINAL</div>'
    h += '<input id="modal-input" type="text" placeholder="QUERY..." autofocus oninput="filterEntries(this.value)">'
    h += '<button class="close-btn" onclick="closeModal()">&#x2715; CLOSE</button>'
    h += '</div></div>'
    h += '<div class="header cyberpunk glow">'
    h += '<h1 class="neon glitch" style="animation:neon-pulse 2s infinite">&#9889; CYBERPUNK FIREWALL TERMINAL</h1>'
    h += '<button class="search-btn neon" onclick="showModal()">&#128269; SEARCH</button>'
    h += '</div>'
    total = int((stats or {}).get('total', 0))
    blocked = int((stats or {}).get('blocked', 0))
    h += '<div class="terminal" style="padding:8px 16px;border-bottom:1px solid #00ffff">'
    h += '<span class="neon">TOTAL: ' + str(total) + '</span>'
    h += ' &nbsp; <span style="color:#ff00ff">BLOCKED: ' + str(blocked) + '</span>'
    h += '</div><div id="entries">'
    for e in (entries or []):
        status = str(e.get('status', 'unknown')).lower()
        cmd = str(e.get('command', '')).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        out = str(e.get('output', '') or '').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        h += '<div class="entry cyberpunk ' + status + '" data-cmd="' + cmd.lower() + '">'
        h += '<div><span class="neon">[' + status.upper() + ']</span> '
        h += '<span class="terminal">' + cmd + '</span></div>'
        if out:
            h += '<pre class="terminal" style="margin-top:4px;color:#888">' + out[:300] + '</pre>'
        h += '</div>'
    h += '</div>'
    h += '<script>'
    h += 'function showModal(){'
    h += 'document.getElementById("modal").style.display="block";'
    h += 'setTimeout(function(){document.getElementById("modal-input").focus();},50);}'
    h += 'function closeModal(){'
    h += 'document.getElementById("modal").style.display="none";}'
    h += 'function filterEntries(q){'
    h += 'var rows=document.querySelectorAll("#entries .entry");'
    h += 'rows.forEach(function(r){r.style.display=r.dataset.cmd.includes(q.toLowerCase())?"":"none";});}'
    h += 'document.addEventListener("keydown",function(e){'
    h += 'if(e.key==="Escape")closeModal();'
    h += 'if((e.ctrlKey||e.metaKey)&&e.key==="k"){e.preventDefault();showModal();}});'
    h += '</script></body></html>'
    return h
