RANDOM_SCENE_ELEMENTS = [
    "simple studio backdrop",
    "white background",
    "neutral gray background",
    "soft gradient background",
    "minimalist background",
    "plain colored wall",
    "wooden backdrop",
    "brick wall background",
    "soft bokeh background",
    "blurred outdoor background",
    "natural daylight setting",
    "indoor lighting setup",
    "window light background",
    "clean white studio",
    "textured paper background",
    "fabric backdrop",
    "solid color background",
    "soft pastel background",
    "warm tone background",
    "cool tone background",
    "natural wood background",
    "concrete wall background",
    "soft shadow background",
    "diffused light background",
    "seamless background",
]
