"""GENERATED by scripts/gen_pg_parser_tables.py from postgresql-18.4 src/backend/tsearch/wparser_def.c -- do not edit.

Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group (PostgreSQL License).
"""

PG_VERSION = 'postgresql-18.4'
STATES = ['TPS_Base', 'TPS_InNumWord', 'TPS_InAsciiWord', 'TPS_InWord', 'TPS_InUnsignedInt', 'TPS_InSignedIntFirst', 'TPS_InSignedInt', 'TPS_InSpace', 'TPS_InUDecimalFirst', 'TPS_InUDecimal', 'TPS_InDecimalFirst', 'TPS_InDecimal', 'TPS_InVerVersion', 'TPS_InSVerVersion', 'TPS_InVersionFirst', 'TPS_InVersion', 'TPS_InMantissaFirst', 'TPS_InMantissaSign', 'TPS_InMantissa', 'TPS_InXMLEntityFirst', 'TPS_InXMLEntity', 'TPS_InXMLEntityNumFirst', 'TPS_InXMLEntityNum', 'TPS_InXMLEntityHexNumFirst', 'TPS_InXMLEntityHexNum', 'TPS_InXMLEntityEnd', 'TPS_InTagFirst', 'TPS_InXMLBegin', 'TPS_InTagCloseFirst', 'TPS_InTagName', 'TPS_InTagBeginEnd', 'TPS_InTag', 'TPS_InTagEscapeK', 'TPS_InTagEscapeKK', 'TPS_InTagBackSleshed', 'TPS_InTagEnd', 'TPS_InCommentFirst', 'TPS_InCommentLast', 'TPS_InComment', 'TPS_InCloseCommentFirst', 'TPS_InCloseCommentLast', 'TPS_InCommentEnd', 'TPS_InHostFirstDomain', 'TPS_InHostDomainSecond', 'TPS_InHostDomain', 'TPS_InPortFirst', 'TPS_InPort', 'TPS_InHostFirstAN', 'TPS_InHost', 'TPS_InEmail', 'TPS_InFileFirst', 'TPS_InFileTwiddle', 'TPS_InPathFirst', 'TPS_InPathFirstFirst', 'TPS_InPathSecond', 'TPS_InFile', 'TPS_InFileNext', 'TPS_InURLPathFirst', 'TPS_InURLPathStart', 'TPS_InURLPath', 'TPS_InFURL', 'TPS_InProtocolFirst', 'TPS_InProtocolSecond', 'TPS_InProtocolEnd', 'TPS_InHyphenAsciiWordFirst', 'TPS_InHyphenAsciiWord', 'TPS_InHyphenWordFirst', 'TPS_InHyphenWord', 'TPS_InHyphenNumWordFirst', 'TPS_InHyphenNumWord', 'TPS_InHyphenDigitLookahead', 'TPS_InParseHyphen', 'TPS_InParseHyphenHyphen', 'TPS_InHyphenWordPart', 'TPS_InHyphenAsciiWordPart', 'TPS_InHyphenNumWordPart', 'TPS_InHyphenUnsignedInt', 'TPS_Null']
TOK_ALIAS = ['', 'asciiword', 'word', 'numword', 'email', 'url', 'host', 'sfloat', 'version', 'hword_numpart', 'hword_part', 'hword_asciipart', 'blank', 'tag', 'protocol', 'numhword', 'asciihword', 'hword', 'url_path', 'file', 'float', 'int', 'uint', 'entity']
FLAGS = {'A_NEXT': 0, 'A_BINGO': 1, 'A_POP': 2, 'A_PUSH': 4, 'A_RERUN': 8, 'A_CLEAR': 16, 'A_MERGE': 32, 'A_CLRALL': 64}
STRANGE_LETTER = frozenset([2307, 2366, 2367, 2368, 2377, 2378, 2379, 2380, 2434, 2435, 2494, 2495, 2496, 2503, 2504, 2507, 2508, 2519, 2563, 2622, 2623, 2624, 2691, 2750, 2751, 2752, 2761, 2763, 2764, 2818, 2819, 2878, 2880, 2887, 2888, 2891, 2892, 2903, 3006, 3007, 3009, 3010, 3014, 3015, 3016, 3018, 3019, 3020, 3031, 3073, 3074, 3075, 3137, 3138, 3139, 3140, 3202, 3203, 3262, 3264, 3265, 3266, 3267, 3268, 3271, 3272, 3274, 3275, 3285, 3286, 3330, 3331, 3390, 3391, 3392, 3398, 3399, 3400, 3402, 3403, 3404, 3415, 3458, 3459, 3535, 3536, 3537, 3544, 3545, 3546, 3547, 3548, 3549, 3550, 3551, 3570, 3571, 3902, 3903, 3967, 4139, 4140, 4145, 4152, 4155, 4156, 4182, 4183, 4194, 4195, 4196, 4199, 4200, 4201, 4202, 4203, 4204, 4205, 4227, 4228, 4231, 4232, 4233, 4234, 4235, 4236, 4239, 6070, 6078, 6079, 6080, 6081, 6082, 6083, 6084, 6085, 6087, 6088, 6435, 6436, 6437, 6438, 6441, 6442, 6443, 6448, 6449, 6451, 6452, 6453, 6454, 6455, 6456, 6576, 6577, 6578, 6579, 6580, 6581, 6582, 6583, 6584, 6585, 6586, 6587, 6588, 6589, 6590, 6591, 6592, 6600, 6601, 6681, 6682, 6683, 6916, 6965, 6971, 6973, 6974, 6975, 6976, 6977, 6979, 6980, 7042, 7073, 7078, 7079, 7082, 7204, 7205, 7206, 7207, 7208, 7209, 7210, 7211, 7220, 7221, 43043, 43044, 43047, 43136, 43137, 43188, 43189, 43190, 43191, 43192, 43193, 43194, 43195, 43196, 43197, 43198, 43199, 43200, 43201, 43202, 43203, 43346, 43347, 43567, 43568, 43571, 43572, 43597])
ACTIONS = [
    # TPS_Base
    [('p_isEOF', '', 0, -1, 0, None), ('p_iseqC', '<', 4, 26, 0, None), ('p_isignore', '', 0, 7, 0, None), ('p_isasclet', '', 0, 2, 0, None), ('p_isalpha', '', 0, 3, 0, None), ('p_isdigit', '', 0, 4, 0, None), ('p_iseqC', '-', 4, 5, 0, None), ('p_iseqC', '+', 4, 5, 0, None), ('p_iseqC', '&', 4, 19, 0, None), ('p_iseqC', '~', 4, 51, 0, None), ('p_iseqC', '/', 4, 50, 0, None), ('p_iseqC', '.', 4, 53, 0, None), (None, '', 0, 7, 0, None)],
    # TPS_InNumWord
    [('p_isEOF', '', 1, 0, 3, None), ('p_isalnum', '', 0, 1, 0, None), ('p_isspecial', '', 0, 1, 0, None), ('p_iseqC', '@', 4, 49, 0, None), ('p_iseqC', '/', 4, 50, 0, None), ('p_iseqC', '.', 4, 56, 0, None), ('p_iseqC', '-', 4, 68, 0, None), (None, '', 1, 0, 3, None)],
    # TPS_InAsciiWord
    [('p_isEOF', '', 1, 0, 1, None), ('p_isasclet', '', 0, -1, 0, None), ('p_iseqC', '.', 4, 42, 0, None), ('p_iseqC', '.', 4, 56, 0, None), ('p_iseqC', '-', 4, 47, 0, None), ('p_iseqC', '-', 4, 64, 0, None), ('p_iseqC', '_', 4, 47, 0, None), ('p_iseqC', '@', 4, 49, 0, None), ('p_iseqC', ':', 4, 61, 0, None), ('p_iseqC', '/', 4, 50, 0, None), ('p_isdigit', '', 4, 48, 0, None), ('p_isdigit', '', 0, 1, 0, None), ('p_isalpha', '', 0, 3, 0, None), ('p_isspecial', '', 0, 3, 0, None), (None, '', 1, 0, 1, None)],
    # TPS_InWord
    [('p_isEOF', '', 1, 0, 2, None), ('p_isalpha', '', 0, -1, 0, None), ('p_isspecial', '', 0, -1, 0, None), ('p_isdigit', '', 0, 1, 0, None), ('p_iseqC', '-', 4, 66, 0, None), (None, '', 1, 0, 2, None)],
    # TPS_InUnsignedInt
    [('p_isEOF', '', 1, 0, 22, None), ('p_isdigit', '', 0, -1, 0, None), ('p_iseqC', '.', 4, 42, 0, None), ('p_iseqC', '.', 4, 8, 0, None), ('p_iseqC', 'e', 4, 16, 0, None), ('p_iseqC', 'E', 4, 16, 0, None), ('p_iseqC', '-', 4, 47, 0, None), ('p_iseqC', '_', 4, 47, 0, None), ('p_iseqC', '@', 4, 49, 0, None), ('p_isasclet', '', 4, 48, 0, None), ('p_isalpha', '', 0, 1, 0, None), ('p_isspecial', '', 0, 1, 0, None), ('p_iseqC', '/', 4, 50, 0, None), (None, '', 1, 0, 22, None)],
    # TPS_InSignedIntFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 16, 6, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InSignedInt
    [('p_isEOF', '', 1, 0, 21, None), ('p_isdigit', '', 0, -1, 0, None), ('p_iseqC', '.', 4, 10, 0, None), ('p_iseqC', 'e', 4, 16, 0, None), ('p_iseqC', 'E', 4, 16, 0, None), (None, '', 1, 0, 21, None)],
    # TPS_InSpace
    [('p_isEOF', '', 1, 0, 12, None), ('p_iseqC', '<', 1, 0, 12, None), ('p_isignore', '', 0, -1, 0, None), ('p_iseqC', '-', 1, 0, 12, None), ('p_iseqC', '+', 1, 0, 12, None), ('p_iseqC', '&', 1, 0, 12, None), ('p_iseqC', '/', 1, 0, 12, None), ('p_isnotalnum', '', 0, 7, 0, None), (None, '', 1, 0, 12, None)],
    # TPS_InUDecimalFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 16, 9, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InUDecimal
    [('p_isEOF', '', 1, 0, 20, None), ('p_isdigit', '', 0, 9, 0, None), ('p_iseqC', '.', 4, 14, 0, None), ('p_iseqC', 'e', 4, 16, 0, None), ('p_iseqC', 'E', 4, 16, 0, None), (None, '', 1, 0, 20, None)],
    # TPS_InDecimalFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 16, 11, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InDecimal
    [('p_isEOF', '', 1, 0, 20, None), ('p_isdigit', '', 0, 11, 0, None), ('p_iseqC', '.', 4, 12, 0, None), ('p_iseqC', 'e', 4, 16, 0, None), ('p_iseqC', 'E', 4, 16, 0, None), (None, '', 1, 0, 20, None)],
    # TPS_InVerVersion
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 8, 13, 0, 'SpecialVerVersion'), (None, '', 2, -1, 0, None)],
    # TPS_InSVerVersion
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 65, 4, 12, None), (None, '', 0, -1, 0, None)],
    # TPS_InVersionFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 16, 15, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InVersion
    [('p_isEOF', '', 1, 0, 8, None), ('p_isdigit', '', 0, 15, 0, None), ('p_iseqC', '.', 4, 14, 0, None), (None, '', 1, 0, 8, None)],
    # TPS_InMantissaFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 16, 18, 0, None), ('p_iseqC', '+', 0, 17, 0, None), ('p_iseqC', '-', 0, 17, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InMantissaSign
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 16, 18, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InMantissa
    [('p_isEOF', '', 1, 0, 7, None), ('p_isdigit', '', 0, 18, 0, None), (None, '', 1, 0, 7, None)],
    # TPS_InXMLEntityFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '#', 0, 21, 0, None), ('p_isasclet', '', 0, 20, 0, None), ('p_iseqC', ':', 0, 20, 0, None), ('p_iseqC', '_', 0, 20, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InXMLEntity
    [('p_isEOF', '', 2, -1, 0, None), ('p_isalnum', '', 0, 20, 0, None), ('p_iseqC', ':', 0, 20, 0, None), ('p_iseqC', '_', 0, 20, 0, None), ('p_iseqC', '.', 0, 20, 0, None), ('p_iseqC', '-', 0, 20, 0, None), ('p_iseqC', ';', 0, 25, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InXMLEntityNumFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', 'x', 0, 23, 0, None), ('p_iseqC', 'X', 0, 23, 0, None), ('p_isdigit', '', 0, 22, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InXMLEntityNum
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 0, 22, 0, None), ('p_iseqC', ';', 0, 25, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InXMLEntityHexNumFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isxdigit', '', 0, 24, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InXMLEntityHexNum
    [('p_isEOF', '', 2, -1, 0, None), ('p_isxdigit', '', 0, 24, 0, None), ('p_iseqC', ';', 0, 25, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InXMLEntityEnd
    [(None, '', 17, 0, 23, None)],
    # TPS_InTagFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '/', 4, 28, 0, None), ('p_iseqC', '!', 4, 36, 0, None), ('p_iseqC', '?', 4, 27, 0, None), ('p_isasclet', '', 4, 29, 0, None), ('p_iseqC', ':', 4, 29, 0, None), ('p_iseqC', '_', 4, 29, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InXMLBegin
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', 'x', 0, 31, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InTagCloseFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isasclet', '', 0, 29, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InTagName
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '/', 0, 30, 0, None), ('p_iseqC', '>', 0, 35, 0, 'SpecialTags'), ('p_isspace', '', 0, 31, 0, 'SpecialTags'), ('p_isalnum', '', 0, -1, 0, None), ('p_iseqC', ':', 0, -1, 0, None), ('p_iseqC', '_', 0, -1, 0, None), ('p_iseqC', '.', 0, -1, 0, None), ('p_iseqC', '-', 0, -1, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InTagBeginEnd
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '>', 0, 35, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InTag
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '>', 0, 35, 0, 'SpecialTags'), ('p_iseqC', "'", 0, 32, 0, None), ('p_iseqC', '"', 0, 33, 0, None), ('p_isasclet', '', 0, -1, 0, None), ('p_isdigit', '', 0, -1, 0, None), ('p_iseqC', '=', 0, -1, 0, None), ('p_iseqC', '-', 0, -1, 0, None), ('p_iseqC', '_', 0, -1, 0, None), ('p_iseqC', '#', 0, -1, 0, None), ('p_iseqC', '/', 0, -1, 0, None), ('p_iseqC', ':', 0, -1, 0, None), ('p_iseqC', '.', 0, -1, 0, None), ('p_iseqC', '&', 0, -1, 0, None), ('p_iseqC', '?', 0, -1, 0, None), ('p_iseqC', '%', 0, -1, 0, None), ('p_iseqC', '~', 0, -1, 0, None), ('p_isspace', '', 0, -1, 0, 'SpecialTags'), (None, '', 2, -1, 0, None)],
    # TPS_InTagEscapeK
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '\\', 4, 34, 0, None), ('p_iseqC', "'", 0, 31, 0, None), (None, '', 0, 32, 0, None)],
    # TPS_InTagEscapeKK
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '\\', 4, 34, 0, None), ('p_iseqC', '"', 0, 31, 0, None), (None, '', 0, 33, 0, None)],
    # TPS_InTagBackSleshed
    [('p_isEOF', '', 2, -1, 0, None), (None, '', 32, -1, 0, None)],
    # TPS_InTagEnd
    [(None, '', 65, 0, 13, None)],
    # TPS_InCommentFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '-', 0, 37, 0, None), ('p_iseqC', 'D', 0, 31, 0, None), ('p_iseqC', 'd', 0, 31, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InCommentLast
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '-', 0, 38, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InComment
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '-', 0, 39, 0, None), (None, '', 0, -1, 0, None)],
    # TPS_InCloseCommentFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '-', 0, 40, 0, None), (None, '', 0, 38, 0, None)],
    # TPS_InCloseCommentLast
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '-', 0, -1, 0, None), ('p_iseqC', '>', 0, 41, 0, None), (None, '', 0, 38, 0, None)],
    # TPS_InCommentEnd
    [(None, '', 65, 0, 13, None)],
    # TPS_InHostFirstDomain
    [('p_isEOF', '', 2, -1, 0, None), ('p_isasclet', '', 0, 43, 0, None), ('p_isdigit', '', 0, 48, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InHostDomainSecond
    [('p_isEOF', '', 2, -1, 0, None), ('p_isasclet', '', 0, 44, 0, None), ('p_isdigit', '', 4, 48, 0, None), ('p_iseqC', '-', 4, 47, 0, None), ('p_iseqC', '_', 4, 47, 0, None), ('p_iseqC', '.', 4, 42, 0, None), ('p_iseqC', '@', 4, 49, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InHostDomain
    [('p_isEOF', '', 65, 0, 6, None), ('p_isasclet', '', 0, 44, 0, None), ('p_isdigit', '', 4, 48, 0, None), ('p_iseqC', ':', 4, 45, 0, None), ('p_iseqC', '-', 4, 47, 0, None), ('p_iseqC', '_', 4, 47, 0, None), ('p_iseqC', '.', 4, 42, 0, None), ('p_iseqC', '@', 4, 49, 0, None), ('p_isdigit', '', 2, -1, 0, None), ('p_isstophost', '', 65, 58, 6, None), ('p_iseqC', '/', 4, 60, 0, None), (None, '', 65, 0, 6, None)],
    # TPS_InPortFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 0, 46, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InPort
    [('p_isEOF', '', 65, 0, 6, None), ('p_isdigit', '', 0, 46, 0, None), ('p_isstophost', '', 65, 58, 6, None), ('p_iseqC', '/', 4, 60, 0, None), (None, '', 65, 0, 6, None)],
    # TPS_InHostFirstAN
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 0, 48, 0, None), ('p_isasclet', '', 0, 48, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InHost
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 0, 48, 0, None), ('p_isasclet', '', 0, 48, 0, None), ('p_iseqC', '@', 4, 49, 0, None), ('p_iseqC', '.', 4, 42, 0, None), ('p_iseqC', '-', 4, 47, 0, None), ('p_iseqC', '_', 4, 47, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InEmail
    [('p_isstophost', '', 2, -1, 0, None), ('p_ishost', '', 65, 0, 4, None), (None, '', 2, -1, 0, None)],
    # TPS_InFileFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isasclet', '', 0, 55, 0, None), ('p_isdigit', '', 0, 55, 0, None), ('p_iseqC', '.', 0, 52, 0, None), ('p_iseqC', '_', 0, 55, 0, None), ('p_iseqC', '~', 4, 51, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InFileTwiddle
    [('p_isEOF', '', 2, -1, 0, None), ('p_isasclet', '', 0, 55, 0, None), ('p_isdigit', '', 0, 55, 0, None), ('p_iseqC', '_', 0, 55, 0, None), ('p_iseqC', '/', 0, 50, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InPathFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isasclet', '', 0, 55, 0, None), ('p_isdigit', '', 0, 55, 0, None), ('p_iseqC', '_', 0, 55, 0, None), ('p_iseqC', '.', 0, 54, 0, None), ('p_iseqC', '/', 0, 50, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InPathFirstFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '.', 0, 54, 0, None), ('p_iseqC', '/', 0, 50, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InPathSecond
    [('p_isEOF', '', 17, 0, 19, None), ('p_iseqC', '/', 4, 50, 0, None), ('p_iseqC', '/', 17, 0, 19, None), ('p_isspace', '', 17, 0, 19, None), (None, '', 2, -1, 0, None)],
    # TPS_InFile
    [('p_isEOF', '', 1, 0, 19, None), ('p_isasclet', '', 0, 55, 0, None), ('p_isdigit', '', 0, 55, 0, None), ('p_iseqC', '.', 4, 56, 0, None), ('p_iseqC', '_', 0, 55, 0, None), ('p_iseqC', '-', 0, 55, 0, None), ('p_iseqC', '/', 4, 50, 0, None), (None, '', 1, 0, 19, None)],
    # TPS_InFileNext
    [('p_isEOF', '', 2, -1, 0, None), ('p_isasclet', '', 16, 55, 0, None), ('p_isdigit', '', 16, 55, 0, None), ('p_iseqC', '_', 16, 55, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InURLPathFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isurlchar', '', 0, 59, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InURLPathStart
    [(None, '', 0, 59, 0, None)],
    # TPS_InURLPath
    [('p_isEOF', '', 1, 0, 18, None), ('p_isurlchar', '', 0, 59, 0, None), (None, '', 1, 0, 18, None)],
    # TPS_InFURL
    [('p_isEOF', '', 2, -1, 0, None), ('p_isURLPath', '', 65, 0, 5, 'SpecialFURL'), (None, '', 2, -1, 0, None)],
    # TPS_InProtocolFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '/', 0, 62, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InProtocolSecond
    [('p_isEOF', '', 2, -1, 0, None), ('p_iseqC', '/', 0, 63, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InProtocolEnd
    [(None, '', 65, 0, 14, None)],
    # TPS_InHyphenAsciiWordFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isasclet', '', 0, 65, 0, None), ('p_isalpha', '', 0, 67, 0, None), ('p_isdigit', '', 0, 70, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InHyphenAsciiWord
    [('p_isEOF', '', 65, 71, 16, 'SpecialHyphen'), ('p_isasclet', '', 0, 65, 0, None), ('p_isalpha', '', 0, 67, 0, None), ('p_isspecial', '', 0, 67, 0, None), ('p_isdigit', '', 0, 69, 0, None), ('p_iseqC', '-', 4, 64, 0, None), (None, '', 65, 71, 16, 'SpecialHyphen')],
    # TPS_InHyphenWordFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isalpha', '', 0, 67, 0, None), ('p_isdigit', '', 0, 70, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InHyphenWord
    [('p_isEOF', '', 65, 71, 17, 'SpecialHyphen'), ('p_isalpha', '', 0, 67, 0, None), ('p_isspecial', '', 0, 67, 0, None), ('p_isdigit', '', 0, 69, 0, None), ('p_iseqC', '-', 4, 66, 0, None), (None, '', 65, 71, 17, 'SpecialHyphen')],
    # TPS_InHyphenNumWordFirst
    [('p_isEOF', '', 2, -1, 0, None), ('p_isalpha', '', 0, 69, 0, None), ('p_isdigit', '', 0, 70, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InHyphenNumWord
    [('p_isEOF', '', 65, 71, 15, 'SpecialHyphen'), ('p_isalnum', '', 0, 69, 0, None), ('p_isspecial', '', 0, 69, 0, None), ('p_iseqC', '-', 4, 68, 0, None), (None, '', 65, 71, 15, 'SpecialHyphen')],
    # TPS_InHyphenDigitLookahead
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 0, 70, 0, None), ('p_isalpha', '', 0, 69, 0, None), ('p_isspecial', '', 0, 69, 0, None), (None, '', 2, -1, 0, None)],
    # TPS_InParseHyphen
    [('p_isEOF', '', 8, 0, 0, None), ('p_isasclet', '', 0, 74, 0, None), ('p_isalpha', '', 0, 73, 0, None), ('p_isdigit', '', 4, 76, 0, None), ('p_iseqC', '-', 4, 72, 0, None), (None, '', 8, 0, 0, None)],
    # TPS_InParseHyphenHyphen
    [('p_isEOF', '', 2, -1, 0, None), ('p_isalnum', '', 17, 71, 12, None), ('p_isspecial', '', 17, 71, 12, None), (None, '', 2, -1, 0, None)],
    # TPS_InHyphenWordPart
    [('p_isEOF', '', 1, 0, 10, None), ('p_isalpha', '', 0, 73, 0, None), ('p_isspecial', '', 0, 73, 0, None), ('p_isdigit', '', 0, 75, 0, None), (None, '', 1, 71, 10, None)],
    # TPS_InHyphenAsciiWordPart
    [('p_isEOF', '', 1, 0, 11, None), ('p_isasclet', '', 0, 74, 0, None), ('p_isalpha', '', 0, 73, 0, None), ('p_isspecial', '', 0, 73, 0, None), ('p_isdigit', '', 0, 75, 0, None), (None, '', 1, 71, 11, None)],
    # TPS_InHyphenNumWordPart
    [('p_isEOF', '', 1, 0, 9, None), ('p_isalnum', '', 0, 75, 0, None), ('p_isspecial', '', 0, 75, 0, None), (None, '', 1, 71, 9, None)],
    # TPS_InHyphenUnsignedInt
    [('p_isEOF', '', 2, -1, 0, None), ('p_isdigit', '', 0, -1, 0, None), ('p_isalpha', '', 16, 75, 0, None), ('p_isspecial', '', 16, 75, 0, None), (None, '', 2, -1, 0, None)],
]
