#!/usr/bin/env python3
"""Generate app/services/posterchandb/pg_parser_tables.py from PostgreSQL's default text-search parser.

PosterChanDB must tokenise text EXACTLY as the relay's Postgres does (`to_tsvector('simple', content)`), or
search answers differ. Rather than re-deriving ~75 state tables by hand, this reads them out of the real C
source (src/backend/tsearch/wparser_def.c) and writes them as Python data. Re-run it only to follow a new
Postgres release, then re-run tests/test_posterchandb_tsparser.py against that release.

    scripts/gen_pg_parser_tables.py /path/to/postgresql-18.4.tar.bz2
"""
import re
import sys
import tarfile

src_tar = sys.argv[1]
with tarfile.open(src_tar) as t:
    name = [n for n in t.getnames() if n.endswith("src/backend/tsearch/wparser_def.c")][0]
    version = name.split("/")[0]
    c = t.extractfile(name).read().decode()

states = re.search(r"typedef enum\s*\{(.*?)\}\s*TParserState;", c, re.S).group(1)
states = [s.strip() for s in re.sub(r"/\*.*?\*/", "", states, flags=re.S).split(",") if s.strip()]
states = [s.split("=")[0].strip() for s in states]
types = {}
for m in re.finditer(r"#define\s+([A-Z_]+)\s+(\d+)\s*\n", c):
    types[m.group(1)] = int(m.group(2))
aliases = re.search(r"tok_alias\[\]\s*=\s*\{(.*?)\};", c, re.S).group(1)
aliases = re.findall(r'"([^"]*)"', aliases)
flags = {k: int(v, 16) for k, v in re.findall(r"#define\s+(A_[A-Z]+)\s+(0x[0-9a-fA-F]+)", c)}
strange = re.search(r"strange_letter\[\]\s*=\s*\{(.*?)\};", c, re.S).group(1)
strange = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]+)", re.sub(r"/\*.*?\*/", "", strange, flags=re.S))]


def char(tok):
    tok = tok.strip()
    if tok == "0":
        return ""
    m = re.fullmatch(r"'(\\?.)'", tok)
    v = m.group(1)
    return {"\\\\": "\\", "\\'": "'"}.get(v, v)


tables = {}
for m in re.finditer(r"static const TParserStateActionItem action(TPS_\w+)\[\]\s*=\s*\{(.*?)\n\};", c, re.S):
    rows = []
    for row in re.findall(r"\{([^{}]*)\}", m.group(2)):
        # fields, where a C char literal ('x', '\\'', ',') is one field however it is spelled
        parts = [p.strip() for p in re.findall(r"\s*('(?:\\.|[^'\\])'|[^,]+)\s*(?:,|$)", row)]
        if len(parts) != 6:
            raise SystemExit("cannot parse row in %s: %r" % (m.group(1), row))
        isclass, ch, fl, to, typ, special = parts
        f = 0
        for x in fl.split("|"):
            f |= flags[x.strip()]
        rows.append((None if isclass == "NULL" else isclass, char(ch), f, states.index(to) if to != "TPS_Null" else -1,
                     types[typ] if typ != "0" else 0, None if special == "NULL" else special))
    tables[m.group(1)] = rows
order = re.search(r"static const TParserStateAction Actions\[\]\s*=\s*\{(.*?)\};", c, re.S).group(1)
order = re.findall(r"TPARSERSTATEACTION\((TPS_\w+)\)", order)
assert order == states[:-1], "Actions[] must follow the state enum"

out = ['"""GENERATED by scripts/gen_pg_parser_tables.py from %s src/backend/tsearch/wparser_def.c -- do not edit.' % version,
       "",
       "Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group (PostgreSQL License).",
       '"""', "", "PG_VERSION = %r" % version, "STATES = %r" % states, "TOK_ALIAS = %r" % aliases,
       "FLAGS = %r" % flags, "STRANGE_LETTER = frozenset(%r)" % strange, "ACTIONS = ["]
for s in order:
    out.append("    # %s" % s)
    out.append("    %r," % (tables[s],))
out.append("]")
open("app/services/posterchandb/pg_parser_tables.py", "w").write("\n".join(out) + "\n")
print("wrote %d states from %s" % (len(order), version))
